import type { AppLocale } from '@/lib/i18n';
import type { ManagerTaskStatus } from '@/lib/lex/manager-tasks';

export const MANAGER_TASK_STATUS_ORDER: ManagerTaskStatus[] = [
  'assigned',
  'in_progress',
  'submitted',
  'correction_required',
  'accepted',
  'cancelled',
];

const COPY = {
  en: {
    page: {
      eyebrow: 'Legal team',
      title: 'Tasks',
      description:
        'Assign work, track delivery, and complete the manager review loop.',
    },
    create: 'Create task',
    refresh: 'Refresh',
    allStatuses: 'All statuses',
    filterLabel: 'Filter by status',
    kpis: {
      assigned: 'Assigned',
      active: 'In progress',
      review: 'Awaiting review',
      accepted: 'Accepted',
    },
    status: {
      assigned: 'Assigned',
      in_progress: 'In progress',
      submitted: 'Submitted',
      correction_required: 'Correction required',
      accepted: 'Accepted',
      cancelled: 'Cancelled',
    } satisfies Record<ManagerTaskStatus, string>,
    list: {
      title: 'Task tracking',
      description: 'Live status for assigned legal work.',
      emptyTitle: 'No tasks found',
      emptyBody: 'Create a task or choose a different status filter.',
      errorTitle: 'Tasks could not be loaded',
      errorBody: 'Check your connection and try again.',
      assignedTo: 'Assigned to',
      created: 'Created',
      updated: 'Last updated',
      attachment: 'Attachment',
      result: 'Submitted result',
      correction: 'Correction note',
      unknownUser: 'Unknown user',
      total: (count: string) => `${count} total tasks`,
    },
    actions: {
      start: 'Start task',
      submit: 'Submit result',
      review: 'Review submission',
      retry: 'Try again',
    },
    createDialog: {
      title: 'Create and assign task',
      description: 'Give one legal team member a clear, trackable work item.',
      titleLabel: 'Task title',
      titlePlaceholder: 'e.g. Review renewal terms',
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Describe the required work and expected outcome.',
      assigneeLabel: 'Assignee',
      assigneePlaceholder: 'Select a team member',
      assigneesLoading: 'Loading team members…',
      noAssignees: 'No active team members are available.',
      attachmentLabel: 'Optional attachment',
      attachmentHint: 'The file is securely uploaded when the task is created.',
      chooseFile: 'Choose file',
      removeFile: 'Remove',
      cancel: 'Cancel',
      submit: 'Create task',
      saving: 'Creating…',
    },
    submitDialog: {
      title: 'Submit task result',
      description: 'Send your completed work to the assigning manager for review.',
      resultLabel: 'Result and evidence',
      resultPlaceholder: 'Summarize the work completed and key findings.',
      cancel: 'Cancel',
      submit: 'Submit for review',
      saving: 'Submitting…',
    },
    reviewDialog: {
      title: 'Review task submission',
      description: 'Accept the result or return it with a clear correction note.',
      resultLabel: 'Submitted result',
      noteLabel: 'Correction note',
      notePlaceholder: 'Explain what must be corrected before resubmission.',
      cancel: 'Cancel',
      accept: 'Accept',
      return: 'Return for correction',
      saving: 'Saving decision…',
    },
    toast: {
      created: 'Task created and assigned',
      started: 'Task started',
      submitted: 'Task submitted for review',
      accepted: 'Task accepted',
      returned: 'Task returned for correction',
    },
  },
  ar: {
    page: {
      eyebrow: 'الفريق القانوني',
      title: 'المهام',
      description: 'إسناد العمل ومتابعة الإنجاز وإكمال دورة مراجعة المدير المسؤول.',
    },
    create: 'إنشاء مهمة',
    refresh: 'تحديث',
    allStatuses: 'جميع الحالات',
    filterLabel: 'تصفية حسب الحالة',
    kpis: {
      assigned: 'مسندة',
      active: 'قيد التنفيذ',
      review: 'بانتظار المراجعة',
      accepted: 'مقبولة',
    },
    status: {
      assigned: 'مسندة',
      in_progress: 'قيد التنفيذ',
      submitted: 'مقدمة للمراجعة',
      correction_required: 'تتطلب تصحيحاً',
      accepted: 'مقبولة',
      cancelled: 'ملغاة',
    } satisfies Record<ManagerTaskStatus, string>,
    list: {
      title: 'متابعة المهام',
      description: 'الحالة المباشرة للأعمال القانونية المسندة.',
      emptyTitle: 'لا توجد مهام',
      emptyBody: 'أنشئ مهمة جديدة أو اختر حالة أخرى.',
      errorTitle: 'تعذر تحميل المهام',
      errorBody: 'تحقق من الاتصال ثم أعد المحاولة.',
      assignedTo: 'مسندة إلى',
      created: 'تاريخ الإنشاء',
      updated: 'آخر تحديث',
      attachment: 'المرفق',
      result: 'النتيجة المقدمة',
      correction: 'ملاحظة التصحيح',
      unknownUser: 'مستخدم غير معروف',
      total: (count: string) => `إجمالي المهام: ${count}`,
    },
    actions: {
      start: 'بدء المهمة',
      submit: 'تقديم النتيجة',
      review: 'مراجعة النتيجة',
      retry: 'إعادة المحاولة',
    },
    createDialog: {
      title: 'إنشاء مهمة وإسنادها',
      description: 'أنشئ عملاً واضحاً وقابلاً للمتابعة لأحد أعضاء الفريق القانوني.',
      titleLabel: 'عنوان المهمة',
      titlePlaceholder: 'مثال: مراجعة شروط التجديد',
      descriptionLabel: 'الوصف',
      descriptionPlaceholder: 'صف العمل المطلوب والنتيجة المتوقعة.',
      assigneeLabel: 'المكلّف',
      assigneePlaceholder: 'اختر عضواً من الفريق',
      assigneesLoading: 'جارٍ تحميل أعضاء الفريق…',
      noAssignees: 'لا يوجد أعضاء نشطون متاحون.',
      attachmentLabel: 'مرفق اختياري',
      attachmentHint: 'يُرفع الملف بشكل آمن عند إنشاء المهمة.',
      chooseFile: 'اختيار ملف',
      removeFile: 'إزالة',
      cancel: 'إلغاء',
      submit: 'إنشاء المهمة',
      saving: 'جارٍ الإنشاء…',
    },
    submitDialog: {
      title: 'تقديم نتيجة المهمة',
      description: 'أرسل العمل المنجز إلى المدير الذي أسند المهمة للمراجعة.',
      resultLabel: 'النتيجة والأدلة',
      resultPlaceholder: 'لخّص العمل المنجز وأهم النتائج.',
      cancel: 'إلغاء',
      submit: 'إرسال للمراجعة',
      saving: 'جارٍ الإرسال…',
    },
    reviewDialog: {
      title: 'مراجعة نتيجة المهمة',
      description: 'اقبل النتيجة أو أعدها مع ملاحظة تصحيح واضحة.',
      resultLabel: 'النتيجة المقدمة',
      noteLabel: 'ملاحظة التصحيح',
      notePlaceholder: 'وضّح ما يجب تصحيحه قبل إعادة التقديم.',
      cancel: 'إلغاء',
      accept: 'قبول',
      return: 'إعادة للتصحيح',
      saving: 'جارٍ حفظ القرار…',
    },
    toast: {
      created: 'تم إنشاء المهمة وإسنادها',
      started: 'تم بدء المهمة',
      submitted: 'تم إرسال المهمة للمراجعة',
      accepted: 'تم قبول المهمة',
      returned: 'تمت إعادة المهمة للتصحيح',
    },
  },
} as const;

export type ManagerTasksCopy = (typeof COPY)['en'] | (typeof COPY)['ar'];

export function managerTasksCopy(locale: AppLocale | string): ManagerTasksCopy {
  return locale === 'ar' ? COPY.ar : COPY.en;
}
