{{- if .Values.visusService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clario360.componentName" (dict "root" . "component" "visus-service") }}
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "visus-service") | nindent 4 }}
  {{- with ((.Values.visusService).service).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ dig "service" "type" "ClusterIP" .Values.visusService }}
  ports:
    - name: http
      port: 8088
      targetPort: http
      protocol: TCP
    - name: admin
      port: 9088
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "clario360.componentSelectorLabels" (dict "root" . "component" "visus-service") | nindent 4 }}
{{- end }}
