import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const __dirname = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });
const nextVitals = compat.extends('next/core-web-vitals');

/* ==========================================================================
 * Design-system guardrails (Items 24/50 — CI guardrails)
 *
 * Severity is WARN so existing code keeps building (`eslint .` exits 0 on
 * warnings). POLICY: for NEW code these are treated as errors — reviewers
 * must not merge code that adds new occurrences. The complementary ratchet
 * (`npm run lint:ds` → scripts/lint-design-system.mjs) hard-fails when the
 * repo-wide count of violations grows past the committed baseline, so the
 * warn severity here cannot silently regress.
 * ========================================================================== */

/** Hardcoded hex colors — consume --ds-* tokens / Tailwind theme colors. */
const dsHexColorSelectors = [
  {
    selector:
      "JSXAttribute[name.name=/^(className|class)$/] Literal[value=/#[0-9a-fA-F]{3}/]",
    message:
      'Hardcoded hex color in className. Use --ds-* tokens via the Tailwind theme (e.g. bg-primary, text-muted-foreground) instead of arbitrary values like bg-[#...].',
  },
  {
    selector:
      "JSXAttribute[name.name=/^(className|class)$/] TemplateElement[value.raw=/#[0-9a-fA-F]{3}/]",
    message:
      'Hardcoded hex color in a className template literal. Use --ds-* tokens via the Tailwind theme instead of arbitrary values like bg-[#...].',
  },
  {
    selector:
      "CallExpression[callee.name=/^(cn|clsx|cx|cva|twMerge)$/] Literal[value=/#[0-9a-fA-F]{3}/]",
    message:
      'Hardcoded hex color in a class-composition call (cn/clsx/cva). Use --ds-* tokens via the Tailwind theme instead.',
  },
  {
    selector:
      "Property[key.name=/^(color|backgroundColor|background|backgroundImage|borderColor|borderTopColor|borderRightColor|borderBottomColor|borderLeftColor|outlineColor|caretColor|textDecorationColor|fill|stroke|boxShadow)$/] > Literal[value=/#[0-9a-fA-F]{3}/]",
    message:
      "Hardcoded hex color in a style object. Use a design token: style={{ color: 'var(--ds-...)' }} or a themed utility class.",
  },
];

/** Raw HTML elements that must go through the design-system primitives. */
const dsRawElementSelectors = [
  {
    selector: "JSXOpeningElement[name.name='table']",
    message:
      'Raw <table> outside the table primitives. Use DataTable (@/components/shared/data-table) or SimpleTable (@/components/shared/simple-table) so sorting, empty states, RTL and .table-premium styling stay consistent.',
  },
  {
    selector: "JSXOpeningElement[name.name='button']",
    message:
      'Raw <button> outside components/ui. Use Button (@/components/ui/button) — it carries the .btn-* tokens, focus-visible ring, disabled and dark-mode states.',
  },
];

/**
 * Deprecated thin-adapter components → canonical primitives.
 * The adapters stay for backward compatibility; NEW imports should target
 * the canonical component named in each message.
 */
const dsDeprecatedImportPaths = [
  {
    name: '@/components/shared/kpi-card',
    message: 'Deprecated adapter. Use StatTile from @/components/shared/stat-tile.',
  },
  {
    name: '@/components/dashboard/kpi-card',
    message: 'Deprecated re-export. Use StatTile from @/components/shared/stat-tile.',
  },
  {
    name: '@/components/shared/stat-card',
    message: 'Deprecated adapter. Use StatTile from @/components/shared/stat-tile.',
  },
  {
    name: '@/components/shared/detail-stat-card',
    message: 'Deprecated adapter. Use StatTile from @/components/shared/stat-tile.',
  },
  {
    name: '@/components/shared/metric-tile',
    message: 'Deprecated adapter. Use StatTile (size="sm") from @/components/shared/stat-tile.',
  },
  {
    name: '@/components/shared/status-chip',
    message: 'Deprecated adapter. Use StatusBadge from @/components/shared/status-badge.',
  },
  {
    name: '@/components/lex/status-chip',
    message:
      'Deprecated adapter (keeps the Lex domain maps only). New code should use StatusBadge from @/components/shared/status-badge.',
  },
  {
    name: '@/components/ui/status-pill',
    message: 'Deprecated adapter. Use StatusBadge from @/components/shared/status-badge.',
  },
  {
    name: '@/components/cyber/cti/severity-badge',
    message:
      'Deprecated adapter. Use StatusBadge with severityMap from @/components/shared/status-badge.',
  },
  {
    name: '@/components/lex/empty-state',
    message: 'Deprecated adapter. Use EmptyState from @/components/common/empty-state.',
  },
  {
    name: '@/components/shared/section-empty',
    message:
      'Deprecated adapter. Use EmptyState (size="compact") from @/components/common/empty-state.',
  },
  {
    name: '@/components/shared/data-table/data-table-empty',
    message: 'Deprecated adapter. Use EmptyState from @/components/common/empty-state.',
  },
  {
    name: '@/components/lex/list-skeleton',
    message:
      'Deprecated adapter. Use Skeleton.Table / Skeleton.Board from @/components/ui/skeleton.',
  },
  {
    name: '@/components/common/loading-skeleton',
    message:
      'Deprecated adapter. Use Skeleton (shaped variants) from @/components/ui/skeleton.',
  },
  {
    name: '@/components/shared/simple-table',
    importNames: ['DataTable'],
    message:
      'Deprecated alias. Import SimpleTable from this module, or the full DataTable from @/components/shared/data-table.',
  },
];

/* ==========================================================================
 * DS-guardrail RATCHET (F52) — freeze the two design-system rules at today's
 * footprint so the warning count cannot INCREASE.
 *
 * The two rules below (`no-restricted-syntax`, `no-restricted-imports`) are
 * promoted to ERROR everywhere, then downgraded back to WARN for exactly the
 * files that already violate them today (`dsRatchetAllowlist`, snapshotted
 * from `npx eslint .`). Net effect: the ~1,061 pre-existing warnings keep the
 * build green, but ANY new file (or a clean file that regresses) hard-fails
 * `eslint .`. The list only shrinks — delete a path once its file is clean.
 * Re-snapshot after a cleanup sweep with the helper in package.json / by
 * re-running `npx eslint . -f json` and pruning fixed paths.
 * ========================================================================== */
const dsRatchetAllowlist = [
  "src/app/\\(auth\\)/invite/page.tsx",
  "src/app/\\(dashboard\\)/acta/_components/acta-calendar-widget.tsx",
  "src/app/\\(dashboard\\)/acta/_components/acta-dashboard-kpis.tsx",
  "src/app/\\(dashboard\\)/acta/action-items/page.tsx",
  "src/app/\\(dashboard\\)/acta/committees/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/acta/committees/_components/committee-stats.tsx",
  "src/app/\\(dashboard\\)/acta/committees/page.tsx",
  "src/app/\\(dashboard\\)/acta/compliance/page.tsx",
  "src/app/\\(dashboard\\)/acta/meetings/\\[id\\]/_components/agenda-item-card.tsx",
  "src/app/\\(dashboard\\)/acta/meetings/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/acta/meetings/page.tsx",
  "src/app/\\(dashboard\\)/acta/page.tsx",
  "src/app/\\(dashboard\\)/admin/ai-governance/\\[modelId\\]/page.tsx",
  "src/app/\\(dashboard\\)/admin/ai-governance/\\[modelId\\]/validate/_components/metrics-cards.tsx",
  "src/app/\\(dashboard\\)/admin/ai-governance/_components/model-card.tsx",
  "src/app/\\(dashboard\\)/admin/ai-governance/_components/prediction-log-table.tsx",
  "src/app/\\(dashboard\\)/admin/ai-governance/benchmarks/\\[suiteId\\]/page.tsx",
  "src/app/\\(dashboard\\)/admin/ai-governance/benchmarks/page.tsx",
  "src/app/\\(dashboard\\)/admin/audit/_components/audit-detail-panel.tsx",
  "src/app/\\(dashboard\\)/admin/audit/_components/audit-export-form.tsx",
  "src/app/\\(dashboard\\)/admin/audit/_components/json-diff-viewer.tsx",
  "src/app/\\(dashboard\\)/admin/audit/logs/\\[logId\\]/_components/changes-diff.tsx",
  "src/app/\\(dashboard\\)/admin/audit/logs/\\[logId\\]/_components/json-viewer.tsx",
  "src/app/\\(dashboard\\)/admin/audit/logs/\\[logId\\]/_components/log-detail.tsx",
  "src/app/\\(dashboard\\)/admin/audit/timeline/\\[resourceId\\]/_components/resource-timeline.tsx",
  "src/app/\\(dashboard\\)/admin/billing/page.tsx",
  "src/app/\\(dashboard\\)/admin/integrations/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/admin/integrations/_components/integration-form-dialog.tsx",
  "src/app/\\(dashboard\\)/admin/integrations/page.tsx",
  "src/app/\\(dashboard\\)/admin/integrations/ticket-links/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/admin/invitations/page.tsx",
  "src/app/\\(dashboard\\)/admin/notifications/components/delivery-dashboard.tsx",
  "src/app/\\(dashboard\\)/admin/notifications/webhooks/\\[webhookId\\]/components/webhook-overview.tsx",
  "src/app/\\(dashboard\\)/admin/notifications/webhooks/\\[webhookId\\]/page.tsx",
  "src/app/\\(dashboard\\)/admin/page.tsx",
  "src/app/\\(dashboard\\)/admin/roles/_components/permission-tree.tsx",
  "src/app/\\(dashboard\\)/admin/roles/_components/role-card.tsx",
  "src/app/\\(dashboard\\)/admin/roles/_components/role-form-dialog.tsx",
  "src/app/\\(dashboard\\)/admin/roles/page.tsx",
  "src/app/\\(dashboard\\)/admin/settings/_components/current-tenant-settings.tsx",
  "src/app/\\(dashboard\\)/admin/tenants/\\[tenantId\\]/_components/tenant-detail.tsx",
  "src/app/\\(dashboard\\)/admin/tenants/new/page.tsx",
  "src/app/\\(dashboard\\)/admin/tenants/page.tsx",
  "src/app/\\(dashboard\\)/admin/users/page.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/analytics/_components/task-workload-table.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/analytics/_components/workflow-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/\\[defId\\]/components/definition-detail.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/\\[defId\\]/designer/components/approval-chain-editor.test.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/\\[defId\\]/designer/components/form-schema-builder.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/\\[defId\\]/designer/components/properties-panel.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/\\[defId\\]/designer/components/step-palette.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/\\[defId\\]/designer/components/workflow-canvas.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/\\[defId\\]/designer/designer-page-client.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/_components/definition-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/definitions/components/definition-columns.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/forms/forms-admin.roundtrip.test.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/forms/page.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/instances/\\[instanceId\\]/components/instance-detail.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/instances/components/admin-instance-columns.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/instances/components/instances-list.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/instances/components/start-workflow-dialog.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/page.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/tasks/\\[id\\]/admin-task-detail-client.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/tasks/components/admin-task-delegate-dialog.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/tasks/components/admin-task-list.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/tasks/components/task-detail-panel.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/templates/\\[templateId\\]/template-detail-client.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/templates/components/template-gallery.tsx",
  "src/app/\\(dashboard\\)/admin/workflows/templates/loading.tsx",
  "src/app/\\(dashboard\\)/console/platform/_components/critical-audit-panel.tsx",
  "src/app/\\(dashboard\\)/console/platform/_components/license-expiries-panel.tsx",
  "src/app/\\(dashboard\\)/console/platform/_components/provisioning-ticker.tsx",
  "src/app/\\(dashboard\\)/console/platform/ai/_components/ai-kpi-row.tsx",
  "src/app/\\(dashboard\\)/console/platform/ai/_components/model-drilldown-panel.tsx",
  "src/app/\\(dashboard\\)/console/platform/audit/_components/audit-export-tab.tsx",
  "src/app/\\(dashboard\\)/console/platform/audit/_components/audit-integrity-tab.tsx",
  "src/app/\\(dashboard\\)/console/platform/licensing/_components/usage-seats-tab.tsx",
  "src/app/\\(dashboard\\)/console/platform/licensing/page.tsx",
  "src/app/\\(dashboard\\)/console/platform/licensing/plans/\\[planKey\\]/page.tsx",
  "src/app/\\(dashboard\\)/console/platform/page.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/cost-breakdown-chart.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/pricing-inputs.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/quote-client-view.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/quote-detail.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/quote-tier-table.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/scenario-compare.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/scenario-drawer.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/_components/tier-comparison.tsx",
  "src/app/\\(dashboard\\)/console/platform/pricing/quotes/page.tsx",
  "src/app/\\(dashboard\\)/console/platform/provisioning/_components/provisioning-table.tsx",
  "src/app/\\(dashboard\\)/console/platform/provisioning/_components/step-list.tsx",
  "src/app/\\(dashboard\\)/console/platform/provisioning/page.tsx",
  "src/app/\\(dashboard\\)/console/platform/services/_components/event-dlq-tab.tsx",
  "src/app/\\(dashboard\\)/console/platform/services/_components/health-grid.tsx",
  "src/app/\\(dashboard\\)/console/platform/suites/_components/route-map-table.tsx",
  "src/app/\\(dashboard\\)/console/platform/suites/_components/suite-card.tsx",
  "src/app/\\(dashboard\\)/console/platform/suites/suites-client.tsx",
  "src/app/\\(dashboard\\)/console/platform/tenants/\\[tenantId\\]/_components/platform-tenant-detail.tsx",
  "src/app/\\(dashboard\\)/console/platform/tenants/page.tsx",
  "src/app/\\(dashboard\\)/cyber/_components/mitre-heatmap-widget.tsx",
  "src/app/\\(dashboard\\)/cyber/_components/recent-alerts-table.tsx",
  "src/app/\\(dashboard\\)/cyber/_components/soc-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/cyber/_components/top-attacked-assets-table.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/_components/alert-comments.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/_components/alert-evidence-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/_components/alert-evidence.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/_components/alert-investigation-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/_components/alert-related.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/_components/alert-timeline-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/_components/alert-timeline.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/_components/alert-stat-bar.tsx",
  "src/app/\\(dashboard\\)/cyber/alerts/_components/alert-stats-bar.tsx",
  "src/app/\\(dashboard\\)/cyber/analytics/_components/alert-volume-forecast.tsx",
  "src/app/\\(dashboard\\)/cyber/analytics/_components/campaign-detection.tsx",
  "src/app/\\(dashboard\\)/cyber/analytics/_components/technique-trends.tsx",
  "src/app/\\(dashboard\\)/cyber/analytics/_components/threat-forecast.tsx",
  "src/app/\\(dashboard\\)/cyber/analytics/_components/threat-landscape.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/\\[id\\]/_components/asset-activity-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/\\[id\\]/_components/asset-alerts-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/\\[id\\]/_components/asset-config-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/\\[id\\]/_components/asset-relationships-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/\\[id\\]/_components/asset-vulnerabilities-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/_components/add-relationship-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/_components/asset-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/_components/bulk-import-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/_components/bulk-tag-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/_components/tag-management-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/scans/\\[id\\]/_components/scan-assets-table.tsx",
  "src/app/\\(dashboard\\)/cyber/assets/scans/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/ctem/\\[id\\]/_components/assessment-comparison.tsx",
  "src/app/\\(dashboard\\)/cyber/ctem/\\[id\\]/_components/assessment-report-view.tsx",
  "src/app/\\(dashboard\\)/cyber/ctem/\\[id\\]/_components/finding-table.tsx",
  "src/app/\\(dashboard\\)/cyber/ctem/\\[id\\]/_components/remediation-groups.tsx",
  "src/app/\\(dashboard\\)/cyber/ctem/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/ctem/dashboard/page.tsx",
  "src/app/\\(dashboard\\)/cyber/ctem/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/actors/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/brand-abuse/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/brand-abuse/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/campaigns/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/campaigns/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/events/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/geo/page.tsx",
  "src/app/\\(dashboard\\)/cyber/cti/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/_components/dspm-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/_components/policy-impact-preview.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/_components/remediation-queue-table.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/access/_components/access-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/access/_components/identity-risk-table.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/access/_components/overprivilege-findings.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/access/_components/stale-access-list.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/access/identities/\\[identityId\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/access/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/access/policies/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/ai-security/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/assets/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/assets/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/compliance/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/exceptions/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/financial/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/lineage/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/policies/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/proliferation/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/remediations/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/dspm/remediations/page.tsx",
  "src/app/\\(dashboard\\)/cyber/events/page.tsx",
  "src/app/\\(dashboard\\)/cyber/indicators/_components/bulk-import-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/indicators/_components/indicator-columns.tsx",
  "src/app/\\(dashboard\\)/cyber/indicators/_components/indicator-detail-panel.tsx",
  "src/app/\\(dashboard\\)/cyber/indicators/_components/indicator-stats.tsx",
  "src/app/\\(dashboard\\)/cyber/mitre/_components/mitre-cell.tsx",
  "src/app/\\(dashboard\\)/cyber/mitre/_components/mitre-coverage-stats.tsx",
  "src/app/\\(dashboard\\)/cyber/mitre/_components/mitre-technique-panel.tsx",
  "src/app/\\(dashboard\\)/cyber/mitre/page.tsx",
  "src/app/\\(dashboard\\)/cyber/page.tsx",
  "src/app/\\(dashboard\\)/cyber/remediation/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/remediation/_components/execution-results-panel.tsx",
  "src/app/\\(dashboard\\)/cyber/remediation/_components/remediation-create-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/remediation/page.tsx",
  "src/app/\\(dashboard\\)/cyber/risk-heatmap/_components/heatmap-summary-table.tsx",
  "src/app/\\(dashboard\\)/cyber/risk-heatmap/page.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/\\[ruleId\\]/_components/rule-overview.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/\\[ruleId\\]/_components/rule-performance.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/\\[ruleId\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/_components/rule-form-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/_components/rule-mitre-selector.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/_components/rule-stats.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/_components/rule-template-gallery.tsx",
  "src/app/\\(dashboard\\)/cyber/rules/_components/rule-wizard.tsx",
  "src/app/\\(dashboard\\)/cyber/threat-feeds/_components/feed-detail.tsx",
  "src/app/\\(dashboard\\)/cyber/threat-feeds/_components/feed-list.tsx",
  "src/app/\\(dashboard\\)/cyber/threat-feeds/page.tsx",
  "src/app/\\(dashboard\\)/cyber/threats/\\[threatId\\]/_components/threat-alerts-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/threats/\\[threatId\\]/_components/threat-indicators-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/threats/\\[threatId\\]/_components/threat-mitre-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/threats/\\[threatId\\]/_components/threat-overview.tsx",
  "src/app/\\(dashboard\\)/cyber/threats/\\[threatId\\]/_components/threat-timeline-tab.tsx",
  "src/app/\\(dashboard\\)/cyber/threats/\\[threatId\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/threats/_components/threat-columns.tsx",
  "src/app/\\(dashboard\\)/cyber/ueba/_components/profile-table.tsx",
  "src/app/\\(dashboard\\)/cyber/ueba/alerts/page.tsx",
  "src/app/\\(dashboard\\)/cyber/ueba/page.tsx",
  "src/app/\\(dashboard\\)/cyber/ueba/profiles/\\[entityId\\]/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/_components/conversation-list.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/_components/llm-ops-panel.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/_components/message-bubble.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/_components/recommendations-list.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/awareness/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/compliance/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/evidence/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/incident-readiness/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/integrations/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/maturity/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/policies/_components/policy-form-dialog.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/policies/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/risk-register/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/third-party/page.tsx",
  "src/app/\\(dashboard\\)/cyber/vciso/workflows/page.tsx",
  "src/app/\\(dashboard\\)/dashboard/loading.tsx",
  "src/app/\\(dashboard\\)/data/analytics/_components/model-browser.tsx",
  "src/app/\\(dashboard\\)/data/analytics/_components/query-results-table.tsx",
  "src/app/\\(dashboard\\)/data/analytics/_components/saved-queries-list.tsx",
  "src/app/\\(dashboard\\)/data/analytics/page.tsx",
  "src/app/\\(dashboard\\)/data/contradictions/_components/contradiction-stat-bar.tsx",
  "src/app/\\(dashboard\\)/data/contradictions/page.tsx",
  "src/app/\\(dashboard\\)/data/dark-data/_components/darkdata-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/data/dark-data/page.tsx",
  "src/app/\\(dashboard\\)/data/lineage/_components/lineage-search.tsx",
  "src/app/\\(dashboard\\)/data/lineage/page.tsx",
  "src/app/\\(dashboard\\)/data/models/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/data/models/_components/model-kpi-cards.tsx",
  "src/app/\\(dashboard\\)/data/models/_components/model-schema-viewer.tsx",
  "src/app/\\(dashboard\\)/data/page.tsx",
  "src/app/\\(dashboard\\)/data/pipelines/\\[id\\]/_components/pipeline-runs-tab.tsx",
  "src/app/\\(dashboard\\)/data/pipelines/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/data/pipelines/_components/create-pipeline-wizard.tsx",
  "src/app/\\(dashboard\\)/data/pipelines/_components/transform-builder/transform-card.tsx",
  "src/app/\\(dashboard\\)/data/pipelines/_components/transform-builder/transform-list.tsx",
  "src/app/\\(dashboard\\)/data/pipelines/_components/wizard-step-basic.tsx",
  "src/app/\\(dashboard\\)/data/quality/_components/quality-rule-form.tsx",
  "src/app/\\(dashboard\\)/data/quality/page.tsx",
  "src/app/\\(dashboard\\)/data/sources/\\[id\\]/_components/data-preview-dialog.tsx",
  "src/app/\\(dashboard\\)/data/sources/\\[id\\]/_components/schema-table-detail.tsx",
  "src/app/\\(dashboard\\)/data/sources/\\[id\\]/_components/schema-tree.tsx",
  "src/app/\\(dashboard\\)/data/sources/\\[id\\]/_components/source-lineage-tab.tsx",
  "src/app/\\(dashboard\\)/data/sources/\\[id\\]/_components/source-overview-tab.tsx",
  "src/app/\\(dashboard\\)/data/sources/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/data/sources/_components/create-source-wizard.tsx",
  "src/app/\\(dashboard\\)/data/sources/_components/edit-source-dialog.tsx",
  "src/app/\\(dashboard\\)/data/sources/_components/wizard-step-schema.tsx",
  "src/app/\\(dashboard\\)/data/sources/_components/wizard-step-sync.tsx",
  "src/app/\\(dashboard\\)/data/sources/_components/wizard-step-test.tsx",
  "src/app/\\(dashboard\\)/dr/_components/activity/activity-feed.tsx",
  "src/app/\\(dashboard\\)/dr/_components/advisor/objective-fit-advisor.tsx",
  "src/app/\\(dashboard\\)/dr/_components/advisor/recovery-tier-catalog.tsx",
  "src/app/\\(dashboard\\)/dr/_components/console/dr-command-bar.tsx",
  "src/app/\\(dashboard\\)/dr/_components/console/dr-posture-banner.tsx",
  "src/app/\\(dashboard\\)/dr/_components/console/failover-wizard/failover-wizard.tsx",
  "src/app/\\(dashboard\\)/dr/_components/console/live-activity-chip.tsx",
  "src/app/\\(dashboard\\)/dr/_components/copilot/dr-copilot-launcher.test.tsx",
  "src/app/\\(dashboard\\)/dr/_components/copilot/dr-copilot-launcher.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-agent-enrollment.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-attestation-actions.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-copilot-commands.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-coverage-actions.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-coverage-selfdr.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-execution-actions.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-intelligence-plane.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-operational-panels.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-recovery-actions.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-recovery-workbench.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-replication-actions.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-resilience-actions.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-resilience-cockpit.tsx",
  "src/app/\\(dashboard\\)/dr/_components/dr-sovereign-actions.tsx",
  "src/app/\\(dashboard\\)/dr/_components/protect/protect-shared.tsx",
  "src/app/\\(dashboard\\)/dr/_components/protect/protection-groups.tsx",
  "src/app/\\(dashboard\\)/dr/_components/protect/replication-operations.tsx",
  "src/app/\\(dashboard\\)/dr/_components/provision/provision-inventory.tsx",
  "src/app/\\(dashboard\\)/dr/_components/readiness/sovereign-readiness.tsx",
  "src/app/\\(dashboard\\)/dr/_components/recover/consistency-point-card.tsx",
  "src/app/\\(dashboard\\)/dr/_components/recover/failover-operations.tsx",
  "src/app/\\(dashboard\\)/dr/approvals/_components/approval-item-card.tsx",
  "src/app/\\(dashboard\\)/dr/approvals/page.tsx",
  "src/app/\\(dashboard\\)/dr/insights/_components/insights-metric-strip.tsx",
  "src/app/\\(dashboard\\)/dr/insights/page.tsx",
  "src/app/\\(dashboard\\)/dr/integrations/_components/integration-health.ts",
  "src/app/\\(dashboard\\)/dr/integrations/_components/integrations-table.tsx",
  "src/app/\\(dashboard\\)/dr/page.tsx",
  "src/app/\\(dashboard\\)/dr/protect/page.tsx",
  "src/app/\\(dashboard\\)/dr/prove/_components/bcm-assessment-panel.tsx",
  "src/app/\\(dashboard\\)/dr/prove/_components/evidence-operations.tsx",
  "src/app/\\(dashboard\\)/dr/prove/_components/evidence/evidence-pack-dialog.tsx",
  "src/app/\\(dashboard\\)/dr/prove/_components/evidence/evidence-pack-print-view.tsx",
  "src/app/\\(dashboard\\)/dr/prove/_components/pir-review.tsx",
  "src/app/\\(dashboard\\)/dr/prove/compliance/_components/assurance-posture-panel.tsx",
  "src/app/\\(dashboard\\)/dr/prove/compliance/_components/compliance-rag.tsx",
  "src/app/\\(dashboard\\)/dr/prove/compliance/_components/framework-card.tsx",
  "src/app/\\(dashboard\\)/dr/prove/compliance/page.tsx",
  "src/app/\\(dashboard\\)/dr/prove/ledger/page.tsx",
  "src/app/\\(dashboard\\)/dr/prove/page.tsx",
  "src/app/\\(dashboard\\)/dr/readiness/page.tsx",
  "src/app/\\(dashboard\\)/dr/recover/page.tsx",
  "src/app/\\(dashboard\\)/dr/rehearse/_components/gameday/drill-diff-panel.tsx",
  "src/app/\\(dashboard\\)/dr/rehearse/_components/gameday/scorecard-panel.tsx",
  "src/app/\\(dashboard\\)/dr/runbooks/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/dr/runbooks/_components/act-on-task-panel.tsx",
  "src/app/\\(dashboard\\)/dr/runbooks/page.tsx",
  "src/app/\\(dashboard\\)/dr/runbooks/runs/\\[runId\\]/page.tsx",
  "src/app/\\(dashboard\\)/dr/runs/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/dr/topology/_components/boot-plan-panel.tsx",
  "src/app/\\(dashboard\\)/dr/topology/_components/boot-run-panel.tsx",
  "src/app/\\(dashboard\\)/dr/topology/_components/failover-target-panel.tsx",
  "src/app/\\(dashboard\\)/dr/topology/_components/topology-graph-panel.tsx",
  "src/app/\\(dashboard\\)/dr/topology/page.tsx",
  "src/app/\\(dashboard\\)/files/page.tsx",
  "src/app/\\(dashboard\\)/lex/_components/contract-analytics.tsx",
  "src/app/\\(dashboard\\)/lex/_components/governance-badge.tsx",
  "src/app/\\(dashboard\\)/lex/_components/needs-attention.tsx",
  "src/app/\\(dashboard\\)/lex/_guards/lex-route-guard.tsx",
  "src/app/\\(dashboard\\)/lex/admin/attachment-policies/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/classifications/_components/classification-appearance-picker.tsx",
  "src/app/\\(dashboard\\)/lex/admin/classifications/_components/classification-audit-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/classifications/_components/classification-tree-node.tsx",
  "src/app/\\(dashboard\\)/lex/admin/classifications/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/contract-approval-policies/_components/policy-audit-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/contract-approval-policies/_components/policy-versions-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/contract-approval-policies/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/contract-approval-policies/templates/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/escalations/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/\\[id\\]/logs/_components/reconciliation-panel.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/\\[id\\]/logs/_components/sync-runs-table.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/\\[id\\]/logs/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/activity-timeline.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/catalog-gallery.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/conflict-resolution-panel.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/connection-panel.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/connector-metrics-grid.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/custom-connector-builder.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/dlq-console.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/dynamic-connector-form.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/egress-policy-editor.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/endpoint-metrics-section.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/event-inspector.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/health-history-chart.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/health-kpi-strip.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/pending-changes-panel.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/setup-wizard.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/sync-run-ledger.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/_components/webhook-helper.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/observability/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/integrations/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/legal-holds/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/escalation-coverage/coverage-cell.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/escalation-coverage/escalation-coverage-matrix.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/escalation-whatif/escalation-whatif-simulator.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/localization-qa/localization-coverage-kpi.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/localization-qa/org-localization-qa.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/org-audit/org-audit-timeline.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/org-chart/org-chart-node.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/org-chart/org-chart-view.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/org-health/org-health-panel.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/people/responsibility-directory.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/platform-sync/platform-sync-view.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/reorganize/org-move-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/_components/reorganize/reparent-impact-preview.tsx",
  "src/app/\\(dashboard\\)/lex/admin/org-entities/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/request-approval-policies/_components/policy-audit-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/request-approval-policies/_components/policy-versions-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/request-approval-policies/templates/_components/template-form-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/request-approval-policies/templates/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/role-matrix/_components/role-matrix-grid.tsx",
  "src/app/\\(dashboard\\)/lex/admin/service-catalog/_components/service-detail-view.tsx",
  "src/app/\\(dashboard\\)/lex/admin/service-catalog/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/sla-targets/page.tsx",
  "src/app/\\(dashboard\\)/lex/admin/working-calendars/_components/calendar-holidays-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/admin/working-calendars/page.tsx",
  "src/app/\\(dashboard\\)/lex/analytics/_components/workload-heatmap.tsx",
  "src/app/\\(dashboard\\)/lex/analytics/page.tsx",
  "src/app/\\(dashboard\\)/lex/analytics/risk/page.tsx",
  "src/app/\\(dashboard\\)/lex/calendar/_components/calendar-filters.tsx",
  "src/app/\\(dashboard\\)/lex/calendar/_components/calendar-tokens.ts",
  "src/app/\\(dashboard\\)/lex/calendar/_components/legal-calendar.tsx",
  "src/app/\\(dashboard\\)/lex/case-timeline/_components/matter-summary-row.tsx",
  "src/app/\\(dashboard\\)/lex/case-timeline/page.tsx",
  "src/app/\\(dashboard\\)/lex/cases/\\[id\\]/_components/case-activity-mini.tsx",
  "src/app/\\(dashboard\\)/lex/cases/\\[id\\]/_components/case-hero.tsx",
  "src/app/\\(dashboard\\)/lex/cases/\\[id\\]/_components/case-people-card.tsx",
  "src/app/\\(dashboard\\)/lex/cases/\\[id\\]/_components/case-related-card.tsx",
  "src/app/\\(dashboard\\)/lex/cases/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/case-form-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/classification-picker.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/detail-workspace/case-command-header.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/detail-workspace/case-timeline-tab.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/detail-workspace/deadline-risk-strip.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/list-workspace/case-list-workspace.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/tabs/audit-tab.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/tabs/defendant-tab.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/tabs/documents-tab.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/tabs/experts-tab.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/tabs/judgments-tab.tsx",
  "src/app/\\(dashboard\\)/lex/cases/_components/tabs/pleadings-tab.tsx",
  "src/app/\\(dashboard\\)/lex/cases/classifications/page.tsx",
  "src/app/\\(dashboard\\)/lex/clause-library/_components/governance-queue-saved-views-pinned-clauses.tsx",
  "src/app/\\(dashboard\\)/lex/clause-library/page.tsx",
  "src/app/\\(dashboard\\)/lex/compliance/_components/alert-detail-panel.tsx",
  "src/app/\\(dashboard\\)/lex/compliance/alerts/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/compliance/page.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/\\[id\\]/_components/consultation-activity-mini.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultation-audit-timeline.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultation-dialogs.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultation-form-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultation-sla-meta.ts",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultation-sla-panel.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultations-board.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultations-columns.tsx",
  "src/app/\\(dashboard\\)/lex/consultations/_components/consultations-kpis.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/\\[id\\]/_components/clauses/clause-amendments.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/\\[id\\]/_components/clauses/clause-review-panel.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/\\[id\\]/_components/clauses/clauses-tab.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/contract-money-kpis.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/contract-playbook-cell.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/contract-preview-drawer.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/contract-signature-cell.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/contract-text-search.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/contracts-entity-rollup.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/contracts-expiry-cliff-chart.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/_components/obligations-command-center.tsx",
  "src/app/\\(dashboard\\)/lex/contracts/page.tsx",
  "src/app/\\(dashboard\\)/lex/documents/_components/bulk-import-csv-dialog.tsx",
  "src/app/\\(dashboard\\)/lex/documents/_components/document-preview-sheet.tsx",
  "src/app/\\(dashboard\\)/lex/documents/_components/document-quick-filters.tsx",
  "src/app/\\(dashboard\\)/lex/documents/_components/documents-board.tsx",
  "src/app/\\(dashboard\\)/lex/documents/_components/documents-view-states.tsx",
  "src/app/\\(dashboard\\)/lex/documents/_components/lex-editor-workspace.tsx",
  "src/app/\\(dashboard\\)/lex/documents/_components/repository-folder-tree.tsx",
  "src/app/\\(dashboard\\)/lex/documents/page.tsx",
  "src/app/\\(dashboard\\)/lex/drafting/_components/drafting-history-panel.tsx",
  "src/app/\\(dashboard\\)/lex/drafting/_components/drafting-workspace-cockpit.tsx",
  "src/app/\\(dashboard\\)/lex/drafting/_components/drafting-workspace-panels.tsx",
  "src/app/\\(dashboard\\)/lex/entities/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/entities/_components/entities-table.tsx",
  "src/app/\\(dashboard\\)/lex/entities/_components/entity-record-list.tsx",
  "src/app/\\(dashboard\\)/lex/inbox/page.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/\\[id\\]/_components/investigation-activity-mini.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/\\[id\\]/_components/investigation-overview-card.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/\\[id\\]/_components/investigation-related-card.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/_components/investigation-approval-operations-panel.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/_components/investigation-board-surface.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/_components/investigation-board.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/_components/investigation-timeline.tsx",
  "src/app/\\(dashboard\\)/lex/investigations/page.tsx",
  "src/app/\\(dashboard\\)/lex/library/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/library/_components/article-toc.tsx",
  "src/app/\\(dashboard\\)/lex/library/_components/ask-library-panel.tsx",
  "src/app/\\(dashboard\\)/lex/library/_components/library-contents-results.tsx",
  "src/app/\\(dashboard\\)/lex/library/_components/library-facet-tree.tsx",
  "src/app/\\(dashboard\\)/lex/library/_components/library-preview-sheet.tsx",
  "src/app/\\(dashboard\\)/lex/library/_components/pdf/pdfjs-viewer.tsx",
  "src/app/\\(dashboard\\)/lex/library/page.tsx",
  "src/app/\\(dashboard\\)/lex/matters/\\[id\\]/_components/matter-activity-mini.tsx",
  "src/app/\\(dashboard\\)/lex/matters/\\[id\\]/_components/matter-related-card.tsx",
  "src/app/\\(dashboard\\)/lex/matters/\\[id\\]/matter-detail.test.tsx",
  "src/app/\\(dashboard\\)/lex/matters/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/inline-edit-cells.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-activity-feed.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-analytics.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-documents-section.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-obligation-summary.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-preview-drawer.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-related-items.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-templates.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/matter-timeline.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/obligation-deadline-calendar.tsx",
  "src/app/\\(dashboard\\)/lex/matters/_components/obligation-manager.tsx",
  "src/app/\\(dashboard\\)/lex/matters/page.tsx",
  "src/app/\\(dashboard\\)/lex/notifications/_components/notification-preferences.tsx",
  "src/app/\\(dashboard\\)/lex/obligations/_components/obligations-board.tsx",
  "src/app/\\(dashboard\\)/lex/obligations/page.tsx",
  "src/app/\\(dashboard\\)/lex/playbooks/_components/deviation-meta.ts",
  "src/app/\\(dashboard\\)/lex/playbooks/_components/deviation-review.tsx",
  "src/app/\\(dashboard\\)/lex/playbooks/_components/playbook-catalog.tsx",
  "src/app/\\(dashboard\\)/lex/playbooks/_components/playbook-template-picker.tsx",
  "src/app/\\(dashboard\\)/lex/playbooks/_components/portfolio-row.tsx",
  "src/app/\\(dashboard\\)/lex/playbooks/portfolio/page.tsx",
  "src/app/\\(dashboard\\)/lex/regulations/_components/regulations-board.tsx",
  "src/app/\\(dashboard\\)/lex/regulations/page.tsx",
  "src/app/\\(dashboard\\)/lex/reports/_components/breakdown-card.tsx",
  "src/app/\\(dashboard\\)/lex/reports/_components/sla-compliance-panel.tsx",
  "src/app/\\(dashboard\\)/lex/reports/analytics/page.tsx",
  "src/app/\\(dashboard\\)/lex/reports/page.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/approval-panel.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/execution-panel.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/list-kpi-header.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/request-activity-mini.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/request-activity-timeline.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/request-board.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/request-people-card.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/request-related-card.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/_components/sla-panel.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/intake/page.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/new/_components/beneficiary-picker.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/new/_components/sla-promise-preview.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/new/_components/what-happens-next.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/new/page.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/notifications/page.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/page.tsx",
  "src/app/\\(dashboard\\)/lex/service-desk/sla-board/page.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/\\[id\\]/_components/settlement-activity-mini.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/\\[id\\]/_components/settlement-key-facts-card.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/\\[id\\]/_components/settlement-related-card.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/case-timeline-panel.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/deadlines-card.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/delay-breakdown.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/delay-category-meta.ts",
  "src/app/\\(dashboard\\)/lex/settlements/_components/delay-event-list.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/hold-history-card.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/settlement-analytics.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/settlement-approver-queue.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/settlement-audit-feed.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/settlement-board-surface.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/settlement-documents-section.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/settlement-stepper.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/settlement-workflow-status.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/timeline-overview.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/_components/timeline-track.tsx",
  "src/app/\\(dashboard\\)/lex/settlements/page.tsx",
  "src/app/\\(dashboard\\)/lex/signatures/_components/signature-risk-center.tsx",
  "src/app/\\(dashboard\\)/lex/signatures/page.tsx",
  "src/app/\\(dashboard\\)/lex/workflow-policies/page.tsx",
  "src/app/\\(dashboard\\)/migrate/_components/migrate-notification-rail.tsx",
  "src/app/\\(dashboard\\)/migrate/_components/migrate-workspace.tsx",
  "src/app/\\(dashboard\\)/notebooks/page.tsx",
  "src/app/\\(dashboard\\)/notifications/notifications-page-client.tsx",
  "src/app/\\(dashboard\\)/recover/_components/recover-analytics-dashboard.tsx",
  "src/app/\\(dashboard\\)/recover/_components/recover-onboarding-panel.tsx",
  "src/app/\\(dashboard\\)/recover/cloud-dr/_components/cloud-dr-dashboard.tsx",
  "src/app/\\(dashboard\\)/recover/cloud-dr/_components/region-failover-view.tsx",
  "src/app/\\(dashboard\\)/recover/cyber-recovery/_components/cyber-recovery-workspace.tsx",
  "src/app/\\(dashboard\\)/recover/cyber-recovery/_components/recovery-flow-panel.tsx",
  "src/app/\\(dashboard\\)/recover/it-dr/_components/it-dr-dashboard.tsx",
  "src/app/\\(dashboard\\)/recover/it-dr/prove/rehearsals/\\[kind\\]/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/recover/prove/_components/evidence-events-list.tsx",
  "src/app/\\(dashboard\\)/respond/_components/incident-command-panels.tsx",
  "src/app/\\(dashboard\\)/respond/incidents/\\[id\\]/page.tsx",
  "src/app/\\(dashboard\\)/respond/incidents/page.tsx",
  "src/app/\\(dashboard\\)/respond/page.tsx",
  "src/app/\\(dashboard\\)/respond/stakeholder/\\[token\\]/page.tsx",
  "src/app/\\(dashboard\\)/settings/_components/api-keys-section.tsx",
  "src/app/\\(dashboard\\)/settings/notifications/page.tsx",
  "src/app/\\(dashboard\\)/visus/alerts/page.tsx",
  "src/app/\\(dashboard\\)/visus/dashboards/\\[dashboardId\\]/_components/widget-preview-dialog.tsx",
  "src/app/\\(dashboard\\)/visus/dashboards/\\[dashboardId\\]/page.tsx",
  "src/app/\\(dashboard\\)/visus/kpis/page.tsx",
  "src/app/\\(dashboard\\)/visus/page.tsx",
  "src/app/\\(dashboard\\)/visus/reports/_components/report-snapshots-dialog.tsx",
  "src/app/\\(dashboard\\)/workflows/\\[id\\]/workflow-instance-page-client.tsx",
  "src/app/\\(dashboard\\)/workflows/definitions/definitions-browser-client.tsx",
  "src/app/\\(dashboard\\)/workflows/tasks/\\[id\\]/task-detail-page-client.tsx",
  "src/app/\\(dashboard\\)/workflows/tasks/tasks-page-client.tsx",
  "src/app/\\(dashboard\\)/workflows/workflows-page-client.tsx",
  "src/app/\\(dev\\)/ui-gallery/page.tsx",
  "src/app/\\(onboarding\\)/setup/_components/provisioning-progress.tsx",
  "src/app/\\(onboarding\\)/setup/_components/step-ready.tsx",
  "src/app/\\(onboarding\\)/setup/_components/step-suites.tsx",
  "src/app/\\(onboarding\\)/setup/_components/suite-selector-card.tsx",
  "src/app/design-system/_components/patterns-section.tsx",
  "src/app/global-error.tsx",
  "src/app/opengraph-image.tsx",
  "src/components/auth/bot-challenge.tsx",
  "src/components/auth/login-form.tsx",
  "src/components/auth/magic-link-form.tsx",
  "src/components/auth/mfa-setup-dialog.tsx",
  "src/components/auth/register-form.tsx",
  "src/components/auth/reset-password-form.tsx",
  "src/components/common/connection-status-banner.tsx",
  "src/components/common/page-loader.tsx",
  "src/components/cyber/cti/entity-link-dialog.tsx",
  "src/components/cyber/cti/kpi-stat-card.tsx",
  "src/components/cyber/cti/live-event-feed.tsx",
  "src/components/cyber/cti/mitre-technique-badges.tsx",
  "src/components/cyber/cti/sector-threat-chart.tsx",
  "src/components/cyber/cti/takedown-pipeline.tsx",
  "src/components/cyber/root-cause-analysis-panel.tsx",
  "src/components/dashboard/critical-alerts-banner.tsx",
  "src/components/dashboard/my-tasks-list.tsx",
  "src/components/dashboard/recent-alerts-table.tsx",
  "src/components/layout/command-palette.tsx",
  "src/components/layout/connection-banner.tsx",
  "src/components/layout/email-verification-reminder.tsx",
  "src/components/layout/header.tsx",
  "src/components/layout/locale-quick-toggle.tsx",
  "src/components/layout/mobile-quick-nav.tsx",
  "src/components/layout/mobile-sidebar.tsx",
  "src/components/layout/notification-dropdown.tsx",
  "src/components/layout/sidebar-nav-item.tsx",
  "src/components/layout/sidebar-section.tsx",
  "src/components/layout/sidebar-user-footer.tsx",
  "src/components/layout/sidebar.tsx",
  "src/components/layout/suite-switcher.tsx",
  "src/components/layout/tenant-switcher.tsx",
  "src/components/layout/theme-locale-switcher.tsx",
  "src/components/layout/theme-toggle.tsx",
  "src/components/layout/user-menu.tsx",
  "src/components/lex/access/lex-access-guard.tsx",
  "src/components/lex/kpi-strip.tsx",
  "src/components/lex/shell/global-search.tsx",
  "src/components/lex/shell/lex-sidebar.tsx",
  "src/components/lex/shell/recent-items.tsx",
  "src/components/marketing/clario360/clario360-shell.tsx",
  "src/components/marketing/clario360/site/app.tsx",
  "src/components/marketing/clario360/site/sovereignty.tsx",
  "src/components/marketing/clario360/site/widgets.tsx",
  "src/components/marketing/shell/marketing-footer.test.tsx",
  "src/components/marketing/shell/marketing-shell.test.tsx",
  "src/components/marketing/shell/marketing-shell.tsx",
  "src/components/marketing/shell/mobile-nav.test.tsx",
  "src/components/marketing/shell/mobile-nav.tsx",
  "src/components/notifications/notification-actions.tsx",
  "src/components/notifications/notification-list.tsx",
  "src/components/platform/impersonation-banner.tsx",
  "src/components/product/dashboard/multi-runbook-dashboard.tsx",
  "src/components/product/dashboard/recovery-dashboard.tsx",
  "src/components/product/dashboard/recovery-utils.ts",
  "src/components/product/dashboard/rpo-indicator.tsx",
  "src/components/product/dashboard/rto-vs-rta-tracker.tsx",
  "src/components/product/dashboard/runbook-progress-bar.tsx",
  "src/components/product/nodemap/node-map.tsx",
  "src/components/product/records/audit-trail-table.tsx",
  "src/components/product/records/integration-cards-grid.tsx",
  "src/components/product/records/post-implementation-review-panel.tsx",
  "src/components/product/runbook/runbook-task-flow.tsx",
  "src/components/shared/charts/chart-legend.tsx",
  "src/components/shared/detail-stat-card.tsx",
  "src/components/shared/document-viewer.tsx",
  "src/components/shared/event-calendar.tsx",
  "src/components/shared/forms/date-range-picker.tsx",
  "src/components/shared/forms/multi-select.tsx",
  "src/components/shared/forms/search-input.tsx",
  "src/components/shared/kpi-card.tsx",
  "src/components/shared/list-row.tsx",
  "src/components/shared/redline-view.tsx",
  "src/components/shared/saved-views-bar.tsx",
  "src/components/shared/simple-table.tsx",
  "src/components/suites/section-card.tsx",
  "src/components/visus/cti/cti-brand-abuse-widget.tsx",
  "src/components/visus/cti/cti-campaigns-widget.tsx",
  "src/components/workflows/workflow-instance-columns.tsx",
  "src/components/workflows/workflow-instance-detail.tsx",
  "src/components/workflows/workflow-step-timeline.tsx",
];

const config = [
  {
    ignores: [
      // Ignore every Next build output, including verification directories such
      // as .next-verify2/.next-verify3 created by production build checks.
      '.next*/**',
      '.next.prev.*',
      'coverage/**',
      'node_modules/**',
      'playwright-report/**',
      'test-results/**',
      'next-env.d.ts',
    ],
  },
  ...nextVitals,
  {
    rules: {
      'react-hooks/immutability': 'off',
      'react-hooks/incompatible-library': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/preserve-manual-memoization': 'off',
      'react-hooks/refs': 'off',
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/static-components': 'off',
    },
  },

  /* --- Design-system guardrails — RATCHETED to ERROR (F52) ---
   * Base: the two DS rules are ERROR across all of src/**. The ratchet
   * allowlist block below downgrades exactly today's offenders back to WARN,
   * so the pre-existing ~1,061 warnings keep the build green while any NEW
   * file that trips these rules hard-fails `eslint .`. Block order matters
   * (flat config: last matching block wins) — see each block's note. */
  {
    files: ['src/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': ['error', ...dsHexColorSelectors, ...dsRawElementSelectors],
      'no-restricted-imports': ['error', { paths: dsDeprecatedImportPaths }],
    },
  },
  // RATCHET: freeze existing violations at WARN. Runs BEFORE the primitives
  // block so an allowlisted primitive (e.g. simple-table) still has its raw
  // <table>/<button> re-exempted by that later block rather than warned here.
  {
    files: dsRatchetAllowlist,
    rules: {
      'no-restricted-syntax': ['warn', ...dsHexColorSelectors, ...dsRawElementSelectors],
      'no-restricted-imports': ['warn', { paths: dsDeprecatedImportPaths }],
    },
  },
  // The primitives themselves own the raw <table>/<button> elements — keep
  // only the hex-color guards inside them (ERROR: they must never regress to
  // hardcoded hex). Placed after the allowlist so raw elements stay exempt.
  {
    files: [
      'src/components/ui/**/*.{ts,tsx}',
      'src/components/shared/data-table/**/*.{ts,tsx}',
      'src/components/shared/simple-table.tsx',
    ],
    rules: {
      'no-restricted-syntax': ['error', ...dsHexColorSelectors],
    },
  },
  // Deprecated adapters may reference each other (dashboard/kpi-card is a
  // pure re-export of shared/kpi-card) — don't flag the adapters themselves.
  {
    files: ['src/components/dashboard/kpi-card.tsx'],
    rules: {
      'no-restricted-imports': 'off',
    },
  },
];

export default config;
