{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clario360.componentName" (dict "root" . "component" "frontend") }}
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "frontend") | nindent 4 }}
  {{- with ((.Values.frontend).service).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ dig "service" "type" "ClusterIP" .Values.frontend }}
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    {{- include "clario360.componentSelectorLabels" (dict "root" . "component" "frontend") | nindent 4 }}
{{- end }}
