{{- if .Values.workflowEngine.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clario360.componentName" (dict "root" . "component" "workflow-engine") }}
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "workflow-engine") | nindent 4 }}
  {{- with ((.Values.workflowEngine).service).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ dig "service" "type" "ClusterIP" .Values.workflowEngine }}
  ports:
    - name: http
      port: 8085
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9085
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "clario360.componentSelectorLabels" (dict "root" . "component" "workflow-engine") | nindent 4 }}
{{- end }}
