"use client";

import { useMemo } from "react";
import { useLocaleOrDefault } from "@/components/providers/locale-provider";
import type { AppLocale } from "@/lib/i18n";
import { type LexBilingual, resolveLexBilingual } from "../../_lib/lex-i18n";

export const INVESTIGATION_STATUS_OPTIONS = [
  "registered",
  "in_progress",
  "results_recorded",
  "pending_approval",
  "approved",
  "rejected",
  "closed",
  "cancelled",
] as const;

export const INVESTIGATION_PRIORITY_OPTIONS = [
  "critical",
  "high",
  "medium",
  "low",
] as const;

export const INVESTIGATION_PARTY_ROLE_OPTIONS = [
  "subject",
  "complainant",
  "witness",
  "investigator",
  "expert",
  "other",
] as const;

/** Snake/kebab token -> Title Case fallback when no localized label exists. */
export function formatInvestigationToken(token: string): string {
  return token
    .split(/[_-]/g)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export interface InvestigationLabels {
  pageTitle: string;
  pageDescription: string;
  eyebrow: string;
  create: string;
  createFirst: string;
  searchPlaceholder: string;
  emptyTitle: string;
  emptyDescription: string;
  loadError: string;
  view: {
    table: string;
    board: string;
  };
  clearLoadedView: string;
  searchHint: string;
  savedViews: {
    save: string;
    saved: string;
    empty: string;
  };
  stats: {
    total: string;
    inProgress: string;
    pendingApproval: string;
    approved: string;
    backendCounted: string;
    loadedFallback: string;
    loadedShown: (n: string) => string;
    loadedCount: (n: string) => string;
  };
  statDetails: {
    registerScope: string;
    visiblePortfolio: string;
    workloadShare: string;
    activeFactGathering: string;
    activeShare: string;
    approvalQueue: string;
    approvalShare: string;
    closedOrApproved: string;
    completionShare: string;
  };
  columns: {
    subject: string;
    number: string;
    status: string;
    priority: string;
    lead: string;
    updated: string;
  };
  filters: {
    status: string;
    priority: string;
    statusOptions: Record<string, string>;
    priorityOptions: Record<string, string>;
    roleOptions: Record<string, string>;
  };
  form: {
    createTitle: string;
    editTitle: string;
    createDescription: string;
    editDescription: string;
    caseStepTitle: string;
    caseStepDescription: string;
    assignmentStepTitle: string;
    assignmentStepDescription: string;
    readinessStepTitle: string;
    readinessStepDescription: string;
    caseId: string;
    caseIdPlaceholder: string;
    caseIdDescription: string;
    subject: string;
    subjectPlaceholder: string;
    subjectDescription: string;
    number: string;
    numberPlaceholder: string;
    lead: string;
    leadPlaceholder: string;
    leadDescription: string;
    priority: string;
    priorityDescription: string;
    department: string;
    departmentPlaceholder: string;
    readinessTitle: string;
    readinessParties: string;
    readinessEvidence: string;
    readinessApproval: string;
    readinessCase: string;
    readinessSubject: string;
    readinessLead: string;
    readinessPartiesCue: string;
    readinessEvidenceCue: string;
    readinessApprovalCue: string;
    readinessComplete: string;
    readinessIncomplete: string;
    cancel: string;
    create: string;
    save: string;
    errors: {
      subjectRequired: string;
      leadRequired: string;
    };
  };
  detail: {
    loadingTitle: string;
    loadingDescription: string;
    errorMessage: string;
    fallbackDescription: string;
    edit: string;
    delete: string;
    changeStatus: string;
    startApproval: string;
    metricStatus: string;
    metricPriority: string;
    metricParties: string;
    metricEvidence: string;
    overviewTitle: string;
    overviewDescription: string;
    metadata: {
      number: string;
      lead: string;
      department: string;
      linkedCase: string;
      aiDrafted: string;
      created: string;
      updated: string;
    };
    autoGenerated: string;
    notSet: string;
    none: string;
    yes: string;
    no: string;
    partiesTitle: string;
    partiesDescription: string;
    addParty: string;
    partiesEmptyTitle: string;
    partiesEmptyDescription: string;
    statementsTitle: string;
    statementsDescription: string;
    recordStatement: string;
    statementsEmptyTitle: string;
    statementsEmptyDescription: string;
    takenBy: (name: string) => string;
    evidenceTitle: string;
    evidenceDescription: string;
    uploadEvidence: string;
    evidenceEmptyTitle: string;
    evidenceEmptyDescription: string;
    collectedBy: (name: string) => string;
    resultsTitle: string;
    resultsDescription: string;
    recordResults: string;
    findingsLabel: string;
    findingsEmpty: string;
    recommendationsTitle: string;
    recommendationsDescription: string;
    recordRecommendations: string;
    recommendationsEmpty: string;
    aiBadge: string;
    approvalTitle: string;
    approvalDescription: string;
    approvalEmptyTitle: string;
    approvalEmptyDescription: string;
    approve: string;
    reject: string;
    auditTitle: string;
    auditDescription: string;
    auditEmptyTitle: string;
    auditEmptyDescription: string;
  };
  dialogs: {
    statusTitle: string;
    statusDescription: string;
    statusLabel: string;
    partyTitle: string;
    partyEditTitle: string;
    partyDescription: string;
    partyEditDescription: string;
    partyRole: string;
    partyName: string;
    partyNamePlaceholder: string;
    partyIdentifier: string;
    partyIdentifierPlaceholder: string;
    partyContact: string;
    partyContactPlaceholder: string;
    statementTitle: string;
    statementDescription: string;
    deponentName: string;
    deponentNamePlaceholder: string;
    statementBody: string;
    statementBodyPlaceholder: string;
    takenBy: string;
    takenByPlaceholder: string;
    takenAt: string;
    evidenceTitle: string;
    evidenceDescription: string;
    evidenceWorkspaceTitle: string;
    evidenceWorkspaceDescription: string;
    evidenceTitleField: string;
    evidenceTitlePlaceholder: string;
    evidenceTypeField: string;
    evidenceTypePlaceholder: string;
    evidenceTypeOptions: Record<string, string>;
    evidenceDescField: string;
    evidenceDescPlaceholder: string;
    collectedBy: string;
    collectedByPlaceholder: string;
    collectedAt: string;
    evidenceSource: string;
    evidenceSourceOptions: Record<string, string>;
    evidenceDocumentName: string;
    evidenceDocumentNamePlaceholder: string;
    evidencePreviewNote: string;
    evidencePreviewNotePlaceholder: string;
    evidencePickerHint: string;
    evidenceReuseHint: string;
    evidenceUploadTitle: string;
    evidenceUploadHint: string;
    evidenceUploadButton: string;
    evidenceUploading: (progress: number) => string;
    evidenceUploadFailed: string;
    evidenceFileTooLarge: string;
    evidenceRemoveUpload: string;
    fileId: string;
    fileIdPlaceholder: string;
    resultsTitle: string;
    resultsDescription: string;
    findings: string;
    findingsPlaceholder: string;
    generateAi: string;
    aiPrompt: string;
    aiPromptPlaceholder: string;
    aiBriefGuidance: string;
    aiPreviewGuidance: string;
    approvalReadinessLabel: string;
    approvalReadinessHint: string;
    regenerateDraft: string;
    acceptDraft: string;
    recommendationsTitle: string;
    recommendationsDescription: string;
    recommendations: string;
    recommendationsPlaceholder: string;
    approvalTitle: string;
    approvalDescription: string;
    approverRole: string;
    approverRolePlaceholder: string;
    notes: string;
    notesPlaceholder: string;
    decisionNotes: string;
    decisionNotesPlaceholder: string;
    submit: string;
    save: string;
    cancel: string;
    errors: {
      required: string;
    };
  };
  toast: {
    created: string;
    updated: string;
    deleted: string;
    statusUpdated: string;
    partyAdded: string;
    partyRemoved: string;
    statementRecorded: string;
    statementRemoved: string;
    evidenceUploaded: string;
    evidenceRemoved: string;
    resultsRecorded: string;
    recommendationsRecorded: string;
    approvalStarted: string;
    approvalDecided: string;
  };
  confirm: {
    deleteTitle: string;
    deleteDescription: (subject: string) => string;
    removePartyTitle: string;
    removePartyDescription: (name: string) => string;
    removeStatementTitle: string;
    removeStatementDescription: (name: string) => string;
    removeEvidenceTitle: string;
    removeEvidenceDescription: (title: string) => string;
    confirm: string;
  };
  /** List-page quick-filter presets (server-backed and loaded-rows). */
  quickFilters: {
    department: string;
    caseId: string;
    signalsHeader: string;
    signalCase: string;
    signalAi: string;
    noSignals: string;
    server: {
      portfolio: string;
      portfolioDescription: string;
      critical: string;
      criticalDescription: string;
      pendingApproval: string;
      pendingApprovalDescription: string;
      inProgress: string;
      inProgressDescription: string;
      resultsRecorded: string;
      resultsRecordedDescription: string;
    };
    loaded: {
      mine: string;
      mineDescription: string;
      missingEvidence: string;
      missingEvidenceDescription: string;
      noParties: string;
      noPartiesDescription: string;
      aiDrafted: string;
      aiDraftedDescription: string;
      linkedToCase: string;
      linkedToCaseDescription: string;
    };
  };
  /** Investigation command header (detail-page hero band). */
  commandHeader: {
    badge: string;
    approvalLabel: string;
    readinessLabel: string;
    checksValue: (done: number, total: number) => string;
    updatedPrefix: string;
    requiredWarning: string;
    readiness: {
      status: string;
      statusDoneHelper: string;
      statusTodoHelper: string;
      findings: string;
      findingsDoneHelper: string;
      findingsTodoHelper: string;
      recommendations: string;
      recommendationsDoneHelper: string;
      recommendationsTodoHelper: string;
      parties: string;
      partiesDoneHelper: (n: number) => string;
      partiesTodoHelper: string;
      statements: string;
      statementsDoneHelper: (n: number) => string;
      statementsTodoHelper: string;
      evidence: string;
      evidenceDoneHelper: (n: number) => string;
      evidenceTodoHelper: string;
    };
    actions: {
      decideApproval: string;
      reviewApproval: string;
      decideHelper: string;
      reviewHelper: string;
      resume: string;
      resumeHelper: string;
      addParty: string;
      addPartyHelper: string;
      recordStatement: string;
      recordStatementHelper: string;
      addEvidence: string;
      addEvidenceHelper: string;
      recordFindings: string;
      recordFindingsHelper: string;
      recordRecommendations: string;
      recordRecommendationsHelper: string;
      startApproval: string;
      startApprovalHelper: string;
      changeStatus: string;
      changeStatusHelper: string;
      viewTimeline: string;
      viewTimelineHelper: (date: string) => string;
    };
    state: {
      approved: string;
      rejected: string;
      pendingApproval: string;
      readyToRoute: string;
      notRouted: string;
      approvedMetric: string;
      rejectedMetric: string;
      pendingMetric: (n: number) => string;
      pendingApprovalMetric: string;
      readyMetric: string;
      notStartedMetric: string;
    };
  };
  /** Approval operations panel (detail page). */
  approvalOps: {
    title: string;
    description: string;
    loading: string;
    retry: string;
    resume: string;
    startApproval: string;
    metricApprovalState: string;
    metricReadiness: string;
    metricReadinessValue: (done: number, total: number) => string;
    metricWorkflow: string;
    readinessDoneHelper: string;
    readinessTodoHelper: string;
    workflowLinked: string;
    workflowNotStarted: string;
    workflowNoInstance: string;
    rejectedTitle: string;
    rejectedBody: string;
    reviewerNote: (note: string) => string;
    readyTitle: string;
    readyBody: string;
    readinessAttentionTitle: string;
    readinessAttentionBody: string;
    routingNotesTitle: string;
    loadIncomplete: string;
    tasksTitle: string;
    openCount: (n: number) => string;
    taskIdLabel: string;
    workflowLabel: string;
    assigneeRoleLabel: string;
    assigneeUserLabel: string;
    createdLabel: string;
    dueLabel: string;
    completedLabel: string;
    updatedLabel: string;
    priorityLabel: string;
    missing: string;
    notSet: string;
    notAssigned: string;
    taskNotesLabel: string;
    decisionNotesMetaLabel: string;
    decisionNotesLabel: string;
    decisionNotesPlaceholder: string;
    approve: string;
    reject: string;
    missingWorkflowWarning: string;
    readiness: {
      status: string;
      statusDoneHelper: string;
      statusTodoHelper: string;
      findings: string;
      findingsDoneHelper: string;
      findingsTodoHelper: string;
      recommendations: string;
      recommendationsDoneHelper: string;
      recommendationsTodoHelper: string;
      parties: string;
      partiesDoneHelper: (n: number) => string;
      partiesTodoHelper: string;
      statements: string;
      statementsDoneHelper: (n: number) => string;
      statementsTodoHelper: string;
      evidence: string;
      evidenceDoneHelper: (n: number) => string;
      evidenceTodoHelper: string;
    };
    state: {
      approved: string;
      rejected: string;
      openTasks: (n: number) => string;
      pendingApproval: string;
      readyToRoute: string;
      notStarted: string;
      approvedBadge: string;
      rejectedBadge: string;
      pendingBadge: string;
      readyBadge: string;
      notStartedBadge: string;
    };
    empty: {
      noOpenTitle: string;
      noActiveTitle: string;
      noReturnedTitle: string;
      notStartedTitle: string;
      rejectedDescription: string;
      pendingDescription: string;
      defaultDescription: string;
    };
  };
  /** Unified investigation timeline (detail page). */
  timeline: {
    title: string;
    description: string;
    loading: string;
    retryAudit: string;
    retryApprovals: string;
    partialError: string;
    emptyTitle: string;
    emptyDescription: string;
    registeredTitle: string;
    updatedTitle: string;
    partyAdded: (name: string) => string;
    statementRecorded: (name: string) => string;
    evidenceCatalogued: (title: string) => string;
    findingsRecorded: string;
    recommendationsRecorded: string;
    approvalOpened: (title: string) => string;
    approvalDue: (title: string) => string;
    auditPrefix: (action: string) => string;
    typePrefix: (type: string) => string;
    rolePrefix: (role: string) => string;
    assigneePrefix: (assignee: string) => string;
    actorPrefix: (actor: string) => string;
  };
  /** Investigation preview drawer (list page). */
  preview: {
    openRecord: string;
    updated: string;
    nextAction: string;
    latestKnownDate: string;
    loading: string;
    notAvailable: string;
    notSet: string;
    next: {
      beginFactGathering: string;
      collectEvidence: string;
      recordFindings: string;
      recordRecommendations: string;
      submitForApproval: string;
      awaitApprovalDecision: string;
      closeInvestigation: string;
      reviseFindings: string;
      closed: string;
      cancelled: string;
    };
  };
}

const bundle: LexBilingual<InvestigationLabels> = {
  en: {
    pageTitle: "Investigations Registry",
    pageDescription:
      "Legal investigations: parties, statements, evidence, findings and approval.",
    eyebrow: "Legal Suite",
    create: "New Investigation",
    createFirst: "Register your first investigation",
    searchPlaceholder: "Search investigations...",
    emptyTitle: "No investigations found",
    emptyDescription:
      "No legal investigations matched the current filters. Register a new investigation to start the chain of custody.",
    loadError: "Failed to load investigations.",
    view: {
      table: "Table",
      board: "Board",
    },
    clearLoadedView: "Clear loaded view",
    searchHint:
      "Search supports the investigation number, subject, lead investigator, department, linked case and backend-indexed investigation text. Loaded views apply to the rows currently in this table page.",
    savedViews: {
      save: "Save current investigation view",
      saved: "Saved investigation views",
      empty: "No saved investigation views yet",
    },
    stats: {
      total: "Total",
      inProgress: "In Progress",
      pendingApproval: "Pending Approval",
      approved: "Approved",
      backendCounted: "Across the register",
      loadedFallback: "From loaded rows",
      loadedShown: (n) => `${n} shown in loaded view`,
      loadedCount: (n) => `${n} on this page`,
    },
    statDetails: {
      registerScope:
        "Filtered investigation register across the current portfolio.",
      visiblePortfolio: "Visible portfolio",
      workloadShare: "Workload share",
      activeFactGathering: "Fact-gathering or results work still underway.",
      activeShare: "Active share",
      approvalQueue: "Findings waiting for reviewer decision.",
      approvalShare: "Approval queue",
      closedOrApproved: "Approved or closed investigations.",
      completionShare: "Completion share",
    },
    columns: {
      subject: "Subject",
      number: "Number",
      status: "Status",
      priority: "Priority",
      lead: "Lead Investigator",
      updated: "Updated",
    },
    filters: {
      status: "Status",
      priority: "Priority",
      statusOptions: {
        registered: "Registered",
        in_progress: "In Progress",
        results_recorded: "Results Recorded",
        pending_approval: "Pending Approval",
        approved: "Approved",
        rejected: "Rejected",
        closed: "Closed",
        cancelled: "Cancelled",
      },
      priorityOptions: {
        critical: "Critical",
        high: "High",
        medium: "Medium",
        low: "Low",
      },
      roleOptions: {
        subject: "Subject",
        complainant: "Complainant",
        witness: "Witness",
        investigator: "Investigator",
        expert: "Expert",
        other: "Other",
      },
    },
    form: {
      createTitle: "Create Investigation",
      editTitle: "Edit Investigation",
      createDescription:
        "Register a new legal investigation through a case-linked intake.",
      editDescription:
        "Update the investigation intake, ownership and readiness cues.",
      caseStepTitle: "Case-linked intake",
      caseStepDescription:
        "Anchor the investigation to a legal case and define the matter under review.",
      assignmentStepTitle: "Ownership and priority",
      assignmentStepDescription:
        "Assign the lead investigator, owning department and response priority.",
      readinessStepTitle: "Readiness checklist",
      readinessStepDescription:
        "Capture intake cues that help the detail workspace move into parties, evidence and approval.",
      caseId: "Linked case ID",
      caseIdPlaceholder: "Search legal cases",
      caseIdDescription:
        "Optional, but recommended when this investigation belongs to a case file.",
      subject: "Subject",
      subjectPlaceholder: "Alleged procurement irregularity",
      subjectDescription:
        "Use a concise matter title that can stand alone in the register.",
      number: "Investigation number",
      numberPlaceholder: "Auto-generated if empty",
      lead: "Lead investigator",
      leadPlaceholder: "Full name",
      leadDescription:
        "The accountable owner for intake, evidence and follow-up.",
      priority: "Priority",
      priorityDescription:
        "Sets triage urgency for the investigation register.",
      department: "Department",
      departmentPlaceholder: "e.g. Compliance",
      readinessTitle: "Approval readiness",
      readinessParties:
        "Known subjects, complainants, witnesses or experts have been identified.",
      readinessEvidence:
        "Likely evidence sources are known or a collection path is defined.",
      readinessApproval: "Approver route and sign-off expectations are clear.",
      readinessCase: "Case link present",
      readinessSubject: "Subject is clear",
      readinessLead: "Lead assigned",
      readinessPartiesCue: "Parties mapped",
      readinessEvidenceCue: "Evidence path mapped",
      readinessApprovalCue: "Approval route mapped",
      readinessComplete: "Ready to capture parties, evidence and findings.",
      readinessIncomplete:
        "Complete the remaining cues before routing findings for approval.",
      cancel: "Cancel",
      create: "Create investigation",
      save: "Save changes",
      errors: {
        subjectRequired: "Subject is required.",
        leadRequired: "Lead investigator is required.",
      },
    },
    detail: {
      loadingTitle: "Investigation",
      loadingDescription: "Loading investigation details.",
      errorMessage: "Failed to load investigation details.",
      fallbackDescription: "Legal investigation detail.",
      edit: "Edit",
      delete: "Delete",
      changeStatus: "Change status",
      startApproval: "Start approval",
      metricStatus: "Status",
      metricPriority: "Priority",
      metricParties: "Parties",
      metricEvidence: "Evidence",
      overviewTitle: "Investigation Overview",
      overviewDescription: "Core investigation state and context.",
      metadata: {
        number: "Investigation number",
        lead: "Lead investigator",
        department: "Department",
        linkedCase: "Linked case",
        aiDrafted: "AI-drafted body",
        created: "Created",
        updated: "Updated",
      },
      autoGenerated: "Auto-generated",
      notSet: "Not set",
      none: "None",
      yes: "Yes",
      no: "No",
      partiesTitle: "Parties",
      partiesDescription:
        "Subjects, complainants, witnesses and investigators.",
      addParty: "Add party",
      partiesEmptyTitle: "No parties",
      partiesEmptyDescription: "No participants have been registered yet.",
      statementsTitle: "Statements",
      statementsDescription: "Recorded testimony and statements.",
      recordStatement: "Record statement",
      statementsEmptyTitle: "No statements",
      statementsEmptyDescription: "No statements have been recorded yet.",
      takenBy: (name) => `Taken by ${name}`,
      evidenceTitle: "Evidence",
      evidenceDescription:
        "Catalogued evidence references and chain of custody.",
      uploadEvidence: "Add evidence",
      evidenceEmptyTitle: "No evidence",
      evidenceEmptyDescription: "No evidence has been catalogued yet.",
      collectedBy: (name) => `Collected by ${name}`,
      resultsTitle: "Findings",
      resultsDescription: "Recorded investigation findings.",
      recordResults: "Record findings",
      findingsLabel: "Findings",
      findingsEmpty: "No findings have been recorded yet.",
      recommendationsTitle: "Recommendations",
      recommendationsDescription:
        "Final recommendations from the investigation.",
      recordRecommendations: "Record recommendations",
      recommendationsEmpty: "No recommendations have been recorded yet.",
      aiBadge: "AI-drafted",
      approvalTitle: "Results Approval",
      approvalDescription: "Approval-chain tasks for the recorded results.",
      approvalEmptyTitle: "No approval tasks",
      approvalEmptyDescription:
        "Start the approval chain to route the findings for sign-off.",
      approve: "Approve",
      reject: "Reject",
      auditTitle: "Audit Trail",
      auditDescription: "Append-only governance log of every action.",
      auditEmptyTitle: "No audit entries",
      auditEmptyDescription: "No actions have been recorded yet.",
    },
    dialogs: {
      statusTitle: "Change investigation status",
      statusDescription:
        "Transition the investigation to a new lifecycle state.",
      statusLabel: "New status",
      partyTitle: "Add party",
      partyEditTitle: "Edit party",
      partyDescription: "Register a participant in the investigation.",
      partyEditDescription:
        "Update this participant while preserving the investigation history.",
      partyRole: "Role",
      partyName: "Name",
      partyNamePlaceholder: "Full name",
      partyIdentifier: "Identifier",
      partyIdentifierPlaceholder: "National ID / employee no. (encrypted)",
      partyContact: "Contact",
      partyContactPlaceholder: "Phone / email (encrypted)",
      statementTitle: "Record statement",
      statementDescription: "Capture a testimony or statement.",
      deponentName: "Deponent name",
      deponentNamePlaceholder: "Full name",
      statementBody: "Statement",
      statementBodyPlaceholder: "Verbatim statement text (encrypted)",
      takenBy: "Taken by",
      takenByPlaceholder: "Recorder name",
      takenAt: "Taken at",
      evidenceTitle: "Add evidence",
      evidenceDescription:
        "Catalogue an evidence reference with collection and file context.",
      evidenceWorkspaceTitle: "Evidence workspace",
      evidenceWorkspaceDescription:
        "Reuse an existing file reference or capture document metadata for later preview.",
      evidenceTitleField: "Title",
      evidenceTitlePlaceholder: "Email thread, CCTV clip...",
      evidenceTypeField: "Category",
      evidenceTypePlaceholder: "Select evidence category",
      evidenceTypeOptions: {
        document: "Document",
        email: "Email",
        image: "Image",
        video: "Video",
        audio: "Audio",
        statement: "Statement",
        system_log: "System log",
        financial_record: "Financial record",
        physical: "Physical item",
        other: "Other",
      },
      evidenceDescField: "Description",
      evidenceDescPlaceholder: "Brief description",
      collectedBy: "Collected by",
      collectedByPlaceholder: "Collector name",
      collectedAt: "Collected date",
      evidenceSource: "Source",
      evidenceSourceOptions: {
        direct_upload: "Uploaded proof",
        existing_file: "Existing file",
        case_document: "Case document",
        email_archive: "Email archive",
        interview: "Interview",
        system_export: "System export",
        physical_collection: "Physical collection",
        other: "Other",
      },
      evidenceDocumentName: "Document name",
      evidenceDocumentNamePlaceholder: "Original filename or document title",
      evidencePreviewNote: "Preview note",
      evidencePreviewNotePlaceholder:
        "What reviewers should expect when opening this reference",
      evidencePickerHint:
        "Search uploaded files, or leave this empty for a manual reference.",
      evidenceReuseHint:
        "File metadata is saved as evidence metadata; only supported fields are sent at the top level.",
      evidenceUploadTitle: "Upload proof file",
      evidenceUploadHint:
        "Upload a new document, image, recording, or export directly to this investigation (maximum 25 MB).",
      evidenceUploadButton: "Choose proof file",
      evidenceUploading: (progress) => `Uploading ${Math.round(progress)}%`,
      evidenceUploadFailed:
        "The proof file could not be uploaded. Please try again.",
      evidenceFileTooLarge: "The proof file exceeds the 25 MB limit.",
      evidenceRemoveUpload: "Remove uploaded proof",
      fileId: "Existing file",
      fileIdPlaceholder: "Select an existing file (optional)",
      resultsTitle: "Record findings",
      resultsDescription:
        "Draft, review and accept the investigation brief findings.",
      findings: "Findings",
      findingsPlaceholder: "Summary of findings (encrypted)",
      generateAi: "Generate or regenerate an AI brief",
      aiPrompt: "Brief instructions",
      aiPromptPlaceholder:
        "Summarize the allegation, evidence themes, disputed facts, risk posture and desired tone.",
      aiBriefGuidance:
        "Use brief-style instructions. The generated draft will return to the investigation for review before approval.",
      aiPreviewGuidance:
        "Review the generated text in the detail panel, then reopen this dialog to accept or revise it.",
      approvalReadinessLabel: "Mark this brief ready for approval routing",
      approvalReadinessHint:
        "Use only after findings, recommendations and evidence references are coherent enough for sign-off.",
      regenerateDraft: "Regenerate brief",
      acceptDraft: "Accept brief",
      recommendationsTitle: "Record recommendations",
      recommendationsDescription:
        "Draft, review and accept recommended actions.",
      recommendations: "Recommendations",
      recommendationsPlaceholder: "Recommended actions",
      approvalTitle: "Start results approval",
      approvalDescription: "Route the recorded results for sign-off.",
      approverRole: "Approver role",
      approverRolePlaceholder: "legal_director",
      notes: "Notes",
      notesPlaceholder: "Optional notes",
      decisionNotes: "Decision notes",
      decisionNotesPlaceholder: "Optional notes for the decision",
      submit: "Submit",
      save: "Save changes",
      cancel: "Cancel",
      errors: {
        required: "This field is required.",
      },
    },
    toast: {
      created: "Investigation created.",
      updated: "Investigation updated.",
      deleted: "Investigation deleted.",
      statusUpdated: "Status updated.",
      partyAdded: "Party added.",
      partyRemoved: "Party removed.",
      statementRecorded: "Statement recorded.",
      statementRemoved: "Statement removed.",
      evidenceUploaded: "Evidence added.",
      evidenceRemoved: "Evidence removed.",
      resultsRecorded: "Findings recorded.",
      recommendationsRecorded: "Recommendations recorded.",
      approvalStarted: "Approval chain started.",
      approvalDecided: "Decision applied.",
    },
    confirm: {
      deleteTitle: "Delete investigation",
      deleteDescription: (subject) =>
        `Delete "${subject}"? This removes it from the active register.`,
      removePartyTitle: "Remove party",
      removePartyDescription: (name) =>
        `Remove "${name}" from the investigation?`,
      removeStatementTitle: "Remove statement",
      removeStatementDescription: (name) =>
        `Remove the statement from "${name}"?`,
      removeEvidenceTitle: "Remove evidence",
      removeEvidenceDescription: (title) => `Remove evidence "${title}"?`,
      confirm: "Confirm",
    },
    quickFilters: {
      department: "Compliance",
      caseId: "Case ID",
      signalsHeader: "Signals",
      signalCase: "Case",
      signalAi: "AI",
      noSignals: "No signals",
      server: {
        portfolio: "Portfolio",
        portfolioDescription: "All investigations",
        critical: "Critical",
        criticalDescription: "Critical priority",
        pendingApproval: "Pending approval",
        pendingApprovalDescription: "Waiting for sign-off",
        inProgress: "In progress",
        inProgressDescription: "Active fact gathering",
        resultsRecorded: "Results recorded",
        resultsRecordedDescription: "Ready for recommendations or approval",
      },
      loaded: {
        mine: "My investigations",
        mineDescription: "Matches your account or lead name on this page",
        missingEvidence: "Missing evidence",
        missingEvidenceDescription: "Loaded investigations with no evidence",
        noParties: "No parties",
        noPartiesDescription: "Loaded investigations with no parties",
        aiDrafted: "AI drafted",
        aiDraftedDescription: "AI-assisted findings or recommendations",
        linkedToCase: "Linked to case",
        linkedToCaseDescription: "Has a case reference",
      },
    },
    commandHeader: {
      badge: "Investigation command",
      approvalLabel: "Approval",
      readinessLabel: "Readiness",
      checksValue: (done, total) => `${done}/${total} checks`,
      updatedPrefix: "Updated",
      requiredWarning:
        "Complete the required readiness checks before routing results for approval.",
      readiness: {
        status: "Results status",
        statusDoneHelper: "Results can be governed.",
        statusTodoHelper: "Move to results recorded.",
        findings: "Findings",
        findingsDoneHelper: "Findings are recorded.",
        findingsTodoHelper: "Record findings.",
        recommendations: "Recommendations",
        recommendationsDoneHelper: "Recommendations are recorded.",
        recommendationsTodoHelper: "Add recommended actions.",
        parties: "Parties",
        partiesDoneHelper: (n) => `${n} registered.`,
        partiesTodoHelper: "Add involved parties.",
        statements: "Statements",
        statementsDoneHelper: (n) => `${n} captured.`,
        statementsTodoHelper: "Record testimony as needed.",
        evidence: "Evidence",
        evidenceDoneHelper: (n) => `${n} catalogued.`,
        evidenceTodoHelper: "Catalogue evidence.",
      },
      actions: {
        decideApproval: "Decide approval",
        reviewApproval: "Review approval",
        decideHelper:
          "Open approval tasks are waiting for a reviewer decision.",
        reviewHelper: "Track approval task metadata and workflow state.",
        resume: "Resume investigation",
        resumeHelper:
          "Return the record to in progress before updating and resubmitting results.",
        addParty: "Add party",
        addPartyHelper:
          "Start by registering subjects, complainants, witnesses, or investigators.",
        recordStatement: "Record statement",
        recordStatementHelper:
          "Capture the first testimony or investigation statement.",
        addEvidence: "Add evidence",
        addEvidenceHelper: "Catalogue evidence references and custody details.",
        recordFindings: "Record findings",
        recordFindingsHelper:
          "Findings are required before results can be routed.",
        recordRecommendations: "Record recommendations",
        recordRecommendationsHelper:
          "Add the recommended actions before final sign-off.",
        startApproval: "Start approval",
        startApprovalHelper:
          "Route the recorded results to the configured approver role.",
        changeStatus: "Change status",
        changeStatusHelper: "Advance or close the investigation lifecycle.",
        viewTimeline: "View timeline",
        viewTimelineHelper: (date) => `Last updated ${date}.`,
      },
      state: {
        approved: "Approved",
        rejected: "Rejected",
        pendingApproval: "Pending approval",
        readyToRoute: "Ready to route",
        notRouted: "Not routed",
        approvedMetric: "Approved",
        rejectedMetric: "Rejected",
        pendingMetric: (n) => `${n} pending`,
        pendingApprovalMetric: "Pending approval",
        readyMetric: "Ready",
        notStartedMetric: "Not started",
      },
    },
    approvalOps: {
      title: "Approval Operations",
      description:
        "Readiness, workflow task metadata, reviewer notes, and decision actions for investigation results.",
      loading: "Loading approval tasks",
      retry: "Retry",
      resume: "Resume",
      startApproval: "Start approval",
      metricApprovalState: "Approval state",
      metricReadiness: "Readiness",
      metricReadinessValue: (done, total) => `${done}/${total} checks`,
      metricWorkflow: "Workflow",
      readinessDoneHelper: "Required checks are complete.",
      readinessTodoHelper: "Required checks need work.",
      workflowLinked: "Linked",
      workflowNotStarted: "Not started",
      workflowNoInstance: "Approval chain has not created a workflow instance.",
      rejectedTitle: "Approval rejected",
      rejectedBody:
        "Resume the investigation, update the findings or recommendations, then route the results again after the record returns to results recorded.",
      reviewerNote: (note) => `Reviewer note: ${note}`,
      readyTitle: "Ready to route",
      readyBody:
        "Required readiness checks are satisfied. Start approval when the reviewer role and routing notes are ready.",
      readinessAttentionTitle: "Readiness checks need attention",
      readinessAttentionBody:
        "Findings and results status are required before an approval chain can start.",
      routingNotesTitle: "Routing notes",
      loadIncomplete:
        "Approval task data did not load completely. Retry to refresh decision status and task metadata.",
      tasksTitle: "Approval tasks",
      openCount: (n) => `${n} open`,
      taskIdLabel: "Task ID",
      workflowLabel: "Workflow",
      assigneeRoleLabel: "Assignee role",
      assigneeUserLabel: "Assignee user",
      createdLabel: "Created",
      dueLabel: "Due",
      completedLabel: "Completed",
      updatedLabel: "Updated",
      priorityLabel: "Priority",
      missing: "Missing",
      notSet: "Not set",
      notAssigned: "Not assigned",
      taskNotesLabel: "Task notes",
      decisionNotesMetaLabel: "Decision notes",
      decisionNotesLabel: "Decision notes",
      decisionNotesPlaceholder:
        "Optional notes visible in the approval decision trail",
      approve: "Approve",
      reject: "Reject",
      missingWorkflowWarning:
        "This task is open, but the workflow instance reference is missing. Refresh approval tasks before deciding.",
      readiness: {
        status: "Results status",
        statusDoneHelper: "Record is eligible for approval governance.",
        statusTodoHelper: "Move to results recorded.",
        findings: "Findings",
        findingsDoneHelper: "Findings are available.",
        findingsTodoHelper: "Record findings first.",
        recommendations: "Recommendations",
        recommendationsDoneHelper: "Recommended actions are available.",
        recommendationsTodoHelper: "Recommended before final approval.",
        parties: "Parties",
        partiesDoneHelper: (n) => `${n} registered.`,
        partiesTodoHelper: "No parties registered.",
        statements: "Statements",
        statementsDoneHelper: (n) => `${n} recorded.`,
        statementsTodoHelper: "No statements recorded.",
        evidence: "Evidence",
        evidenceDoneHelper: (n) => `${n} catalogued.`,
        evidenceTodoHelper: "No evidence catalogued.",
      },
      state: {
        approved: "Approved",
        rejected: "Rejected",
        openTasks: (n) => `${n} open task${n === 1 ? "" : "s"}`,
        pendingApproval: "Pending approval",
        readyToRoute: "Ready to route",
        notStarted: "Not started",
        approvedBadge: "Approved",
        rejectedBadge: "Rejected",
        pendingBadge: "Pending",
        readyBadge: "Ready",
        notStartedBadge: "Not started",
      },
      empty: {
        noOpenTitle: "No open approval tasks",
        noActiveTitle: "No active approval task",
        noReturnedTitle: "No approval tasks returned",
        notStartedTitle: "Approval not started",
        rejectedDescription:
          "Resume the investigation and route the results again after updates are complete.",
        pendingDescription:
          "The workflow is pending approval, but no task metadata is currently available.",
        defaultDescription:
          "Start approval after required readiness checks are complete.",
      },
    },
    timeline: {
      title: "Unified Investigation Timeline",
      description:
        "Chronological view across audit events, parties, statements, evidence, findings, recommendations, and approval tasks.",
      loading: "Loading activity",
      retryAudit: "Retry audit",
      retryApprovals: "Retry approvals",
      partialError:
        "Timeline is showing the activity that loaded successfully. Retry any failed stream to fill gaps.",
      emptyTitle: "No timeline events",
      emptyDescription:
        "Activity will appear after the investigation record changes.",
      registeredTitle: "Investigation registered",
      updatedTitle: "Investigation updated",
      partyAdded: (name) => `Party added: ${name}`,
      statementRecorded: (name) => `Statement recorded: ${name}`,
      evidenceCatalogued: (title) => `Evidence catalogued: ${title}`,
      findingsRecorded: "Findings recorded",
      recommendationsRecorded: "Recommendations recorded",
      approvalOpened: (title) => `Approval task opened: ${title}`,
      approvalDue: (title) => `Approval task due: ${title}`,
      auditPrefix: (action) => `Audit: ${action}`,
      typePrefix: (type) => `Type: ${type}`,
      rolePrefix: (role) => `Role: ${role}`,
      assigneePrefix: (assignee) => `Assignee: ${assignee}`,
      actorPrefix: (actor) => `Actor: ${actor}`,
    },
    preview: {
      openRecord: "Open record",
      updated: "Updated",
      nextAction: "Next action",
      latestKnownDate: "Latest known date",
      loading: "Loading...",
      notAvailable: "Not available",
      notSet: "Not set",
      next: {
        beginFactGathering: "Begin fact gathering",
        collectEvidence: "Collect evidence",
        recordFindings: "Record findings",
        recordRecommendations: "Record recommendations",
        submitForApproval: "Submit for approval",
        awaitApprovalDecision: "Await approval decision",
        closeInvestigation: "Close investigation",
        reviseFindings: "Revise findings",
        closed: "Closed",
        cancelled: "Cancelled",
      },
    },
  },
  ar: {
    pageTitle: "سجل التحقيقات",
    pageDescription:
      "التحقيقات القانونية: الأطراف والإفادات والأدلة والنتائج والاعتماد.",
    eyebrow: "المجموعة القانونية",
    create: "تحقيق جديد",
    createFirst: "سجّل أول تحقيق لك",
    searchPlaceholder: "البحث في التحقيقات...",
    emptyTitle: "لا توجد تحقيقات",
    emptyDescription:
      "لا توجد تحقيقات مطابقة للمرشّحات الحالية. سجّل تحقيقًا جديدًا لبدء سلسلة الحيازة.",
    loadError: "تعذّر تحميل التحقيقات.",
    view: {
      table: "جدول",
      board: "لوحة",
    },
    clearLoadedView: "مسح العرض المحمّل",
    searchHint:
      "يدعم البحث رقم التحقيق والموضوع والمحقق المسؤول والإدارة والقضية المرتبطة والنص المفهرس في الخادم. تنطبق العروض المحمّلة على الصفوف الظاهرة في هذه الصفحة.",
    savedViews: {
      save: "حفظ عرض التحقيقات الحالي",
      saved: "عروض التحقيقات المحفوظة",
      empty: "لا توجد عروض تحقيقات محفوظة بعد",
    },
    stats: {
      total: "الإجمالي",
      inProgress: "قيد التنفيذ",
      pendingApproval: "بانتظار الاعتماد",
      approved: "معتمد",
      backendCounted: "عبر السجل",
      loadedFallback: "من الصفوف المحمّلة",
      loadedShown: (n) => `${n} ظاهرة في العرض المحمّل`,
      loadedCount: (n) => `${n} في هذه الصفحة`,
    },
    statDetails: {
      registerScope: "سجل التحقيقات المصفّى ضمن المحفظة الحالية.",
      visiblePortfolio: "المحفظة الظاهرة",
      workloadShare: "حصة عبء العمل",
      activeFactGathering: "جمع وقائع أو تسجيل نتائج ما زال قيد التنفيذ.",
      activeShare: "الحصة النشطة",
      approvalQueue: "نتائج بانتظار قرار المراجع.",
      approvalShare: "قائمة الاعتماد",
      closedOrApproved: "تحقيقات معتمدة أو مغلقة.",
      completionShare: "حصة الإنجاز",
    },
    columns: {
      subject: "الموضوع",
      number: "الرقم",
      status: "الحالة",
      priority: "الأولوية",
      lead: "المحقق المسؤول",
      updated: "آخر تحديث",
    },
    filters: {
      status: "الحالة",
      priority: "الأولوية",
      statusOptions: {
        registered: "مُسجَّل",
        in_progress: "قيد التنفيذ",
        results_recorded: "سُجّلت النتائج",
        pending_approval: "بانتظار الاعتماد",
        approved: "معتمد",
        rejected: "مرفوض",
        closed: "مغلق",
        cancelled: "ملغى",
      },
      priorityOptions: {
        critical: "حرج",
        high: "مرتفع",
        medium: "متوسط",
        low: "منخفض",
      },
      roleOptions: {
        subject: "المعني",
        complainant: "المُشتكي",
        witness: "شاهد",
        investigator: "محقق",
        expert: "خبير",
        other: "أخرى",
      },
    },
    form: {
      createTitle: "إنشاء تحقيق",
      editTitle: "تعديل التحقيق",
      createDescription: "تسجيل تحقيق قانوني جديد من خلال إدخال مرتبط بالقضية.",
      editDescription: "تحديث الإدخال والملكية ومؤشرات الجاهزية للتحقيق.",
      caseStepTitle: "إدخال مرتبط بالقضية",
      caseStepDescription:
        "ربط التحقيق بقضية قانونية وتحديد الموضوع محل المراجعة.",
      assignmentStepTitle: "الملكية والأولوية",
      assignmentStepDescription:
        "تعيين المحقق المسؤول والإدارة المالكة وأولوية الاستجابة.",
      readinessStepTitle: "قائمة الجاهزية",
      readinessStepDescription:
        "تسجيل مؤشرات تساعد مساحة التفاصيل على الانتقال إلى الأطراف والأدلة والاعتماد.",
      caseId: "معرّف القضية المرتبطة",
      caseIdPlaceholder: "معرّف القضية أو مرجعها",
      caseIdDescription: "اختياري، لكنه مفضّل عندما يرتبط التحقيق بملف قضية.",
      subject: "الموضوع",
      subjectPlaceholder: "مخالفة مزعومة في المشتريات",
      subjectDescription:
        "استخدم عنوانًا موجزًا يمكن فهمه مباشرة في سجل التحقيقات.",
      number: "رقم التحقيق",
      numberPlaceholder: "يُولَّد تلقائيًا إذا تُرك فارغًا",
      lead: "المحقق المسؤول",
      leadPlaceholder: "الاسم الكامل",
      leadDescription: "المالك المسؤول عن الإدخال والأدلة والمتابعة.",
      priority: "الأولوية",
      priorityDescription: "تحدد درجة الاستعجال في سجل التحقيقات.",
      department: "الإدارة",
      departmentPlaceholder: "مثال: الالتزام",
      readinessTitle: "جاهزية الاعتماد",
      readinessParties:
        "تم تحديد المعنيين أو المشتكين أو الشهود أو الخبراء المعروفين.",
      readinessEvidence: "مصادر الأدلة المحتملة معروفة أو تم تحديد مسار جمعها.",
      readinessApproval: "مسار المعتمد وتوقعات التوقيع واضحة.",
      readinessCase: "رابط القضية موجود",
      readinessSubject: "الموضوع واضح",
      readinessLead: "تم تعيين المسؤول",
      readinessPartiesCue: "تم حصر الأطراف",
      readinessEvidenceCue: "تم تحديد مسار الأدلة",
      readinessApprovalCue: "تم تحديد مسار الاعتماد",
      readinessComplete: "جاهز لتسجيل الأطراف والأدلة والنتائج.",
      readinessIncomplete: "أكمل المؤشرات المتبقية قبل توجيه النتائج للاعتماد.",
      cancel: "إلغاء",
      create: "إنشاء التحقيق",
      save: "حفظ التغييرات",
      errors: {
        subjectRequired: "الموضوع مطلوب.",
        leadRequired: "المحقق المسؤول مطلوب.",
      },
    },
    detail: {
      loadingTitle: "التحقيق",
      loadingDescription: "جارٍ تحميل تفاصيل التحقيق.",
      errorMessage: "تعذّر تحميل تفاصيل التحقيق.",
      fallbackDescription: "تفاصيل التحقيق القانوني.",
      edit: "تعديل",
      delete: "حذف",
      changeStatus: "تغيير الحالة",
      startApproval: "بدء الاعتماد",
      metricStatus: "الحالة",
      metricPriority: "الأولوية",
      metricParties: "الأطراف",
      metricEvidence: "الأدلة",
      overviewTitle: "نظرة عامة على التحقيق",
      overviewDescription: "الحالة الأساسية للتحقيق وسياقه.",
      metadata: {
        number: "رقم التحقيق",
        lead: "المحقق المسؤول",
        department: "الإدارة",
        linkedCase: "القضية المرتبطة",
        aiDrafted: "نص مُصاغ بالذكاء الاصطناعي",
        created: "تاريخ الإنشاء",
        updated: "آخر تحديث",
      },
      autoGenerated: "مُولَّد تلقائيًا",
      notSet: "غير محدد",
      none: "لا يوجد",
      yes: "نعم",
      no: "لا",
      partiesTitle: "الأطراف",
      partiesDescription: "المعنيون والمشتكون والشهود والمحققون.",
      addParty: "إضافة طرف",
      partiesEmptyTitle: "لا يوجد أطراف",
      partiesEmptyDescription: "لم يُسجَّل أي مشارك بعد.",
      statementsTitle: "الإفادات",
      statementsDescription: "الإفادات والشهادات المُسجَّلة.",
      recordStatement: "تسجيل إفادة",
      statementsEmptyTitle: "لا توجد إفادات",
      statementsEmptyDescription: "لم تُسجَّل أي إفادة بعد.",
      takenBy: (name) => `أخذها ${name}`,
      evidenceTitle: "الأدلة",
      evidenceDescription: "مراجع الأدلة المُفهرَسة وسلسلة الحيازة.",
      uploadEvidence: "إضافة دليل",
      evidenceEmptyTitle: "لا توجد أدلة",
      evidenceEmptyDescription: "لم تُفهرَس أي أدلة بعد.",
      collectedBy: (name) => `جمعها ${name}`,
      resultsTitle: "النتائج",
      resultsDescription: "نتائج التحقيق المُسجَّلة.",
      recordResults: "تسجيل النتائج",
      findingsLabel: "النتائج",
      findingsEmpty: "لم تُسجَّل أي نتائج بعد.",
      recommendationsTitle: "التوصيات",
      recommendationsDescription: "التوصيات النهائية للتحقيق.",
      recordRecommendations: "تسجيل التوصيات",
      recommendationsEmpty: "لم تُسجَّل أي توصيات بعد.",
      aiBadge: "مُصاغ بالذكاء الاصطناعي",
      approvalTitle: "اعتماد النتائج",
      approvalDescription: "مهام سلسلة الاعتماد للنتائج المُسجَّلة.",
      approvalEmptyTitle: "لا توجد مهام اعتماد",
      approvalEmptyDescription: "ابدأ سلسلة الاعتماد لتوجيه النتائج للاعتماد.",
      approve: "اعتماد",
      reject: "رفض",
      auditTitle: "سجل المراجعة",
      auditDescription: "سجل حوكمة غير قابل للتعديل لكل إجراء.",
      auditEmptyTitle: "لا توجد قيود مراجعة",
      auditEmptyDescription: "لم تُسجَّل أي إجراءات بعد.",
    },
    dialogs: {
      statusTitle: "تغيير حالة التحقيق",
      statusDescription: "نقل التحقيق إلى حالة جديدة في دورة الحياة.",
      statusLabel: "الحالة الجديدة",
      partyTitle: "إضافة طرف",
      partyEditTitle: "تعديل الطرف",
      partyDescription: "تسجيل مشارك في التحقيق.",
      partyEditDescription:
        "تحديث بيانات هذا المشارك مع الحفاظ على سجل التحقيق.",
      partyRole: "الدور",
      partyName: "الاسم",
      partyNamePlaceholder: "الاسم الكامل",
      partyIdentifier: "المعرّف",
      partyIdentifierPlaceholder: "الهوية الوطنية / الرقم الوظيفي (مشفّر)",
      partyContact: "بيانات الاتصال",
      partyContactPlaceholder: "هاتف / بريد إلكتروني (مشفّر)",
      statementTitle: "تسجيل إفادة",
      statementDescription: "تدوين شهادة أو إفادة.",
      deponentName: "اسم المُدلي",
      deponentNamePlaceholder: "الاسم الكامل",
      statementBody: "الإفادة",
      statementBodyPlaceholder: "نص الإفادة الحرفي (مشفّر)",
      takenBy: "دوّنها",
      takenByPlaceholder: "اسم المُدوّن",
      takenAt: "تاريخ التدوين",
      evidenceTitle: "إضافة دليل",
      evidenceDescription: "فهرسة مرجع دليل مع سياق الجمع والملف.",
      evidenceWorkspaceTitle: "مساحة الأدلة",
      evidenceWorkspaceDescription:
        "أعد استخدام مرجع ملف موجود أو سجل بيانات المستند للمعاينة لاحقًا.",
      evidenceTitleField: "العنوان",
      evidenceTitlePlaceholder: "سلسلة بريد، مقطع كاميرا مراقبة...",
      evidenceTypeField: "الفئة",
      evidenceTypePlaceholder: "اختر فئة الدليل",
      evidenceTypeOptions: {
        document: "مستند",
        email: "بريد إلكتروني",
        image: "صورة",
        video: "فيديو",
        audio: "صوت",
        statement: "إفادة",
        system_log: "سجل نظام",
        financial_record: "سجل مالي",
        physical: "عنصر مادي",
        other: "أخرى",
      },
      evidenceDescField: "الوصف",
      evidenceDescPlaceholder: "وصف موجز",
      collectedBy: "جمعها",
      collectedByPlaceholder: "اسم الجامع",
      collectedAt: "تاريخ الجمع",
      evidenceSource: "المصدر",
      evidenceSourceOptions: {
        direct_upload: "إثبات مرفوع",
        existing_file: "ملف موجود",
        case_document: "مستند قضية",
        email_archive: "أرشيف بريد",
        interview: "مقابلة",
        system_export: "تصدير نظام",
        physical_collection: "جمع مادي",
        other: "أخرى",
      },
      evidenceDocumentName: "اسم المستند",
      evidenceDocumentNamePlaceholder: "اسم الملف الأصلي أو عنوان المستند",
      evidencePreviewNote: "ملاحظة المعاينة",
      evidencePreviewNotePlaceholder:
        "ما الذي يجب أن يتوقعه المراجع عند فتح هذا المرجع",
      evidencePickerHint:
        "ابحث في الملفات المرفوعة، أو اترك الحقل فارغًا كمرجع يدوي.",
      evidenceReuseHint:
        "تُحفظ بيانات الملف ضمن بيانات الدليل الوصفية؛ وترسل الحقول المدعومة فقط في المستوى الرئيسي.",
      evidenceUploadTitle: "رفع ملف الإثبات",
      evidenceUploadHint:
        "ارفع مستندًا أو صورة أو تسجيلًا أو ملف تصدير جديدًا مباشرة إلى هذا التحقيق (بحد أقصى 25 م.ب).",
      evidenceUploadButton: "اختيار ملف الإثبات",
      evidenceUploading: (progress) => `جارٍ الرفع ${Math.round(progress)}٪`,
      evidenceUploadFailed: "تعذّر رفع ملف الإثبات. يرجى المحاولة مرة أخرى.",
      evidenceFileTooLarge: "يتجاوز ملف الإثبات الحد الأقصى البالغ 25 م.ب.",
      evidenceRemoveUpload: "إزالة الإثبات المرفوع",
      fileId: "ملف موجود",
      fileIdPlaceholder: "اختر ملفًا موجودًا (اختياري)",
      resultsTitle: "تسجيل النتائج",
      resultsDescription: "صياغة نتائج موجز التحقيق ومراجعتها واعتمادها.",
      findings: "النتائج",
      findingsPlaceholder: "ملخّص النتائج (مشفّر)",
      generateAi: "إنشاء أو إعادة إنشاء موجز بالذكاء الاصطناعي",
      aiPrompt: "تعليمات الموجز",
      aiPromptPlaceholder:
        "لخّص الادعاء ومحاور الأدلة والوقائع محل الخلاف ومستوى المخاطر والنبرة المطلوبة.",
      aiBriefGuidance:
        "استخدم تعليمات بأسلوب الموجز. سيعود النص المولّد إلى التحقيق للمراجعة قبل الاعتماد.",
      aiPreviewGuidance:
        "راجع النص المولّد في لوحة التفاصيل، ثم أعد فتح هذا الحوار لقبوله أو تعديله.",
      approvalReadinessLabel: "تمييز هذا الموجز كجاهز لمسار الاعتماد",
      approvalReadinessHint:
        "استخدمها فقط بعد أن تكون النتائج والتوصيات ومراجع الأدلة متماسكة بما يكفي للتوقيع.",
      regenerateDraft: "إعادة إنشاء الموجز",
      acceptDraft: "اعتماد الموجز",
      recommendationsTitle: "تسجيل التوصيات",
      recommendationsDescription:
        "صياغة الإجراءات الموصى بها ومراجعتها واعتمادها.",
      recommendations: "التوصيات",
      recommendationsPlaceholder: "الإجراءات الموصى بها",
      approvalTitle: "بدء اعتماد النتائج",
      approvalDescription: "توجيه النتائج المُسجَّلة للاعتماد.",
      approverRole: "دور المعتمِد",
      approverRolePlaceholder: "legal_director",
      notes: "ملاحظات",
      notesPlaceholder: "ملاحظات اختيارية",
      decisionNotes: "ملاحظات القرار",
      decisionNotesPlaceholder: "ملاحظات اختيارية للقرار",
      submit: "إرسال",
      save: "حفظ التغييرات",
      cancel: "إلغاء",
      errors: {
        required: "هذا الحقل مطلوب.",
      },
    },
    toast: {
      created: "تم إنشاء التحقيق.",
      updated: "تم تحديث التحقيق.",
      deleted: "تم حذف التحقيق.",
      statusUpdated: "تم تحديث الحالة.",
      partyAdded: "تمت إضافة الطرف.",
      partyRemoved: "تمت إزالة الطرف.",
      statementRecorded: "تم تسجيل الإفادة.",
      statementRemoved: "تمت إزالة الإفادة.",
      evidenceUploaded: "تمت إضافة الدليل.",
      evidenceRemoved: "تمت إزالة الدليل.",
      resultsRecorded: "تم تسجيل النتائج.",
      recommendationsRecorded: "تم تسجيل التوصيات.",
      approvalStarted: "بدأت سلسلة الاعتماد.",
      approvalDecided: "تم تطبيق القرار.",
    },
    confirm: {
      deleteTitle: "حذف التحقيق",
      deleteDescription: (subject) =>
        `حذف "${subject}"؟ سيؤدي ذلك إلى إزالته من السجل النشط.`,
      removePartyTitle: "إزالة الطرف",
      removePartyDescription: (name) => `إزالة "${name}" من التحقيق؟`,
      removeStatementTitle: "إزالة الإفادة",
      removeStatementDescription: (name) => `إزالة إفادة "${name}"؟`,
      removeEvidenceTitle: "إزالة الدليل",
      removeEvidenceDescription: (title) => `إزالة الدليل "${title}"؟`,
      confirm: "تأكيد",
    },
    quickFilters: {
      department: "الالتزام",
      caseId: "معرّف القضية",
      signalsHeader: "المؤشرات",
      signalCase: "قضية",
      signalAi: "ذكاء اصطناعي",
      noSignals: "لا توجد مؤشرات",
      server: {
        portfolio: "المحفظة",
        portfolioDescription: "جميع التحقيقات",
        critical: "حرجة",
        criticalDescription: "أولوية حرجة",
        pendingApproval: "بانتظار الاعتماد",
        pendingApprovalDescription: "بانتظار التوقيع",
        inProgress: "قيد التنفيذ",
        inProgressDescription: "تقصٍّ نشط للوقائع",
        resultsRecorded: "سُجّلت النتائج",
        resultsRecordedDescription: "جاهزة للتوصيات أو الاعتماد",
      },
      loaded: {
        mine: "تحقيقاتي",
        mineDescription: "تطابق حسابك أو اسم المسؤول في هذه الصفحة",
        missingEvidence: "بلا أدلة",
        missingEvidenceDescription: "التحقيقات المحمّلة بلا أدلة",
        noParties: "بلا أطراف",
        noPartiesDescription: "التحقيقات المحمّلة بلا أطراف",
        aiDrafted: "مُصاغة بالذكاء الاصطناعي",
        aiDraftedDescription: "نتائج أو توصيات بمساعدة الذكاء الاصطناعي",
        linkedToCase: "مرتبطة بقضية",
        linkedToCaseDescription: "لها مرجع قضية",
      },
    },
    commandHeader: {
      badge: "مركز قيادة التحقيق",
      approvalLabel: "الاعتماد",
      readinessLabel: "الجاهزية",
      checksValue: (done, total) => `${done}/${total} فحوصات`,
      updatedPrefix: "آخر تحديث",
      requiredWarning:
        "أكمل فحوصات الجاهزية المطلوبة قبل توجيه النتائج للاعتماد.",
      readiness: {
        status: "حالة النتائج",
        statusDoneHelper: "يمكن حوكمة النتائج.",
        statusTodoHelper: "انتقل إلى حالة سُجّلت النتائج.",
        findings: "النتائج",
        findingsDoneHelper: "تم تسجيل النتائج.",
        findingsTodoHelper: "سجّل النتائج.",
        recommendations: "التوصيات",
        recommendationsDoneHelper: "تم تسجيل التوصيات.",
        recommendationsTodoHelper: "أضف الإجراءات الموصى بها.",
        parties: "الأطراف",
        partiesDoneHelper: (n) => `${n} مُسجَّلة.`,
        partiesTodoHelper: "أضف الأطراف المعنية.",
        statements: "الإفادات",
        statementsDoneHelper: (n) => `${n} مُدوَّنة.`,
        statementsTodoHelper: "سجّل الإفادات حسب الحاجة.",
        evidence: "الأدلة",
        evidenceDoneHelper: (n) => `${n} مُفهرَسة.`,
        evidenceTodoHelper: "افهرس الأدلة.",
      },
      actions: {
        decideApproval: "البتّ في الاعتماد",
        reviewApproval: "مراجعة الاعتماد",
        decideHelper: "مهام اعتماد مفتوحة بانتظار قرار المراجع.",
        reviewHelper: "تتبّع بيانات مهام الاعتماد وحالة سير العمل.",
        resume: "استئناف التحقيق",
        resumeHelper:
          "أعد السجل إلى قيد التنفيذ قبل تحديث النتائج وإعادة تقديمها.",
        addParty: "إضافة طرف",
        addPartyHelper:
          "ابدأ بتسجيل المعنيين أو المشتكين أو الشهود أو المحققين.",
        recordStatement: "تسجيل إفادة",
        recordStatementHelper: "دوّن أول شهادة أو إفادة في التحقيق.",
        addEvidence: "إضافة دليل",
        addEvidenceHelper: "افهرس مراجع الأدلة وتفاصيل الحيازة.",
        recordFindings: "تسجيل النتائج",
        recordFindingsHelper: "النتائج مطلوبة قبل إمكان توجيه النتائج.",
        recordRecommendations: "تسجيل التوصيات",
        recordRecommendationsHelper:
          "أضف الإجراءات الموصى بها قبل التوقيع النهائي.",
        startApproval: "بدء الاعتماد",
        startApprovalHelper:
          "وجّه النتائج المُسجَّلة إلى دور المعتمِد المُهيّأ.",
        changeStatus: "تغيير الحالة",
        changeStatusHelper: "تقدّم بدورة حياة التحقيق أو أغلقها.",
        viewTimeline: "عرض المخطط الزمني",
        viewTimelineHelper: (date) => `آخر تحديث ${date}.`,
      },
      state: {
        approved: "معتمد",
        rejected: "مرفوض",
        pendingApproval: "بانتظار الاعتماد",
        readyToRoute: "جاهز للتوجيه",
        notRouted: "غير مُوجَّه",
        approvedMetric: "معتمد",
        rejectedMetric: "مرفوض",
        pendingMetric: (n) => `${n} قيد الانتظار`,
        pendingApprovalMetric: "بانتظار الاعتماد",
        readyMetric: "جاهز",
        notStartedMetric: "لم يبدأ",
      },
    },
    approvalOps: {
      title: "عمليات الاعتماد",
      description:
        "الجاهزية وبيانات مهام سير العمل وملاحظات المراجع وإجراءات القرار لنتائج التحقيق.",
      loading: "جارٍ تحميل مهام الاعتماد",
      retry: "إعادة المحاولة",
      resume: "استئناف",
      startApproval: "بدء الاعتماد",
      metricApprovalState: "حالة الاعتماد",
      metricReadiness: "الجاهزية",
      metricReadinessValue: (done, total) => `${done}/${total} فحوصات`,
      metricWorkflow: "سير العمل",
      readinessDoneHelper: "الفحوصات المطلوبة مكتملة.",
      readinessTodoHelper: "الفحوصات المطلوبة تحتاج إلى عمل.",
      workflowLinked: "مرتبط",
      workflowNotStarted: "لم يبدأ",
      workflowNoInstance: "لم تنشئ سلسلة الاعتماد نسخة سير عمل.",
      rejectedTitle: "رُفض الاعتماد",
      rejectedBody:
        "استأنف التحقيق وحدّث النتائج أو التوصيات، ثم وجّه النتائج مرة أخرى بعد عودة السجل إلى حالة سُجّلت النتائج.",
      reviewerNote: (note) => `ملاحظة المراجع: ${note}`,
      readyTitle: "جاهز للتوجيه",
      readyBody:
        "فحوصات الجاهزية المطلوبة مُستوفاة. ابدأ الاعتماد عندما يكون دور المراجع وملاحظات التوجيه جاهزة.",
      readinessAttentionTitle: "فحوصات الجاهزية تحتاج إلى انتباه",
      readinessAttentionBody:
        "النتائج وحالة النتائج مطلوبة قبل إمكان بدء سلسلة الاعتماد.",
      routingNotesTitle: "ملاحظات التوجيه",
      loadIncomplete:
        "لم تُحمَّل بيانات مهام الاعتماد بالكامل. أعد المحاولة لتحديث حالة القرار وبيانات المهام.",
      tasksTitle: "مهام الاعتماد",
      openCount: (n) => `${n} مفتوحة`,
      taskIdLabel: "معرّف المهمة",
      workflowLabel: "سير العمل",
      assigneeRoleLabel: "دور المُسنَد إليه",
      assigneeUserLabel: "المستخدم المُسنَد إليه",
      createdLabel: "تاريخ الإنشاء",
      dueLabel: "تاريخ الاستحقاق",
      completedLabel: "تاريخ الإكمال",
      updatedLabel: "آخر تحديث",
      priorityLabel: "الأولوية",
      missing: "مفقود",
      notSet: "غير محدد",
      notAssigned: "غير مُسنَد",
      taskNotesLabel: "ملاحظات المهمة",
      decisionNotesMetaLabel: "ملاحظات القرار",
      decisionNotesLabel: "ملاحظات القرار",
      decisionNotesPlaceholder: "ملاحظات اختيارية تظهر في سجل قرار الاعتماد",
      approve: "اعتماد",
      reject: "رفض",
      missingWorkflowWarning:
        "هذه المهمة مفتوحة، لكن مرجع نسخة سير العمل مفقود. حدّث مهام الاعتماد قبل البتّ.",
      readiness: {
        status: "حالة النتائج",
        statusDoneHelper: "السجل مؤهّل لحوكمة الاعتماد.",
        statusTodoHelper: "انتقل إلى حالة سُجّلت النتائج.",
        findings: "النتائج",
        findingsDoneHelper: "النتائج متوفرة.",
        findingsTodoHelper: "سجّل النتائج أولًا.",
        recommendations: "التوصيات",
        recommendationsDoneHelper: "الإجراءات الموصى بها متوفرة.",
        recommendationsTodoHelper: "يُوصى بها قبل الاعتماد النهائي.",
        parties: "الأطراف",
        partiesDoneHelper: (n) => `${n} مُسجَّلة.`,
        partiesTodoHelper: "لا توجد أطراف مُسجَّلة.",
        statements: "الإفادات",
        statementsDoneHelper: (n) => `${n} مُسجَّلة.`,
        statementsTodoHelper: "لا توجد إفادات مُسجَّلة.",
        evidence: "الأدلة",
        evidenceDoneHelper: (n) => `${n} مُفهرَسة.`,
        evidenceTodoHelper: "لا توجد أدلة مُفهرَسة.",
      },
      state: {
        approved: "معتمد",
        rejected: "مرفوض",
        openTasks: (n) => `${n} مهمة مفتوحة`,
        pendingApproval: "بانتظار الاعتماد",
        readyToRoute: "جاهز للتوجيه",
        notStarted: "لم يبدأ",
        approvedBadge: "معتمد",
        rejectedBadge: "مرفوض",
        pendingBadge: "قيد الانتظار",
        readyBadge: "جاهز",
        notStartedBadge: "لم يبدأ",
      },
      empty: {
        noOpenTitle: "لا توجد مهام اعتماد مفتوحة",
        noActiveTitle: "لا توجد مهمة اعتماد نشطة",
        noReturnedTitle: "لم تُرجَع أي مهام اعتماد",
        notStartedTitle: "لم يبدأ الاعتماد",
        rejectedDescription:
          "استأنف التحقيق ووجّه النتائج مرة أخرى بعد اكتمال التحديثات.",
        pendingDescription:
          "سير العمل بانتظار الاعتماد، لكن لا تتوفر بيانات مهام حاليًا.",
        defaultDescription:
          "ابدأ الاعتماد بعد اكتمال فحوصات الجاهزية المطلوبة.",
      },
    },
    timeline: {
      title: "المخطط الزمني الموحّد للتحقيق",
      description:
        "عرض زمني عبر أحداث المراجعة والأطراف والإفادات والأدلة والنتائج والتوصيات ومهام الاعتماد.",
      loading: "جارٍ تحميل النشاط",
      retryAudit: "إعادة محاولة المراجعة",
      retryApprovals: "إعادة محاولة الاعتمادات",
      partialError:
        "يعرض المخطط الزمني النشاط الذي تم تحميله بنجاح. أعد محاولة أي مصدر فشل لسدّ الفجوات.",
      emptyTitle: "لا توجد أحداث في المخطط الزمني",
      emptyDescription: "سيظهر النشاط بعد تغيّر سجل التحقيق.",
      registeredTitle: "تم تسجيل التحقيق",
      updatedTitle: "تم تحديث التحقيق",
      partyAdded: (name) => `أُضيف طرف: ${name}`,
      statementRecorded: (name) => `سُجّلت إفادة: ${name}`,
      evidenceCatalogued: (title) => `فُهرس دليل: ${title}`,
      findingsRecorded: "تم تسجيل النتائج",
      recommendationsRecorded: "تم تسجيل التوصيات",
      approvalOpened: (title) => `فُتحت مهمة اعتماد: ${title}`,
      approvalDue: (title) => `استحقاق مهمة اعتماد: ${title}`,
      auditPrefix: (action) => `مراجعة: ${action}`,
      typePrefix: (type) => `النوع: ${type}`,
      rolePrefix: (role) => `الدور: ${role}`,
      assigneePrefix: (assignee) => `المُسنَد إليه: ${assignee}`,
      actorPrefix: (actor) => `المنفِّذ: ${actor}`,
    },
    preview: {
      openRecord: "فتح السجل",
      updated: "آخر تحديث",
      nextAction: "الإجراء التالي",
      latestKnownDate: "آخر تاريخ معروف",
      loading: "جارٍ التحميل...",
      notAvailable: "غير متوفر",
      notSet: "غير محدد",
      next: {
        beginFactGathering: "بدء تقصّي الوقائع",
        collectEvidence: "جمع الأدلة",
        recordFindings: "تسجيل النتائج",
        recordRecommendations: "تسجيل التوصيات",
        submitForApproval: "تقديم للاعتماد",
        awaitApprovalDecision: "انتظار قرار الاعتماد",
        closeInvestigation: "إغلاق التحقيق",
        reviseFindings: "مراجعة النتائج",
        closed: "مغلق",
        cancelled: "ملغى",
      },
    },
  },
};

export function resolveInvestigationLabels(
  locale: AppLocale = "en",
): InvestigationLabels {
  return resolveLexBilingual(bundle, locale);
}

export function useInvestigationLabels(): InvestigationLabels {
  const { locale } = useLocaleOrDefault();
  return useMemo(() => resolveInvestigationLabels(locale), [locale]);
}
