'use client';

import { useLocaleOrDefault } from '@/components/providers/locale-provider';

const EN = {
  aiBrief: {
    title: 'AI case brief',
    description: 'Deterministic draft',
    posture: 'Posture',
    facts: 'Key facts',
    risks: 'Risk signals',
    nextSteps: 'Next steps',
    refresh: 'Refresh',
    noRisks: 'No immediate risk signals found.',
    noNextSteps: 'No immediate workflow action found.',
    notAssessed: 'Not assessed',
    brief: {
      summary: (title: string, companyStatus: string, status: string, priority: string) =>
        `${title} is a ${companyStatus} matter currently marked ${status} with ${priority} priority.`,
      workspaceCounts: (parties: number, hearings: number, tasks: number, audits: number) =>
        `${parties} parties, ${hearings} hearings, ${tasks} active tasks, and ${audits} audit events are available in this workspace.`,
      competentCourt: (court: string) => `Competent court: ${court}.`,
      responsibleLawyer: (lawyer: string) => `Responsible lawyer: ${lawyer}.`,
      matterSummary: (summary: string) => `Matter summary: ${summary}`,
      latestHearing: (date: string, decision: string) =>
        `Latest hearing was ${date}${decision ? ` with decision: ${decision}` : ''}.`,
      filings: (filed: number, total: number, experts: number, judgments: number) =>
        `${filed}/${total} pleadings filed, ${experts} experts assigned, and ${judgments} judgments recorded.`,
      criticalDeadlines: (count: number) =>
        `${count} deadline item${count === 1 ? '' : 's'} due within two days or overdue.`,
      highDeadlines: (count: number) => `${count} deadline item${count === 1 ? '' : 's'} due within seven days.`,
      casePriority: (priority: string) => `Case priority is ${priority}.`,
      strengthNotAssessed: 'Case strength has not been assessed.',
      strengthWeak: 'Case strength is currently weak.',
      noResponsibleLawyer: 'No responsible lawyer is set.',
      pendingJudgments: (count: number) =>
        `${count} judgment${count === 1 ? '' : 's'} still need study recommendation.`,
      reviewDeadline: (title: string, date: string) => `Review ${title} by ${date}.`,
      assignLawyer: 'Assign a responsible lawyer or owner.',
      completeStrength: 'Complete the strength assessment.',
      createTask: 'Create the next procedural task for the matter team.',
      confirmHearing: 'Confirm whether the next hearing date should be recorded.',
    },
  },
  collaboration: {
    title: 'Collaboration',
    description: 'Case notes',
    placeholder: 'Add a note. Use @mentions for people, teams, or departments.',
    add: 'Add note',
    clear: 'Delete',
    emptyTitle: 'No case notes yet',
    emptyDescription: 'Notes stay in this browser until server collaboration is connected.',
    you: 'You',
    mentions: 'Mentions',
    unread: 'Unread',
    mentionsMetric: 'Mentions',
    mentionedYou: 'Mentioned you',
    localFallback: 'Local fallback',
    serverNotes: 'Server notes',
    markAllRead: 'Mark all read',
    ownNote: 'Own note',
    unreadBadge: 'Unread',
    readLocally: 'Read locally',
    mentionsYou: 'Mentions you',
    taskCreated: 'Task created',
    convertToTask: 'Convert to task',
    markRead: 'Mark read',
    taskCreatedToast: 'Task created from note',
    collaborationNote: 'Collaboration note',
    followUp: (text: string) => `Follow up: ${text}`,
  },
  command: {
    title: 'Case command',
    status: 'Status',
    priority: 'Priority',
    strength: 'Strength',
    owner: 'Owner / lawyer',
    nextCriticalDate: 'Next critical date',
    unassigned: 'Unassigned',
    notSet: 'Not set',
    noneScheduled: 'None scheduled',
    reviewDeadline: 'Review deadline',
    openIntake: 'Open intake',
    setStrength: 'Set strength',
    updateStatus: 'Update status',
    viewTimeline: 'View timeline',
    nextBestActions: 'Next-best actions',
    pendingActions: (count: number) => `${count} open`,
    completeIntake: 'Complete intake',
    assignOwner: 'Assign owner',
    recordHearing: 'Record hearing',
    recordTask: 'Record task',
    recordDocument: 'Record document',
    needed: 'Needed',
    done: 'Done',
    watch: 'Watch',
    open: 'Open',
    writeRequired: 'Write access required',
    intakeRequired: 'Intake is still the active status.',
    intakeComplete: 'Intake gate is cleared.',
    ownerMissing: 'No responsible lawyer is assigned.',
    ownerReady: 'Owner is assigned.',
    strengthMissing: 'Strength has not been assessed.',
    strengthReady: 'Strength is recorded.',
    deadlineDue: (label: string) => `Next: ${label}`,
    noDeadline: 'No active deadline to review.',
    hearingMissing: 'No hearing is on the calendar.',
    hearingTracked: (count: number) => `${count} hearing${count === 1 ? '' : 's'} tracked.`,
    taskMissing: 'No task is tracked.',
    taskTracked: (count: number) => `${count} task${count === 1 ? '' : 's'} tracked.`,
    documentReady: 'Open the live document workspace.',
  },
  deadline: {
    title: 'Deadline risk',
    allClear: 'No active deadlines are inside the risk window.',
    activeSummary: (count: number) => `${count} active deadline${count === 1 ? '' : 's'} tracked.`,
    critical: 'Critical',
    high: 'High',
    medium: 'Watch',
    low: 'Tracked',
    overdue: 'overdue',
    dueToday: 'due today',
    dueIn: (days: number) => `due in ${days}d`,
    viewTimeline: 'Timeline',
    empty: 'No dated tasks, hearings, expert reports, or objection deadlines yet.',
    owner: 'Owner',
    department: 'Department',
    lastUpdate: 'Last update',
    strength: 'Strength',
    unassignedWarning: 'No owner or department assigned.',
    missingStrength: 'Strength is not set.',
    weakCase: 'Weak merits signal.',
    staleUpdate: (days: number) => `No case update for ${days}d.`,
    escalationHint: 'Escalate ownership before the next critical date.',
    moreDeadlines: (count: number) => `+${count} more`,
    countsByType: 'Deadline mix',
  },
  timeline: {
    title: 'Case timeline',
    description: 'Metadata, deadlines, hearings, tasks, audit, and plaintiff workflow events.',
    loading: 'Syncing workflow events',
    partialError: 'Some workflow events could not be loaded.',
    retry: 'Retry',
    emptyTitle: 'No timeline events yet',
    emptyDescription: 'Case activity will appear here as teams add tasks, hearings, pleadings, experts, and judgments.',
    upcoming: 'Upcoming',
    history: 'History',
    metadata: 'Metadata',
    milestone: 'Milestone',
    addMilestone: 'Add milestone',
    hearing: 'Hearing',
    task: 'Task',
    audit: 'Audit',
    pleading: 'Pleading',
    expert: 'Expert',
    judgment: 'Judgment',
    defendant: 'Defendant',
    filters: 'Filters',
    typeFilter: 'Event type',
    windowFilter: 'Time window',
    allTypes: 'All events',
    allDates: 'All dates',
    upcomingOnly: 'Upcoming',
    pastOnly: 'Past',
    next30: 'Next 30d',
    next90: 'Next 90d',
    showing: (shown: number, total: number) => `${shown}/${total} shown`,
    counts: 'Counts',
    print: 'Print',
    exportPdf: 'Export full timeline (PDF)',
    by: (name: string) => `by ${name}`,
    exportCsv: 'Export CSV',
    emptyFilteredTitle: 'No matching events',
    emptyFilteredDescription: 'Adjust the type or time window filters.',
    created: 'Case created',
    updated: 'Case updated',
    plaintiffTrack: 'Plaintiff track',
    noPleadings: 'No pleadings recorded yet',
    noExperts: 'No expert assignments recorded yet',
    noJudgments: 'No judgments recorded yet',
  },
};

const AR: typeof EN = {
  aiBrief: {
    title: 'ملخص القضية بالذكاء الاصطناعي',
    description: 'مسودة حتمية',
    posture: 'الموقف',
    facts: 'الوقائع الرئيسية',
    risks: 'مؤشرات المخاطر',
    nextSteps: 'الخطوات التالية',
    refresh: 'تحديث',
    noRisks: 'لا توجد مؤشرات مخاطر فورية.',
    noNextSteps: 'لا يوجد إجراء سير عمل فوري.',
    notAssessed: 'لم تُقيَّم',
    brief: {
      summary: (title, companyStatus, status, priority) =>
        `${title} مسألة بصفة ${companyStatus} مُعلَّمة حاليًا بحالة ${status} وأولوية ${priority}.`,
      workspaceCounts: (parties, hearings, tasks, audits) =>
        `تتوفر ${parties} أطراف و${hearings} جلسات و${tasks} مهام نشطة و${audits} حدث تدقيق في مساحة العمل هذه.`,
      competentCourt: (court) => `المحكمة المختصة: ${court}.`,
      responsibleLawyer: (lawyer) => `المحامي المسؤول: ${lawyer}.`,
      matterSummary: (summary) => `ملخص المسألة: ${summary}`,
      latestHearing: (date, decision) =>
        `كانت آخر جلسة في ${date}${decision ? ` بقرار: ${decision}` : ''}.`,
      filings: (filed, total, experts, judgments) =>
        `أُودعت ${filed}/${total} مذكرات، وعُيِّن ${experts} خبراء، وسُجِّل ${judgments} حكمًا.`,
      criticalDeadlines: (count) => `${count} بند موعد مستحق خلال يومين أو متأخر.`,
      highDeadlines: (count) => `${count} بند موعد مستحق خلال سبعة أيام.`,
      casePriority: (priority) => `أولوية القضية ${priority}.`,
      strengthNotAssessed: 'لم تُقيَّم قوة القضية.',
      strengthWeak: 'قوة القضية ضعيفة حاليًا.',
      noResponsibleLawyer: 'لم يُحدَّد محامٍ مسؤول.',
      pendingJudgments: (count) => `${count} حكم لا يزال يحتاج إلى توصية دراسة.`,
      reviewDeadline: (title, date) => `راجع ${title} بحلول ${date}.`,
      assignLawyer: 'أسند محاميًا مسؤولًا أو مالكًا.',
      completeStrength: 'أكمل تقييم القوة.',
      createTask: 'أنشئ المهمة الإجرائية التالية لفريق المسألة.',
      confirmHearing: 'أكّد ما إذا كان ينبغي تسجيل تاريخ الجلسة القادمة.',
    },
  },
  collaboration: {
    title: 'التعاون',
    description: 'ملاحظات القضية',
    placeholder: 'أضف ملاحظة. استخدم @ للإشارة إلى أشخاص أو فرق أو إدارات.',
    add: 'إضافة ملاحظة',
    clear: 'حذف',
    emptyTitle: 'لا توجد ملاحظات بعد',
    emptyDescription: 'تبقى الملاحظات في هذا المتصفح إلى حين ربط التعاون بالخادم.',
    you: 'أنت',
    mentions: 'الإشارات',
    unread: 'غير مقروءة',
    mentionsMetric: 'الإشارات',
    mentionedYou: 'أشارت إليك',
    localFallback: 'بديل محلي',
    serverNotes: 'ملاحظات الخادم',
    markAllRead: 'تعليم الكل كمقروء',
    ownNote: 'ملاحظتك',
    unreadBadge: 'غير مقروءة',
    readLocally: 'مقروءة محليًا',
    mentionsYou: 'تشير إليك',
    taskCreated: 'أُنشئت المهمة',
    convertToTask: 'تحويل إلى مهمة',
    markRead: 'تعليم كمقروء',
    taskCreatedToast: 'أُنشئت مهمة من الملاحظة',
    collaborationNote: 'ملاحظة تعاون',
    followUp: (text) => `متابعة: ${text}`,
  },
  command: {
    title: 'مركز قيادة القضية',
    status: 'الحالة',
    priority: 'الأولوية',
    strength: 'القوة',
    owner: 'المالك / المحامي',
    nextCriticalDate: 'أقرب تاريخ حرج',
    unassigned: 'غير مسند',
    notSet: 'غير محدد',
    noneScheduled: 'لا يوجد موعد',
    reviewDeadline: 'مراجعة الموعد',
    openIntake: 'فتح الاستلام',
    setStrength: 'تحديد القوة',
    updateStatus: 'تحديث الحالة',
    viewTimeline: 'عرض الجدول',
    nextBestActions: 'أفضل الإجراءات التالية',
    pendingActions: (count: number) => `${count} مفتوح`,
    completeIntake: 'إكمال الاستلام',
    assignOwner: 'إسناد المالك',
    recordHearing: 'تسجيل جلسة',
    recordTask: 'تسجيل مهمة',
    recordDocument: 'تسجيل مستند',
    needed: 'مطلوب',
    done: 'منجز',
    watch: 'متابعة',
    open: 'مفتوح',
    writeRequired: 'صلاحية الكتابة مطلوبة',
    intakeRequired: 'لا تزال حالة الاستلام نشطة.',
    intakeComplete: 'تم تجاوز بوابة الاستلام.',
    ownerMissing: 'لا يوجد محام مسؤول مسند.',
    ownerReady: 'تم إسناد المالك.',
    strengthMissing: 'لم يتم تقييم القوة.',
    strengthReady: 'تم تسجيل القوة.',
    deadlineDue: (label: string) => `التالي: ${label}`,
    noDeadline: 'لا يوجد موعد نشط للمراجعة.',
    hearingMissing: 'لا توجد جلسة في التقويم.',
    hearingTracked: (count: number) => `توجد ${count} جلسة تحت المتابعة.`,
    taskMissing: 'لا توجد مهمة تحت المتابعة.',
    taskTracked: (count: number) => `توجد ${count} مهمة تحت المتابعة.`,
    documentReady: 'افتح مساحة المستندات المباشرة.',
  },
  deadline: {
    title: 'مخاطر المواعيد',
    allClear: 'لا توجد مواعيد نشطة داخل نطاق المخاطر.',
    activeSummary: (count: number) => `توجد ${count} مواعيد نشطة تحت المتابعة.`,
    critical: 'حرج',
    high: 'مرتفع',
    medium: 'متابعة',
    low: 'تحت المتابعة',
    overdue: 'متأخر',
    dueToday: 'مستحق اليوم',
    dueIn: (days: number) => `مستحق خلال ${days} يوم`,
    viewTimeline: 'الجدول',
    empty: 'لا توجد مهام أو جلسات أو تقارير خبرة أو مواعيد اعتراض مؤرخة بعد.',
    owner: 'المالك',
    department: 'الإدارة',
    lastUpdate: 'آخر تحديث',
    strength: 'القوة',
    unassignedWarning: 'لا يوجد مالك أو إدارة مسندة.',
    missingStrength: 'لم يتم تحديد القوة.',
    weakCase: 'مؤشر ضعف في جوهر القضية.',
    staleUpdate: (days: number) => `لا يوجد تحديث للقضية منذ ${days} يوم.`,
    escalationHint: 'صعّد الملكية قبل أقرب تاريخ حرج.',
    moreDeadlines: (count: number) => `+${count} إضافية`,
    countsByType: 'مزيج المواعيد',
  },
  timeline: {
    title: 'الجدول الزمني للقضية',
    description: 'البيانات الأساسية والمواعيد والجلسات والمهام والتدقيق ومسار المدعي.',
    loading: 'تحديث أحداث سير العمل',
    partialError: 'تعذر تحميل بعض أحداث سير العمل.',
    retry: 'إعادة المحاولة',
    emptyTitle: 'لا توجد أحداث بعد',
    emptyDescription: 'ستظهر أنشطة القضية عند إضافة المهام والجلسات والمذكرات والخبراء والأحكام.',
    upcoming: 'قادمة',
    history: 'السابقة',
    metadata: 'البيانات',
    milestone: 'محطة رئيسية',
    addMilestone: 'إضافة محطة',
    hearing: 'جلسة',
    task: 'مهمة',
    audit: 'تدقيق',
    pleading: 'مذكرة',
    expert: 'خبير',
    judgment: 'حكم',
    defendant: 'مدعى عليه',
    filters: 'التصفية',
    typeFilter: 'نوع الحدث',
    windowFilter: 'النطاق الزمني',
    allTypes: 'كل الأحداث',
    allDates: 'كل التواريخ',
    upcomingOnly: 'قادمة',
    pastOnly: 'سابقة',
    next30: '٣٠ يوم',
    next90: '٩٠ يوم',
    showing: (shown: number, total: number) => `معروض ${shown}/${total}`,
    counts: 'الأعداد',
    print: 'طباعة',
    exportPdf: 'تصدير المسار الزمني الكامل (PDF)',
    by: (name: string) => `بواسطة ${name}`,
    exportCsv: 'تصدير CSV',
    emptyFilteredTitle: 'لا توجد أحداث مطابقة',
    emptyFilteredDescription: 'عدّل نوع الحدث أو النطاق الزمني.',
    created: 'إنشاء القضية',
    updated: 'تحديث القضية',
    plaintiffTrack: 'مسار المدعي',
    noPleadings: 'لا توجد مذكرات مسجلة بعد',
    noExperts: 'لا توجد تكليفات خبراء مسجلة بعد',
    noJudgments: 'لا توجد أحكام مسجلة بعد',
  },
};

export function useDetailWorkspaceLabels() {
  const { locale } = useLocaleOrDefault();
  return locale === 'ar' ? AR : EN;
}
