import type {
  AnalyticsQuery,
  Contradiction,
  ContradictionScan,
  ContradictionStats,
  DarkDataAsset,
  DarkDataScan,
  DarkDataStatsSummary,
  DataModel,
  DataSource,
  DataSuiteDashboard,
  DiscoveredSchema,
  LineageGraph,
  Pipeline,
  PipelineRun,
  QualityResult,
  QualityRule,
  QualityScore,
  QueryResult,
  SavedQuery,
} from '@/lib/data-suite';

export const sourceSchema: DiscoveredSchema = {
  tables: [
    {
      schema_name: 'public',
      name: 'customers',
      type: 'table',
      comment: 'Customer master',
      columns: [
        {
          name: 'id',
          data_type: 'integer',
          native_type: 'integer',
          mapped_type: 'integer',
          nullable: false,
          is_primary_key: true,
          is_foreign_key: false,
          sample_values: ['1', '2', '3'],
          inferred_pii: false,
          inferred_classification: 'internal',
        },
        {
          name: 'email',
          data_type: 'string',
          native_type: 'varchar(255)',
          mapped_type: 'string',
          nullable: false,
          is_primary_key: false,
          is_foreign_key: false,
          sample_values: ['john@example.com', 'jane@example.com', 'sam@example.com'],
          inferred_pii: true,
          inferred_pii_type: 'email',
          inferred_classification: 'confidential',
        },
        {
          name: 'first_name',
          data_type: 'string',
          native_type: 'varchar(255)',
          mapped_type: 'string',
          nullable: true,
          is_primary_key: false,
          is_foreign_key: false,
          sample_values: ['John', 'Jane', 'Sam'],
          inferred_pii: true,
          inferred_pii_type: 'name',
          inferred_classification: 'confidential',
        },
        {
          name: 'status',
          data_type: 'string',
          native_type: 'varchar(20)',
          mapped_type: 'string',
          nullable: false,
          is_primary_key: false,
          is_foreign_key: false,
          sample_values: ['A', 'I', 'A'],
          inferred_pii: false,
          inferred_classification: 'internal',
        },
        {
          name: 'updated_at',
          data_type: 'datetime',
          native_type: 'timestamptz',
          mapped_type: 'datetime',
          nullable: false,
          is_primary_key: false,
          is_foreign_key: false,
          sample_values: ['2026-03-01T10:00:00Z', '2026-03-02T11:00:00Z', '2026-03-03T09:30:00Z'],
          inferred_pii: false,
          inferred_classification: 'internal',
        },
      ],
      primary_keys: ['id'],
      foreign_keys: [],
      estimated_rows: 245000,
      size_bytes: 1536000,
      inferred_classification: 'confidential',
      contains_pii: true,
      pii_column_count: 2,
      nullable_count: 1,
      sampled_row_count: 3,
    },
    {
      schema_name: 'public',
      name: 'orders',
      type: 'table',
      comment: 'Order facts',
      columns: [
        {
          name: 'id',
          data_type: 'integer',
          native_type: 'integer',
          mapped_type: 'integer',
          nullable: false,
          is_primary_key: true,
          is_foreign_key: false,
          sample_values: ['100', '101', '102'],
          inferred_pii: false,
          inferred_classification: 'internal',
        },
        {
          name: 'customer_id',
          data_type: 'integer',
          native_type: 'integer',
          mapped_type: 'integer',
          nullable: false,
          is_primary_key: false,
          is_foreign_key: true,
          foreign_key_ref: { schema: 'public', table: 'customers', column: 'id' },
          sample_values: ['1', '2', '1'],
          inferred_pii: false,
          inferred_classification: 'internal',
        },
        {
          name: 'amount',
          data_type: 'float',
          native_type: 'numeric',
          mapped_type: 'float',
          nullable: false,
          is_primary_key: false,
          is_foreign_key: false,
          sample_values: ['120.5', '0', '55.25'],
          inferred_pii: false,
          inferred_classification: 'internal',
        },
      ],
      primary_keys: ['id'],
      foreign_keys: [{ column: 'customer_id', referenced_ref: { table: 'customers', column: 'id' } }],
      estimated_rows: 1200000,
      size_bytes: 5690000,
      inferred_classification: 'internal',
      contains_pii: false,
      pii_column_count: 0,
      nullable_count: 0,
      sampled_row_count: 3,
    },
  ],
  table_count: 2,
  column_count: 8,
  contains_pii: true,
  highest_classification: 'confidential',
  warnings: [],
};

export const dataSources: DataSource[] = [
  {
    id: '11111111-1111-1111-1111-111111111111',
    tenant_id: 'tenant-1',
    name: 'Customer Database',
    description: 'Primary PostgreSQL customer database',
    type: 'postgresql',
    connection_config: { host: 'db-prod', port: 5432, database: 'customers' },
    status: 'active',
    last_error: null,
    schema_metadata: sourceSchema,
    schema_discovered_at: '2026-03-05T10:00:00Z',
    last_synced_at: '2026-03-07T08:00:00Z',
    last_sync_status: 'success',
    last_sync_error: null,
    last_sync_duration_ms: 12000,
    sync_frequency: '0 * * * *',
    next_sync_at: '2026-03-07T11:00:00Z',
    table_count: 15,
    total_row_count: 1200000,
    total_size_bytes: 4500000000,
    tags: ['critical'],
    metadata: {},
    created_by: 'user-1',
    created_at: '2026-01-01T00:00:00Z',
    updated_at: '2026-03-07T08:00:00Z',
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    tenant_id: 'tenant-1',
    name: 'Billing API',
    description: 'External billing API',
    type: 'api',
    connection_config: { base_url: 'https://billing.example.com' },
    status: 'error',
    last_error: 'Connection refused to billing.example.com',
    schema_metadata: null,
    schema_discovered_at: null,
    last_synced_at: null,
    last_sync_status: 'failed',
    last_sync_error: 'Connection refused to billing.example.com',
    last_sync_duration_ms: null,
    sync_frequency: null,
    next_sync_at: null,
    table_count: 0,
    total_row_count: 0,
    total_size_bytes: 0,
    tags: [],
    metadata: {},
    created_by: 'user-1',
    created_at: '2026-01-02T00:00:00Z',
    updated_at: '2026-03-06T08:00:00Z',
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    tenant_id: 'tenant-1',
    name: 'CSV Landing Zone',
    description: 'CSV import source',
    type: 'csv',
    connection_config: { bucket: 'ingest', file_path: 'customers.csv' },
    status: 'syncing',
    last_error: null,
    schema_metadata: sourceSchema,
    schema_discovered_at: '2026-03-04T10:00:00Z',
    last_synced_at: '2026-03-07T09:45:00Z',
    last_sync_status: 'running',
    last_sync_error: null,
    last_sync_duration_ms: null,
    sync_frequency: '0 0 * * *',
    next_sync_at: '2026-03-08T00:00:00Z',
    table_count: 1,
    total_row_count: 5000,
    total_size_bytes: 1024000,
    tags: ['landing'],
    metadata: {},
    created_by: 'user-1',
    created_at: '2026-01-03T00:00:00Z',
    updated_at: '2026-03-07T09:45:00Z',
  },
];

export const dataModels: DataModel[] = [
  {
    id: '44444444-4444-4444-4444-444444444444',
    tenant_id: 'tenant-1',
    name: 'customer_master',
    display_name: 'Customer Master',
    description: 'Master customer record',
    status: 'active',
    schema_definition: [
      {
        name: 'id',
        display_name: 'ID',
        data_type: 'integer',
        native_type: 'integer',
        nullable: false,
        is_primary_key: true,
        is_foreign_key: false,
        description: '',
        classification: 'internal',
        validation_rules: [],
      },
      {
        name: 'email',
        display_name: 'Email',
        data_type: 'string',
        native_type: 'varchar(255)',
        nullable: false,
        is_primary_key: false,
        is_foreign_key: false,
        description: '',
        pii_type: 'email',
        classification: 'confidential',
        validation_rules: [],
      },
      {
        name: 'status',
        display_name: 'Status',
        data_type: 'string',
        native_type: 'varchar(20)',
        nullable: false,
        is_primary_key: false,
        is_foreign_key: false,
        description: '',
        classification: 'internal',
        validation_rules: [],
      },
    ],
    source_id: dataSources[0].id,
    source_table: 'public.customers',
    quality_rules: [],
    data_classification: 'confidential',
    contains_pii: true,
    pii_columns: ['email'],
    field_count: 3,
    version: 2,
    previous_version_id: null,
    tags: ['gold'],
    metadata: {},
    created_by: 'user-1',
    created_at: '2026-01-10T00:00:00Z',
    updated_at: '2026-03-05T00:00:00Z',
  },
];

export const pipelineRuns: PipelineRun[] = [
  {
    id: '55555555-5555-5555-5555-555555555555',
    tenant_id: 'tenant-1',
    pipeline_id: '66666666-6666-6666-6666-666666666666',
    status: 'running',
    current_phase: 'transforming',
    records_extracted: 1200,
    records_transformed: 900,
    records_loaded: 0,
    records_failed: 0,
    records_filtered: 25,
    records_deduplicated: 10,
    bytes_read: 120000,
    bytes_written: 0,
    quality_gate_results: [],
    quality_gates_passed: 0,
    quality_gates_failed: 0,
    quality_gates_warned: 0,
    started_at: '2026-03-07T09:30:00Z',
    extract_started_at: '2026-03-07T09:30:00Z',
    extract_completed_at: '2026-03-07T09:31:00Z',
    transform_started_at: '2026-03-07T09:31:00Z',
    transform_completed_at: null,
    load_started_at: null,
    load_completed_at: null,
    completed_at: null,
    duration_ms: 240000,
    error_phase: null,
    error_message: null,
    error_details: null,
    triggered_by: 'manual',
    triggered_by_user: 'user-1',
    retry_count: 0,
    incremental_from: null,
    incremental_to: null,
    created_at: '2026-03-07T09:30:00Z',
  },
  {
    id: '77777777-7777-7777-7777-777777777777',
    tenant_id: 'tenant-1',
    pipeline_id: '66666666-6666-6666-6666-666666666666',
    status: 'completed',
    current_phase: 'loading',
    records_extracted: 2200,
    records_transformed: 2175,
    records_loaded: 2175,
    records_failed: 0,
    records_filtered: 25,
    records_deduplicated: 0,
    bytes_read: 220000,
    bytes_written: 180000,
    quality_gate_results: [
      {
        name: 'Null check',
        metric: 'null_percentage',
        status: 'passed',
        metric_value: 0,
        threshold: 0.5,
        operator: '<=',
        message: 'No null drift detected',
        severity: 'high',
        evaluated_at: '2026-03-07T08:05:00Z',
      },
    ],
    quality_gates_passed: 1,
    quality_gates_failed: 0,
    quality_gates_warned: 0,
    started_at: '2026-03-07T08:00:00Z',
    extract_started_at: '2026-03-07T08:00:00Z',
    extract_completed_at: '2026-03-07T08:01:00Z',
    transform_started_at: '2026-03-07T08:01:00Z',
    transform_completed_at: '2026-03-07T08:03:00Z',
    load_started_at: '2026-03-07T08:03:00Z',
    load_completed_at: '2026-03-07T08:05:00Z',
    completed_at: '2026-03-07T08:05:00Z',
    duration_ms: 300000,
    error_phase: null,
    error_message: null,
    error_details: null,
    triggered_by: 'schedule',
    triggered_by_user: null,
    retry_count: 0,
    incremental_from: null,
    incremental_to: null,
    created_at: '2026-03-07T08:00:00Z',
  },
];

export const pipelines: Pipeline[] = [
  {
    id: '66666666-6666-6666-6666-666666666666',
    tenant_id: 'tenant-1',
    name: 'customer_orders_sync',
    description: 'Sync customer orders into analytics',
    type: 'etl',
    source_id: dataSources[0].id,
    target_id: dataSources[2].id,
    config: {
      source_table: 'public.orders',
      target_table: 'analytics.customer_orders',
      target_model_id: dataModels[0].id,
      transformations: [
        { type: 'rename', config: { from: 'status', to: 'order_status' } },
        { type: 'filter', config: { expression: "amount > 0 AND status == 'A'" } },
      ],
      quality_gates: [
        {
          name: 'Null check',
          metric: 'null_percentage',
          column: 'amount',
          operator: '<=',
          threshold: 0.5,
          severity: 'high',
        },
      ],
      fail_on_quality_gate: true,
      load_strategy: 'merge',
      merge_keys: ['id'],
      max_retries: 3,
      retry_backoff_sec: 60,
    },
    schedule: '0 * * * *',
    status: 'active',
    last_run_id: pipelineRuns[1].id,
    last_run_at: '2026-03-07T08:00:00Z',
    last_run_status: 'completed',
    last_run_error: null,
    next_run_at: '2026-03-07T11:00:00Z',
    total_runs: 14,
    successful_runs: 13,
    failed_runs: 1,
    total_records_processed: 300000,
    avg_duration_ms: 280000,
    tags: ['hourly'],
    created_by: 'user-1',
    created_at: '2026-01-20T00:00:00Z',
    updated_at: '2026-03-07T08:05:00Z',
  },
];

export const qualityRules: QualityRule[] = [
  {
    id: '88888888-8888-8888-8888-888888888888',
    tenant_id: 'tenant-1',
    model_id: dataModels[0].id,
    name: 'email_not_null',
    description: 'Email must be present',
    rule_type: 'not_null',
    severity: 'critical',
    column_name: 'email',
    config: {},
    schedule: '0 2 * * *',
    enabled: true,
    last_run_at: '2026-03-07T02:00:00Z',
    last_status: 'failed',
    consecutive_failures: 2,
    tags: ['customer'],
    created_by: 'user-1',
    created_at: '2026-02-01T00:00:00Z',
    updated_at: '2026-03-07T02:05:00Z',
  },
];

export const qualityResult: QualityResult = {
  id: '99999999-9999-9999-9999-999999999999',
  tenant_id: 'tenant-1',
  rule_id: qualityRules[0].id,
  model_id: dataModels[0].id,
  pipeline_run_id: pipelineRuns[1].id,
  status: 'failed',
  records_checked: 2000,
  records_passed: 1990,
  records_failed: 10,
  pass_rate: 99.5,
  failure_samples: [{ id: 1, email: null }],
  failure_summary: '10 customer rows are missing email addresses',
  checked_at: '2026-03-07T02:05:00Z',
  duration_ms: 1200,
  error_message: null,
  created_at: '2026-03-07T02:05:00Z',
};

export const qualityScore: QualityScore = {
  overall_score: 92,
  grade: 'A-',
  model_scores: [
    {
      model_id: dataModels[0].id,
      model_name: dataModels[0].display_name,
      classification: 'confidential',
      score: 92,
      total_rules: 4,
      passed_rules: 3,
      failed_rules: 1,
      warning_rules: 0,
      classification_weight: 1.3,
    },
  ],
  total_rules: 4,
  passed_rules: 3,
  failed_rules: 1,
  warning_rules: 0,
  pass_rate: 75,
  top_failures: [
    {
      rule_id: qualityRules[0].id,
      rule_name: qualityRules[0].name,
      model_id: dataModels[0].id,
      model_name: dataModels[0].display_name,
      severity: 'critical',
      status: 'failed',
      records_failed: 10,
    },
  ],
  trend: 'up',
  trend_delta: 4,
  calculated_at: '2026-03-07T09:00:00Z',
};

export const contradictions: Contradiction[] = [
  {
    id: 'aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
    tenant_id: 'tenant-1',
    scan_id: 'scan-1',
    type: 'semantic',
    severity: 'high',
    confidence_score: 0.88,
    title: 'Customer email mismatch',
    description: 'CRM and billing store different email addresses',
    source_a: {
      source_id: dataSources[0].id,
      source_name: 'CRM Database',
      model_name: '',
      table_name: 'customers',
      column_name: 'email',
      value: 'john@company-a.com',
      last_synced_at: '2026-03-07T08:00:00Z',
    },
    source_b: {
      source_id: dataSources[1].id,
      source_name: 'Billing System',
      model_name: '',
      table_name: 'contact',
      column_name: 'email',
      value: 'john@company-b.com',
      last_synced_at: '2026-03-04T08:00:00Z',
    },
    entity_key_column: 'customer_id',
    entity_key_value: 'CUS-001',
    affected_records: 23,
    sample_records: [
      {
        entity_key: 'CUS-001',
        source_a_value: 'john@company-a.com',
        source_b_value: 'john@company-b.com',
        match_type: 'Exact mismatch',
      },
    ],
    resolution_guidance: 'Update billing to match CRM',
    authoritative_source: 'CRM Database',
    status: 'detected',
    resolved_by: null,
    resolved_at: null,
    resolution_notes: null,
    resolution_action: null,
    metadata: {},
    created_at: '2026-03-06T10:00:00Z',
    updated_at: '2026-03-06T10:00:00Z',
  },
];

export const contradictionStats: ContradictionStats = {
  total: 5,
  by_status: {
    open: 2,
    investigating: 1,
    resolved: 1,
    accepted: 1,
    false_positive: 0,
  },
  by_type: {
    semantic: 3,
    temporal: 2,
  },
  by_severity: {
    critical: 1,
    high: 2,
    medium: 2,
  },
  average_confidence: 82,
  open_contradictions: 2,
  updated_at: '2026-03-07T09:00:00Z',
};

export const contradictionScan: ContradictionScan = {
  id: 'scan-1',
  tenant_id: 'tenant-1',
  status: 'completed',
  models_scanned: 2,
  model_pairs_compared: 3,
  contradictions_found: 3,
  by_type: { semantic: 2, temporal: 1 },
  by_severity: { high: 2, medium: 1 },
  started_at: '2026-03-07T09:00:00Z',
  completed_at: '2026-03-07T09:05:00Z',
  duration_ms: 300000,
  triggered_by: 'manual',
  created_at: '2026-03-07T09:00:00Z',
};

export const lineageGraph: LineageGraph = {
  nodes: [
    { id: 'source-1', type: 'data_source', entity_id: dataSources[0].id, name: dataSources[0].name, status: 'active', metadata: {}, depth: 0, in_degree: 0, out_degree: 1, is_critical: true },
    { id: 'pipeline-1', type: 'pipeline', entity_id: pipelines[0].id, name: pipelines[0].name, status: 'active', metadata: {}, depth: 1, in_degree: 1, out_degree: 1, is_critical: true },
    { id: 'model-1', type: 'data_model', entity_id: dataModels[0].id, name: dataModels[0].display_name, status: 'active', metadata: {}, depth: 2, in_degree: 1, out_degree: 1, is_critical: true },
    { id: 'consumer-1', type: 'suite_consumer', entity_id: 'consumer-1', name: 'Visus360 KPIs', status: 'active', metadata: {}, depth: 3, in_degree: 1, out_degree: 0, is_critical: false },
  ],
  edges: [
    { id: 'edge-1', source: 'source-1', target: 'pipeline-1', relationship: 'extracts', active: true, last_seen_at: '2026-03-07T09:00:00Z' },
    { id: 'edge-2', source: 'pipeline-1', target: 'model-1', relationship: 'loads', active: true, last_seen_at: '2026-03-07T09:00:00Z' },
    { id: 'edge-3', source: 'model-1', target: 'consumer-1', relationship: 'serves', active: true, last_seen_at: '2026-03-07T09:00:00Z' },
  ],
  stats: {
    node_count: 4,
    edge_count: 3,
    max_depth: 3,
    source_count: 1,
    consumer_count: 1,
    nodes_by_type: {
      data_source: 1,
      pipeline: 1,
      data_model: 1,
      suite_consumer: 1,
    },
  },
};

export const darkDataAssets: DarkDataAsset[] = [
  {
    id: 'dddddddd-dddd-dddd-dddd-dddddddddddd',
    tenant_id: 'tenant-1',
    scan_id: 'scan-1',
    name: 'legacy_customer_dump',
    asset_type: 'file',
    source_id: dataSources[2].id,
    source_name: dataSources[2].name,
    schema_name: null,
    table_name: null,
    file_path: '/mnt/legacy/customer_dump.csv',
    reason: 'ungoverned',
    estimated_row_count: 50000,
    estimated_size_bytes: 52428800,
    column_count: 12,
    contains_pii: true,
    pii_types: ['email', 'name'],
    inferred_classification: 'restricted',
    last_accessed_at: '2025-12-01T00:00:00Z',
    last_modified_at: '2026-01-15T00:00:00Z',
    days_since_access: 96,
    risk_score: 82,
    risk_factors: [{ factor: 'contains_pii', value: 40 }],
    governance_status: 'unmanaged',
    governance_notes: null,
    reviewed_by: null,
    reviewed_at: null,
    linked_model_id: null,
    metadata: {},
    discovered_at: '2026-03-07T08:00:00Z',
    created_at: '2026-03-07T08:00:00Z',
    updated_at: '2026-03-07T08:00:00Z',
  },
];

export const darkDataStats: DarkDataStatsSummary = {
  total_assets: 10,
  by_reason: { ungoverned: 4, stale: 3, unmodeled: 3 },
  by_type: { file: 5, database_table: 3, api_endpoint: 2 },
  by_governance_status: { unmanaged: 6, under_review: 1, governed: 2, archived: 1 },
  pii_assets: 4,
  high_risk_assets: 3,
  total_size_bytes: 1048576000,
  average_risk_score: 58,
  governed_assets: 2,
  scheduled_deletion_count: 1,
};

export const darkDataScan: DarkDataScan = {
  id: 'dark-scan-1',
  tenant_id: 'tenant-1',
  status: 'completed',
  sources_scanned: 3,
  storage_scanned: true,
  assets_discovered: 10,
  by_reason: { ungoverned: 4 },
  by_type: { file: 5 },
  pii_assets_found: 4,
  high_risk_found: 3,
  total_size_bytes: 1048576000,
  started_at: '2026-03-07T08:00:00Z',
  completed_at: '2026-03-07T08:05:00Z',
  duration_ms: 300000,
  triggered_by: 'manual',
  created_at: '2026-03-07T08:00:00Z',
};

export const dashboard: DataSuiteDashboard = {
  kpis: {
    total_sources: 10,
    active_pipelines: 8,
    quality_score: 92,
    quality_grade: 'A-',
    open_contradictions: 7,
    dark_data_assets: 10,
    total_models: 15,
    failed_pipelines_24h: 1,
    sources_delta: 2,
    quality_delta: 4,
    contradictions_delta: 1,
  },
  pipeline_trend_30d: Array.from({ length: 30 }, (_, index) => ({
    day: `2026-02-${String(index + 1).padStart(2, '0')}`,
    value: 10 + index,
  })),
  quality_trend_30d: Array.from({ length: 30 }, (_, index) => ({
    day: `2026-02-${String(index + 1).padStart(2, '0')}`,
    value: 80 + (index % 10),
  })),
  sources_by_type: { postgresql: 5, mysql: 2, api: 2, csv: 1 },
  sources_by_status: { active: 7, inactive: 1, error: 1, syncing: 1 },
  pipelines_by_status: { active: 6, paused: 1, error: 1 },
  recent_runs: pipelineRuns.map((run) => ({
    id: run.id,
    pipeline_id: pipelines[0].id,
    pipeline_name: pipelines[0].name,
    status: run.status,
    started_at: run.started_at,
    completed_at: run.completed_at,
    duration_ms: run.duration_ms,
  })),
  pipeline_success_rate_30d: 93.4,
  quality_score: {
    overall_score: qualityScore.overall_score,
    grade: qualityScore.grade,
    passed_rules: qualityScore.passed_rules,
    failed_rules: qualityScore.failed_rules,
    warning_rules: qualityScore.warning_rules,
    pass_rate: qualityScore.pass_rate,
  },
  quality_by_model: qualityScore.model_scores.map((item) => ({
    model_id: item.model_id,
    model_name: item.model_name,
    classification: item.classification,
    score: item.score,
  })),
  top_quality_failures: qualityScore.top_failures.map((item) => ({
    rule_id: item.rule_id,
    rule_name: item.rule_name,
    model_id: item.model_id,
    model_name: item.model_name,
    severity: item.severity,
    records_failed: item.records_failed,
  })),
  contradictions_by_type: { semantic: 3, temporal: 2 },
  contradictions_by_severity: { critical: 1, high: 4, medium: 2 },
  open_contradictions: 7,
  lineage_stats: { node_count: 4, edge_count: 3 },
  dark_data_stats: { total_assets: 10, high_risk_assets: 3 },
  calculated_at: '2026-03-07T09:00:00Z',
};

export const analyticsResult: QueryResult = {
  columns: [
    { name: 'email', data_type: 'string', classification: 'confidential', is_pii: true, masked: true },
    { name: 'status', data_type: 'string', classification: 'internal', is_pii: false, masked: false },
  ],
  rows: [
    { email: 'j***@e*****.com', status: 'active' },
    { email: 's***@e*****.com', status: 'inactive' },
  ],
  row_count: 2,
  total_count: 150,
  truncated: true,
  metadata: {
    model_name: dataModels[0].display_name,
    data_classification: 'confidential',
    pii_masking_applied: true,
    columns_masked: ['email'],
    execution_time_ms: 55,
    cached_result: false,
  },
};

export const savedQueries: SavedQuery[] = [
  {
    id: 'saved-1',
    tenant_id: 'tenant-1',
    name: 'Customer emails',
    description: 'Basic customer email query',
    model_id: dataModels[0].id,
    query_definition: {
      columns: ['email'],
      filters: [],
      aggregations: [],
      group_by: [],
      order_by: [],
      limit: 100,
    } as AnalyticsQuery,
    visibility: 'team',
    tags: ['shared'],
    run_count: 3,
    last_run_at: '2026-03-07T07:00:00Z',
    created_by: 'user-1',
    created_at: '2026-03-01T00:00:00Z',
    updated_at: '2026-03-07T07:00:00Z',
  },
];

export function paginated<T>(data: T[]) {
  return {
    data,
    meta: {
      page: 1,
      per_page: data.length || 1,
      total: data.length,
      total_pages: 1,
    },
  };
}
