package engine

import (
	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promauto"
)

type UEBAMetrics struct {
	EngineCycleDurationSeconds *prometheus.HistogramVec
	EngineCyclesTotal          *prometheus.CounterVec
	EventsCollectedTotal       *prometheus.CounterVec
	EventsDeduplicatedTotal    *prometheus.CounterVec
	ProfilesTotal              *prometheus.GaugeVec
	ProfilesUpdatedTotal       *prometheus.CounterVec
	AnomalySignalsTotal        *prometheus.CounterVec
	AlertsCreatedTotal         *prometheus.CounterVec
	AlertsCorrelatedTotal      *prometheus.CounterVec
	RiskScoreDistribution      *prometheus.HistogramVec
	RiskScoreUpdatesTotal      *prometheus.CounterVec
	FalsePositivesTotal        *prometheus.CounterVec
}

func NewMetrics(reg prometheus.Registerer) *UEBAMetrics {
	factory := promauto.With(reg)
	return &UEBAMetrics{
		EngineCycleDurationSeconds: factory.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: "ueba",
			Name:      "engine_cycle_duration_seconds",
			Help:      "Time spent executing one tenant UEBA cycle.",
			Buckets:   []float64{1, 5, 10, 20, 30, 45, 60, 90},
		}, []string{"tenant_id"}),
		EngineCyclesTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "engine_cycles_total",
			Help:      "Total UEBA cycles by completion status.",
		}, []string{"tenant_id", "status"}),
		EventsCollectedTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "events_collected_total",
			Help:      "Total UEBA access events collected by source.",
		}, []string{"tenant_id", "source_type"}),
		EventsDeduplicatedTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "events_deduplicated_total",
			Help:      "Total UEBA events removed as duplicates during collection.",
		}, []string{"tenant_id"}),
		ProfilesTotal: factory.NewGaugeVec(prometheus.GaugeOpts{
			Namespace: "ueba",
			Name:      "profiles_total",
			Help:      "Current UEBA profile counts by maturity and status.",
		}, []string{"tenant_id", "maturity", "status"}),
		ProfilesUpdatedTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "profiles_updated_total",
			Help:      "Total UEBA profile updates applied.",
		}, []string{"tenant_id"}),
		AnomalySignalsTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "anomaly_signals_total",
			Help:      "Total anomaly signals generated by type and severity.",
		}, []string{"tenant_id", "signal_type", "severity"}),
		AlertsCreatedTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "alerts_created_total",
			Help:      "Total UEBA alerts created by type and severity.",
		}, []string{"tenant_id", "alert_type", "severity"}),
		AlertsCorrelatedTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "alerts_correlated_total",
			Help:      "Total times multi-signal correlation produced UEBA findings.",
		}, []string{"tenant_id"}),
		RiskScoreDistribution: factory.NewHistogramVec(prometheus.HistogramOpts{
			Namespace: "ueba",
			Name:      "risk_score_distribution",
			Help:      "Distribution of entity risk scores after UEBA scoring updates.",
			Buckets:   []float64{0, 10, 25, 50, 75, 90, 100},
		}, []string{"tenant_id"}),
		RiskScoreUpdatesTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "risk_score_updates_total",
			Help:      "Total UEBA risk score recalculations.",
		}, []string{"tenant_id"}),
		FalsePositivesTotal: factory.NewCounterVec(prometheus.CounterOpts{
			Namespace: "ueba",
			Name:      "false_positives_total",
			Help:      "Total UEBA false positives recorded by signal type.",
		}, []string{"tenant_id", "signal_type"}),
	}
}
