{{- if .Values.cyberService.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clario360.componentName" (dict "root" . "component" "cyber-service") }}-config
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "cyber-service") | nindent 4 }}
data:
  CYBER_HTTP_PORT: "8090"
  METRICS_PORT: "9090"
  CYBER_KAFKA_GROUP_ID: "cyber-service"
  {{- with .Values.cyberService.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
