"use client";

import { useLocaleOrDefault } from "@/components/providers/locale-provider";

const labels = {
  en: {
    suite: "WatheeqTech",
    investigations: "Cases & Investigations",
    caseReport: "Case Report",
    title: "Investigation Report & Findings",
    casePrefix: "Case",
    draft: "Draft",
    saveDraft: "Save Draft",
    exportPdf: "Export PDF",
    submitReview: "Submit for Review",
    executiveSummary: "Executive Summary",
    executiveSummaryPlaceholder:
      "Summarize the investigation, scope, and material conclusions.",
    keyFindings: "Key Findings",
    addFinding: "Add finding",
    finding: "Finding",
    findingTitlePlaceholder: "Finding title",
    findingDescriptionPlaceholder:
      "Describe the supporting facts and conclusion.",
    recommendations: "Recommendations",
    addRecommendation: "Add recommendation",
    recommendation: "Recommendation",
    recommendationTitlePlaceholder: "Recommendation title",
    recommendationDescriptionPlaceholder: "Describe the corrective action.",
    owner: "Owner",
    ownerPlaceholder: "Responsible owner",
    timing: "Timing / due date",
    timingPlaceholder: "Immediate or due date",
    approval: "Approval & Sign-off Workflow",
    reportPrepared: "Report prepared",
    leadInvestigator: "Lead investigator",
    reviewNotStarted: "Review not started",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    inReview: "Under Review",
    prepared: "Prepared",
    evidenceGrid: "Associated Evidence Reference Grid",
    artifactId: "Artifact ID",
    relevance: "Brief Relevance & Use Case in Findings",
    verification: "Verification Standard",
    evidenceEmpty: "No evidence has been associated with this investigation.",
    catalogued: "Catalogued",
    verified: "Verified",
    remove: "Remove",
    back: "Back to investigation",
    loadingTitle: "Loading investigation report",
    loadingDescription: "Retrieving findings, evidence, and approval status.",
    error: "The investigation report could not be loaded.",
    draftSaved: "Investigation report draft saved",
    reviewStarted: "Investigation report submitted for review",
    validation:
      "Add at least one finding and one recommendation before submitting.",
    readonly: "This report is read-only in its current lifecycle state.",
    printTitle: "Investigation report",
    severity: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
  },
  ar: {
    suite: "وثيق تك",
    investigations: "القضايا والتحقيقات",
    caseReport: "تقرير القضية",
    title: "تقرير التحقيق والنتائج",
    casePrefix: "القضية",
    draft: "مسودة",
    saveDraft: "حفظ المسودة",
    exportPdf: "تصدير PDF",
    submitReview: "إرسال للمراجعة",
    executiveSummary: "الملخص التنفيذي",
    executiveSummaryPlaceholder: "لخّص نطاق التحقيق وأبرز النتائج الجوهرية.",
    keyFindings: "النتائج الرئيسية",
    addFinding: "إضافة نتيجة",
    finding: "نتيجة",
    findingTitlePlaceholder: "عنوان النتيجة",
    findingDescriptionPlaceholder: "صف الوقائع المؤيدة والاستنتاج.",
    recommendations: "التوصيات",
    addRecommendation: "إضافة توصية",
    recommendation: "توصية",
    recommendationTitlePlaceholder: "عنوان التوصية",
    recommendationDescriptionPlaceholder: "صف الإجراء التصحيحي.",
    owner: "الجهة المسؤولة",
    ownerPlaceholder: "الجهة المسؤولة",
    timing: "الموعد / تاريخ الاستحقاق",
    timingPlaceholder: "فوري أو تاريخ الاستحقاق",
    approval: "مسار الاعتماد والتوقيع",
    reportPrepared: "تم إعداد التقرير",
    leadInvestigator: "المحقق الرئيسي",
    reviewNotStarted: "لم تبدأ المراجعة",
    pending: "قيد الانتظار",
    approved: "معتمد",
    rejected: "مرفوض",
    inReview: "قيد المراجعة",
    prepared: "مُعد",
    evidenceGrid: "جدول مراجع الأدلة المرتبطة",
    artifactId: "معرّف الدليل",
    relevance: "الصلة المختصرة والاستخدام في النتائج",
    verification: "معيار التحقق",
    evidenceEmpty: "لا توجد أدلة مرتبطة بهذا التحقيق.",
    catalogued: "مفهرس",
    verified: "تم التحقق",
    remove: "إزالة",
    back: "العودة إلى التحقيق",
    loadingTitle: "جارٍ تحميل تقرير التحقيق",
    loadingDescription: "جارٍ استرجاع النتائج والأدلة وحالة الاعتماد.",
    error: "تعذر تحميل تقرير التحقيق.",
    draftSaved: "تم حفظ مسودة تقرير التحقيق",
    reviewStarted: "تم إرسال تقرير التحقيق للمراجعة",
    validation: "أضف نتيجة واحدة وتوصية واحدة على الأقل قبل الإرسال.",
    readonly: "هذا التقرير للقراءة فقط في مرحلته الحالية.",
    printTitle: "تقرير التحقيق",
    severity: {
      critical: "حرجة",
      high: "عالية",
      medium: "متوسطة",
      low: "منخفضة",
    },
  },
} as const;

export type InvestigationReportLabels = (typeof labels)["en"];

export function useInvestigationReportLabels(): InvestigationReportLabels {
  const { locale } = useLocaleOrDefault();
  return (locale === "ar" ? labels.ar : labels.en) as InvestigationReportLabels;
}
