package drafting

import (
	"context"
	"fmt"
	"strings"

	"github.com/google/uuid"

	llmmodel "github.com/clario360/platform/internal/cyber/vciso/llm/model"
	provider "github.com/clario360/platform/internal/cyber/vciso/llm/provider"
)

// streamDraftingSystem instructs the model to emit ONLY the clause text (no tool,
// no JSON, no preamble). Plain-text generation streams token-by-token smoothly,
// whereas a forced tool call streams its structured input in coarse bursts — so
// the interactive streaming path generates text and derives the light structure
// (title/clause_type) locally. The buffered GenerateClause remains the fully
// structured, governed path (rationale/risk_level/assumptions).
const streamDraftingSystem = "You are an expert legal drafting engine for Saudi and GCC law. " +
	"Draft clear, enforceable, balanced clause language consistent with Saudi law and common GCC commercial practice. " +
	"Be precise and conservative; never invent facts not supplied. " +
	"Output ONLY the clause text itself, ready to paste into a contract. " +
	"Do not add any preamble, heading label, explanation, commentary, markdown, or JSON."

// GenerateClauseStream is the streaming twin of GenerateClause (AID-01). It
// streams the clause text word-by-word through emit as the model writes it and
// returns the assembled GeneratedClause when the stream ends. The clause TEXT is
// generated by the same model at the same quality; the structured extras
// (rationale/risk_level/assumptions) are not assessed on this fast interactive
// path — use the buffered GenerateClause for the full governed structure. When
// the resolved provider cannot stream, it falls back to one buffered generate.
func (d *Drafter) GenerateClauseStream(ctx context.Context, tenantID uuid.UUID, req ClauseRequest, emit func(delta string)) (*GeneratedClause, error) {
	if !d.Enabled() {
		return nil, ErrDraftingDisabled
	}
	user := fmt.Sprintf("Draft a contract clause.\nIntent: %s\nClause type: %s\nContract type: %s\nContext: %s\n%s",
		strings.TrimSpace(req.Intent), orNA(req.ClauseType), orNA(req.ContractType), orNA(d.truncate(req.Context)), langLine(req.Language))

	cctx, cancel := context.WithTimeout(ctx, d.cfg.Timeout)
	defer cancel()

	prov, err := d.resolver.Resolve(cctx, tenantID)
	if err != nil {
		return nil, fmt.Errorf("resolve llm provider: %w", err)
	}

	streamer, ok := prov.(provider.StreamingProvider)
	if !ok {
		// Provider can't stream (non-anthropic tier): fall back to one buffered
		// generate so callers still get a clause, emitted in a single chunk.
		out, gerr := d.GenerateClause(ctx, tenantID, req)
		if gerr != nil {
			return nil, gerr
		}
		if emit != nil && out.Text != "" {
			emit(out.Text)
		}
		return out, nil
	}

	var full strings.Builder
	llmReq := &provider.CompletionRequest{
		SystemPrompt:   streamDraftingSystem,
		Messages:       []llmmodel.LLMMessage{{Role: "user", Content: user}},
		MaxTokens:      d.cfg.MaxTokens,
		ResponseFormat: "text",
	}
	handler := provider.StreamHandler{
		OnText: func(delta string) error {
			full.WriteString(delta)
			if emit != nil && delta != "" {
				emit(delta)
			}
			return nil
		},
	}

	resp, err := streamer.StreamComplete(cctx, llmReq, handler)
	if err != nil {
		return nil, fmt.Errorf("llm stream: %w", err)
	}
	text := strings.TrimSpace(full.String())
	if text == "" {
		text = strings.TrimSpace(resp.Content)
	}
	return &GeneratedClause{
		Title:      streamClauseTitle(req),
		ClauseType: strings.TrimSpace(req.ClauseType),
		Text:       text,
		Language:   cleanLang(req.Language),
		Meta: map[string]any{
			"model":    prov.Model(),
			"provider": prov.Name(),
			"tokens":   resp.Usage.TotalTokens,
			"streamed": true,
		},
	}, nil
}

// streamClauseTitle derives a human-readable heading for a streamed clause
// (which has no model-generated title) from its clause type and language.
func streamClauseTitle(req ClauseRequest) string {
	ar := cleanLang(req.Language) == "ar"
	ct := strings.ToLower(strings.TrimSpace(req.ClauseType))
	labels := map[string][2]string{ // {english, arabic}
		"confidentiality":         {"Confidentiality Clause", "بند السرية"},
		"dispute_resolution":      {"Dispute Resolution Clause", "بند تسوية المنازعات"},
		"limitation_of_liability": {"Limitation of Liability Clause", "بند تحديد المسؤولية"},
		"indemnity":               {"Indemnity Clause", "بند التعويض"},
		"termination":             {"Termination Clause", "بند الإنهاء"},
		"force_majeure":           {"Force Majeure Clause", "بند القوة القاهرة"},
		"governing_law":           {"Governing Law Clause", "بند القانون الحاكم"},
		"intellectual_property":   {"Intellectual Property Clause", "بند الملكية الفكرية"},
		"payment":                 {"Payment Clause", "بند الدفع"},
		"warranty":                {"Warranty Clause", "بند الضمان"},
		"non_compete":             {"Non-Compete Clause", "بند عدم المنافسة"},
		"data_protection":         {"Data Protection Clause", "بند حماية البيانات"},
	}
	if l, ok := labels[ct]; ok {
		if ar {
			return l[1]
		}
		return l[0]
	}
	if ct != "" {
		h := strings.ReplaceAll(ct, "_", " ")
		if len(h) > 0 {
			h = strings.ToUpper(h[:1]) + h[1:]
		}
		if ar {
			return "بند: " + h
		}
		return h + " Clause"
	}
	if ar {
		return "بند مُقترح"
	}
	return "Drafted Clause"
}
