export const breadcrumbMap: Record<string, string> = {
  dashboard: 'Dashboard',
  cyber: 'Cybersecurity',
  cti: 'Threat Intelligence',
  assets: 'Assets',
  alerts: 'Alerts',
  threats: 'Threat Hunting',
  events: 'Threat Events',
  campaigns: 'Campaigns',
  actors: 'Threat Actors',
  'brand-abuse': 'Brand Abuse',
  sectors: 'Sector Targeting',
  geo: 'Geographic Analysis',
  ctem: 'CTEM Assessments',
  remediation: 'Remediation',
  dspm: 'DSPM',
  vciso: 'Virtual CISO',
  'risk-register': 'Risk Register',
  policies: 'Policies',
  'third-party': 'Third-Party Risk',
  evidence: 'Evidence',
  maturity: 'Maturity & Budget',
  awareness: 'Awareness & IAM',
  'incident-readiness': 'Incident Readiness',
  integrations: 'Integrations',
  data: 'Data Intelligence',
  sources: 'Data Sources',
  models: 'Data Models',
  pipelines: 'Pipelines',
  quality: 'Data Quality',
  contradictions: 'Contradictions',
  'dark-data': 'Dark Data',
  analytics: 'Analytics',
  dr: 'ClarioDR',
  protect: 'Protect',
  topology: 'Topology',
  runbooks: 'Runbooks',
  recover: 'Recover',
  rehearse: 'Rehearse',
  prove: 'Prove',
  ledger: 'Attestation Ledger',
  approvals: 'Approvals',
  readiness: 'Readiness',
  insights: 'Insights',
  runs: 'Recovery Runs',
  groups: 'Protection Groups',
  replication: 'Replication',
  failover: 'Failover',
  drills: 'Drills & Tests',
  'recovery-points': 'Recovery Points',
  attestation: 'Attestation',
  acta: 'Governance',
  committees: 'Committees',
  meetings: 'Meetings',
  'action-items': 'Action Items',
  lex: 'وثيقتك',
  contracts: 'Contracts',
  documents: 'Documents',
  matters: 'Matters',
  playbooks: 'Playbooks',
  obligations: 'Obligations',
  'workflow-policies': 'Workflow Policies',
  'clause-library': 'Clause Library',
  regulations: 'Regulations',
  signatures: 'Signatures',
  compliance: 'Compliance',
  visus: 'Executive Intelligence',
  dashboards: 'Dashboards',
  reports: 'Reports',
  admin: 'Platform',
  users: 'Users',
  roles: 'Roles',
  audit: 'Audit Logs',
  settings: 'Settings',
  workflows: 'Workflows',
  tasks: 'Tasks',
  notifications: 'Notifications',
  files: 'Files',
  notifications_prefs: 'Notification Preferences',
  tenants: 'Tenants',
  'api-keys': 'API Keys',
  invitations: 'Invitations',
  new: 'New',
  callback: 'Callback',
};

export const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export function isUUID(segment: string): boolean {
  return UUID_REGEX.test(segment);
}

export function segmentToLabel(segment: string): string {
  if (breadcrumbMap[segment]) return breadcrumbMap[segment];
  // Title-case hyphenated slugs
  return segment
    .split('-')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
