{{- if .Values.auditService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clario360.componentName" (dict "root" . "component" "audit-service") }}
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "audit-service") | nindent 4 }}
  {{- with ((.Values.auditService).service).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ dig "service" "type" "ClusterIP" .Values.auditService }}
  ports:
    - name: http
      port: 8084
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9084
      targetPort: admin
      protocol: TCP
  selector:
    {{- include "clario360.componentSelectorLabels" (dict "root" . "component" "audit-service") | nindent 4 }}
{{- end }}
