import {
  Archive,
  ArrowRight,
  ArrowRightLeft,
  BadgeCheck,
  Bell,
  BookOpen,
  Bot,
  Boxes,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  CheckCircle2,
  ChevronRight,
  Circle,
  ClipboardList,
  Database,
  Eye,
  File,
  FileText,
  Fingerprint,
  Flag,
  FormInput,
  Gauge,
  Gavel,
  Globe2,
  Handshake,
  KeyRound,
  Layers,
  Lock,
  Mail,
  MapPin,
  Network,
  Pencil,
  Phone,
  Plug,
  Radar,
  RefreshCcw,
  RotateCcw,
  Scale,
  Search,
  Server,
  Shield,
  Sparkles,
  Target,
  TrendingUp,
  TriangleAlert,
  Users,
  Workflow,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/utils';

const ICONS = {
  alert: TriangleAlert,
  archive: Archive,
  arrow: ArrowRight,
  bell: Bell,
  book: BookOpen,
  bot: Bot,
  boxes: Boxes,
  briefcase: BriefcaseBusiness,
  building: Building2,
  calendar: CalendarDays,
  check: CheckCircle2,
  checkCircle: CheckCircle2,
  chev: ChevronRight,
  clipboard: ClipboardList,
  cube: Boxes,
  cycle: RefreshCcw,
  database: Database,
  doc: FileText,
  eye: Eye,
  file: File,
  finger: Fingerprint,
  flag: Flag,
  form: FormInput,
  gauge: Gauge,
  gavel: Gavel,
  globe: Globe2,
  handshake: Handshake,
  key: KeyRound,
  layers: Layers,
  license: BadgeCheck,
  lock: Lock,
  mail: Mail,
  migrate: ArrowRightLeft,
  network: Network,
  pen: Pencil,
  phone: Phone,
  pin: MapPin,
  plug: Plug,
  radar: Radar,
  recover: RotateCcw,
  scale: Scale,
  search: Search,
  server: Server,
  shield: Shield,
  sparkle: Sparkles,
  sync: RefreshCcw,
  target: Target,
  trend: TrendingUp,
  users: Users,
  workflow: Workflow,
  x: XCircle,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type MarketingIconName = keyof typeof ICONS | (string & {});

export function getMarketingIcon(name: MarketingIconName): LucideIcon {
  return name in ICONS ? ICONS[name as keyof typeof ICONS] : Circle;
}

export function MarketingIcon({
  name,
  className,
}: {
  name: MarketingIconName;
  className?: string;
}) {
  const Icon = getMarketingIcon(name);

  return <Icon aria-hidden className={cn('h-5 w-5', className)} />;
}
