'use client';

import { useLocaleOrDefault } from '@/components/providers/locale-provider';

const EN = {
  common: {
    notSet: 'Not set',
    file: 'File',
    reference: 'Court reference',
    decisionReference: 'Decision reference',
    documentReference: 'Document reference',
  },
  evidence: {
    title: 'Evidence Submission Logs',
    description: 'Court-ready evidence, submission status, references, and supporting files.',
    summary: 'Evidence Summary',
    total: 'Total submissions',
    admitted: 'Accepted by court',
    review: 'Under review',
    challenged: 'Objected / rejected',
    strength: 'Evidence strength meter',
    strengthHint: 'Calculated from court admission status and recorded evidence strength.',
    categories: 'Categories Breakdown',
    submittedBy: 'Submitted by',
    courtStatus: 'Court status',
    admittedLabel: 'Admitted',
    pendingLabel: 'Under review',
    submittedLabel: 'Submitted',
    rejectedLabel: 'Objected',
    withdrawnLabel: 'Withdrawn',
    uncategorized: 'Uncategorized',
  },
  filings: {
    title: 'Requests & Memorandums',
    description: 'Incoming, outgoing, and internal legal filings with court response deadlines.',
    overview: 'Requests Overview',
    total: 'Total active filings',
    outgoing: 'Outgoing legal submissions',
    incoming: 'Incoming opposing notices',
    rate: 'Court acceptance rate',
    deadlines: 'Upcoming Deadlines',
    recipient: 'Recipient / target body',
    deadline: 'Response deadline',
    direction: {
      incoming: 'Incoming',
      outgoing: 'Outgoing',
      internal: 'Internal',
    },
  },
  decisions: {
    title: 'Judicial Decisions',
    description: 'Court rulings, their impact, implications, and the expected next decision.',
    overview: 'Decisions Summary',
    total: 'Total court decisions',
    positive: 'Favorable rulings',
    neutral: 'Neutral determinations',
    negative: 'Unfavorable outcomes',
    trajectory: 'Case Trajectory Indicator',
    positiveTrajectory: 'Positive trajectory',
    neutralTrajectory: 'Neutral trajectory',
    negativeTrajectory: 'Negative trajectory',
    positiveHint: 'The recorded rulings favor the current case position.',
    neutralHint: 'The recorded rulings indicate a balanced case position.',
    negativeHint: 'The recorded rulings require corrective case action.',
    next: 'Next expected ruling',
    judge: 'Judge',
    court: 'Court',
    summary: 'Decision summary',
    implications: 'Implications for next steps',
    impact: {
      positive: 'Favorable status',
      negative: 'Unfavorable status',
      neutral: 'Neutral impact',
      mixed: 'Mixed impact',
    },
  },
};

const AR: typeof EN = {
  common: {
    notSet: 'غير محدد',
    file: 'الملف',
    reference: 'مرجع المحكمة',
    decisionReference: 'مرجع القرار',
    documentReference: 'مرجع المستند',
  },
  evidence: {
    title: 'سجل تقديم الأدلة',
    description: 'أدلة جاهزة للمحكمة مع حالة التقديم والمراجع والملفات المؤيدة.',
    summary: 'ملخص الأدلة',
    total: 'إجمالي التقديمات',
    admitted: 'مقبولة لدى المحكمة',
    review: 'قيد المراجعة',
    challenged: 'معترض عليها / مرفوضة',
    strength: 'مؤشر قوة الأدلة',
    strengthHint: 'يُحسب من حالة قبول المحكمة وقوة الدليل المسجلة.',
    categories: 'توزيع الفئات',
    submittedBy: 'مقدم الدليل',
    courtStatus: 'حالة المحكمة',
    admittedLabel: 'مقبول',
    pendingLabel: 'قيد المراجعة',
    submittedLabel: 'تم التقديم',
    rejectedLabel: 'معترض عليه',
    withdrawnLabel: 'مسحوب',
    uncategorized: 'غير مصنف',
  },
  filings: {
    title: 'الطلبات والمذكرات',
    description: 'ملفات قانونية واردة وصادرة وداخلية مع مواعيد الرد أمام المحكمة.',
    overview: 'ملخص الطلبات',
    total: 'إجمالي الملفات النشطة',
    outgoing: 'المذكرات القانونية الصادرة',
    incoming: 'الإشعارات الواردة من الخصم',
    rate: 'نسبة قبول المحكمة',
    deadlines: 'المواعيد القادمة',
    recipient: 'المستلم / الجهة المستهدفة',
    deadline: 'موعد الرد',
    direction: {
      incoming: 'وارد',
      outgoing: 'صادر',
      internal: 'داخلي',
    },
  },
  decisions: {
    title: 'القرارات القضائية',
    description: 'أحكام المحكمة وآثارها وتبعاتها والقرار المتوقع التالي.',
    overview: 'ملخص القرارات',
    total: 'إجمالي قرارات المحكمة',
    positive: 'قرارات لصالح القضية',
    neutral: 'قرارات محايدة',
    negative: 'نتائج غير مواتية',
    trajectory: 'مؤشر مسار القضية',
    positiveTrajectory: 'مسار إيجابي',
    neutralTrajectory: 'مسار محايد',
    negativeTrajectory: 'مسار سلبي',
    positiveHint: 'القرارات المسجلة تدعم الموقف الحالي للقضية.',
    neutralHint: 'القرارات المسجلة تشير إلى موقف متوازن للقضية.',
    negativeHint: 'القرارات المسجلة تستلزم إجراءً تصحيحيًا في القضية.',
    next: 'القرار المتوقع التالي',
    judge: 'القاضي',
    court: 'المحكمة',
    summary: 'ملخص القرار',
    implications: 'الآثار على الخطوات التالية',
    impact: {
      positive: 'نتيجة مواتية',
      negative: 'نتيجة غير مواتية',
      neutral: 'أثر محايد',
      mixed: 'أثر مختلط',
    },
  },
};

export function useDeepTabLabels() {
  const { locale } = useLocaleOrDefault();
  return locale === 'ar' ? AR : EN;
}
