package model

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

// Alert models a security alert generated by the detection engine or an analyst action.
type Alert struct {
	ID                  uuid.UUID          `json:"id" db:"id"`
	TenantID            uuid.UUID          `json:"tenant_id" db:"tenant_id"`
	Title               string             `json:"title" db:"title"`
	Description         string             `json:"description" db:"description"`
	Severity            Severity           `json:"severity" db:"severity"`
	Status              AlertStatus        `json:"status" db:"status"`
	Source              string             `json:"source" db:"source"`
	RuleID              *uuid.UUID         `json:"rule_id,omitempty" db:"rule_id"`
	AssetID             *uuid.UUID         `json:"asset_id,omitempty" db:"asset_id"`
	AssetIDs            []uuid.UUID        `json:"asset_ids" db:"asset_ids"`
	AssignedTo          *uuid.UUID         `json:"assigned_to,omitempty" db:"assigned_to"`
	AssignedAt          *time.Time         `json:"assigned_at,omitempty" db:"assigned_at"`
	EscalatedTo         *uuid.UUID         `json:"escalated_to,omitempty" db:"escalated_to"`
	EscalatedAt         *time.Time         `json:"escalated_at,omitempty" db:"escalated_at"`
	Explanation         AlertExplanation   `json:"explanation" db:"explanation"`
	ConfidenceScore     float64            `json:"confidence_score" db:"confidence_score"`
	MITRETacticID       *string            `json:"mitre_tactic_id,omitempty" db:"mitre_tactic_id"`
	MITRETacticName     *string            `json:"mitre_tactic_name,omitempty" db:"mitre_tactic_name"`
	MITRETechniqueID    *string            `json:"mitre_technique_id,omitempty" db:"mitre_technique_id"`
	MITRETechniqueName  *string            `json:"mitre_technique_name,omitempty" db:"mitre_technique_name"`
	EventCount          int                `json:"event_count" db:"event_count"`
	FirstEventAt        time.Time          `json:"first_event_at" db:"first_event_at"`
	LastEventAt         time.Time          `json:"last_event_at" db:"last_event_at"`
	ResolvedAt          *time.Time         `json:"resolved_at,omitempty" db:"resolved_at"`
	ResolutionNotes     *string            `json:"resolution_notes,omitempty" db:"resolution_notes"`
	FalsePositiveReason *string            `json:"false_positive_reason,omitempty" db:"false_positive_reason"`
	Tags                []string           `json:"tags" db:"tags"`
	Metadata            json.RawMessage    `json:"metadata" db:"metadata"`
	RuleName            *string            `json:"rule_name,omitempty" db:"rule_name"`
	RuleType            *DetectionRuleType `json:"rule_type,omitempty" db:"rule_type"`
	AssetName           *string            `json:"asset_name,omitempty" db:"asset_name"`
	AssetIPAddress      *string            `json:"asset_ip_address,omitempty" db:"asset_ip_address"`
	AssetHostname       *string            `json:"asset_hostname,omitempty" db:"asset_hostname"`
	AssetOS             *string            `json:"asset_os,omitempty" db:"asset_os"`
	AssetOwner          *string            `json:"asset_owner,omitempty" db:"asset_owner"`
	AssetCriticality    *Criticality       `json:"asset_criticality,omitempty" db:"asset_criticality"`
	AssignedToName      *string            `json:"assigned_to_name,omitempty" db:"assigned_to_name"`
	AssignedToEmail     *string            `json:"assigned_to_email,omitempty" db:"assigned_to_email"`
	EscalatedToName     *string            `json:"escalated_to_name,omitempty" db:"escalated_to_name"`
	EscalatedToEmail    *string            `json:"escalated_to_email,omitempty" db:"escalated_to_email"`
	CreatedAt           time.Time          `json:"created_at" db:"created_at"`
	UpdatedAt           time.Time          `json:"updated_at" db:"updated_at"`
	DeletedAt           *time.Time         `json:"-" db:"deleted_at"`
}

// AlertExplanation captures the explainable output analysts use to trust an alert.
type AlertExplanation struct {
	Summary                 string                 `json:"summary"`
	Reason                  string                 `json:"reason"`
	Evidence                []AlertEvidence        `json:"evidence"`
	MatchedConditions       []string               `json:"matched_conditions"`
	ConfidenceFactors       []ConfidenceFactor     `json:"confidence_factors"`
	RecommendedActions      []string               `json:"recommended_actions"`
	FalsePositiveIndicators []string               `json:"false_positive_indicators"`
	IndicatorMatches        []IndicatorEvidence    `json:"indicator_matches,omitempty"`
	Details                 map[string]interface{} `json:"details,omitempty"`
}

// AlertEvidence is a single structured fact supporting an alert.
type AlertEvidence struct {
	Label       string      `json:"label"`
	Field       string      `json:"field"`
	Value       interface{} `json:"value"`
	Description string      `json:"description"`
}

// IndicatorEvidence captures an IOC that reinforced the alert.
type IndicatorEvidence struct {
	Type       IndicatorType `json:"type"`
	Value      string        `json:"value"`
	Source     string        `json:"source"`
	Confidence float64       `json:"confidence"`
	Field      string        `json:"field"`
}

// ConfidenceFactor captures one additive or subtractive confidence contribution.
type ConfidenceFactor struct {
	Factor      string  `json:"factor"`
	Impact      float64 `json:"impact"`
	Description string  `json:"description"`
}

// AlertComment models an analyst or system comment on an alert.
type AlertComment struct {
	ID        uuid.UUID       `json:"id" db:"id"`
	TenantID  uuid.UUID       `json:"tenant_id" db:"tenant_id"`
	AlertID   uuid.UUID       `json:"alert_id" db:"alert_id"`
	UserID    uuid.UUID       `json:"user_id" db:"user_id"`
	UserName  string          `json:"user_name" db:"user_name"`
	UserEmail string          `json:"user_email" db:"user_email"`
	Content   string          `json:"content" db:"content"`
	IsSystem  bool            `json:"is_system" db:"is_system"`
	Metadata  json.RawMessage `json:"metadata" db:"metadata"`
	CreatedAt time.Time       `json:"created_at" db:"created_at"`
	UpdatedAt time.Time       `json:"updated_at" db:"updated_at"`
}

// AlertTimelineEntry models one immutable lifecycle event for an alert.
type AlertTimelineEntry struct {
	ID          uuid.UUID       `json:"id" db:"id"`
	TenantID    uuid.UUID       `json:"tenant_id" db:"tenant_id"`
	AlertID     uuid.UUID       `json:"alert_id" db:"alert_id"`
	Action      string          `json:"action" db:"action"`
	ActorID     *uuid.UUID      `json:"actor_id,omitempty" db:"actor_id"`
	ActorName   *string         `json:"actor_name,omitempty" db:"actor_name"`
	OldValue    *string         `json:"old_value,omitempty" db:"old_value"`
	NewValue    *string         `json:"new_value,omitempty" db:"new_value"`
	Description string          `json:"description" db:"description"`
	Metadata    json.RawMessage `json:"metadata" db:"metadata"`
	CreatedAt   time.Time       `json:"created_at" db:"created_at"`
}

// AlertStats holds aggregated alert metrics for dashboards.
type AlertStats struct {
	Total             int          `json:"total"`
	BySeverity        []NamedCount `json:"by_severity"`
	ByStatus          []NamedCount `json:"by_status"`
	ByRule            []NamedCount `json:"by_rule"`
	ByRuleType        []NamedCount `json:"by_rule_type"`
	ByTechnique       []NamedCount `json:"by_technique"`
	OpenCount         int          `json:"open_count"`
	ResolvedCount     int          `json:"resolved_count"`
	MTTRHours         float64      `json:"mttr_hours"`
	MTTAHours         float64      `json:"mtta_hours"`
	FalsePositiveRate float64      `json:"false_positive_rate"`
}

// NamedCount is a generic name/count pair used in aggregation responses.
type NamedCount struct {
	Name  string `json:"name"`
	Count int    `json:"count"`
}
