#!/usr/bin/env python3
"""Import the WatheeqTech translated visible-text inventory into a TS module.

The source Word document is owned by the translation workflow. This script keeps
the application-side artifact reproducible: run it again when a new translated
version arrives, then review the generated diff and run the i18n checks.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from docx import Document


DEFAULT_SOURCE = Path(
    "/Users/mac/clario360/docs/ClarioWatheeq/"
    "WatheeqTech Visible Text Inventory - Mr. Ben - TRANSLATED v22.docx"
)
DEFAULT_OUTPUT = Path(
    "/Users/mac/clario360/frontend/src/lib/i18n/"
    "watheeqtech-visible-text-v22.generated.ts"
)


def normalize(value: str) -> str:
    return " ".join((value or "").split()).strip()


def find_master_table(document: Document):
    for table in document.tables:
        if len(table.rows) < 2 or len(table.columns) < 3:
            continue
        header = [normalize(cell.text) for cell in table.rows[0].cells]
        if (
            "ID" in header[0]
            and "Source (English)" in header[1]
            and "Arabic Translation" in header[2]
        ):
            return table
    raise RuntimeError("Could not find the master bilingual string table.")


def load_translations(source: Path) -> tuple[dict[str, str], list[tuple[str, str, str]]]:
    document = Document(source)
    table = find_master_table(document)
    translations: dict[str, str] = {}
    conflicts: list[tuple[str, str, str]] = []

    for row in table.rows[1:]:
        cells = row.cells
        english = normalize(cells[1].text if len(cells) > 1 else "")
        arabic = normalize(cells[2].text if len(cells) > 2 else "")
        if not english or not arabic:
            continue

        existing = translations.get(english)
        if existing and existing != arabic:
            conflicts.append((english, existing, arabic))
            continue
        translations[english] = arabic

    return dict(sorted(translations.items(), key=lambda item: item[0].lower())), conflicts


def write_typescript(output: Path, translations: dict[str, str], source: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(translations, ensure_ascii=False, indent=2)
    output.write_text(
        "\n".join(
            [
                "/**",
                " * Generated by scripts/import_watheeq_translations.py.",
                f" * Source: {source}",
                " * Do not edit this file manually; update the Word translation",
                " * inventory and regenerate this module instead.",
                " */",
                "",
                "export const WATHEEQTECH_TRANSLATION_MEMORY_VERSION = 'v22' as const;",
                "",
                "export const WATHEEQTECH_VISIBLE_TEXT_TRANSLATIONS:",
                "  Readonly<Record<string, string>> =",
                f"{payload};",
                "",
                "export function translateWatheeqTechVisibleText(",
                "  source: string | null | undefined,",
                "): string | undefined {",
                "  if (!source) return undefined;",
                "  return WATHEEQTECH_VISIBLE_TEXT_TRANSLATIONS[source];",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    translations, conflicts = load_translations(args.source)
    write_typescript(args.output, translations, args.source)

    print(f"wrote {args.output}")
    print(f"translations={len(translations)} conflicts={len(conflicts)}")
    if conflicts:
        print("conflicting duplicate source strings were skipped:")
        for english, existing, incoming in conflicts[:20]:
            print(f"- {english!r}: existing={existing!r} incoming={incoming!r}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
