/**
 * Feature-local bilingual label catalog for the Matters surface.
 *
 * Follows the canonical lex bilingual contract (`../../_lib/lex-i18n.ts`,
 * mirroring `dr/_lib/dr-i18n.ts`): the label group is a
 * `LexBilingual<MatterLabels>` bundle holding two FULL, same-shaped copies —
 * English in `en` (equal to the pre-existing strings so English-asserting tests
 * stay green) and professional MSA in `ar`. Components never receive the bundle;
 * they read the resolved `MatterLabels` from {@link useMatterLabels} (React) or
 * {@link resolveMatterLabels} (non-React / tests, English default).
 *
 * Interpolation params and Western digits are preserved across both locales.
 * Legal glossary: عقد (contract) / بند (clause) / قضية (matter) / التزام
 * (obligation) / طرف (party) / حجز قانوني (legal hold).
 */

'use client';

import { useMemo } from 'react';
import { useLocaleOrDefault } from '@/components/providers/locale-provider';
import type { AppLocale } from '@/lib/i18n';
import { type LexBilingual, resolveLexBilingual } from '../../_lib/lex-i18n';

export interface MatterLabels {
  list: {
    title: string;
    description: string;
    newMatter: string;
    searchPlaceholder: string;
    emptyTitle: string;
    emptyDescription: string;
    columns: {
      matter: string;
      status: string;
      type: string;
      priority: string;
      owner: string;
      requester: string;
      linkedContracts: string;
      due: string;
      updated: string;
      actions: string;
    };
    rowActions: {
      view: string;
      edit: string;
      triage: string;
      changeStatus: string;
      delete: string;
    };
    unassigned: string;
    notCaptured: string;
    notLinked: string;
    noDueDate: string;
    linkedCount: (count: number) => string;
    titlePlaceholder: string;
  };
  filters: {
    status: string;
    type: string;
    priority: string;
    statusOptions: Record<string, string>;
    typeOptions: Record<string, string>;
    priorityOptions: Record<string, string>;
  };
  intake: {
    title: string;
    description: string;
    noRequester: string;
  };
  conflict: {
    title: string;
    description: string;
    matterTitle: string;
    counterparty: string;
    contract: string;
    context: string;
    contextPlaceholder: string;
    counterpartyPlaceholder: string;
    contractPlaceholder: string;
    run: string;
    inProgressTitle: string;
    inProgressDescription: string;
    emptyTitle: string;
    emptyDescription: string;
    resultTitle: string;
    checkedAt: string;
    conflicts: string;
    warnings: string;
    conflictSeverity: string;
    warningSeverity: string;
    potentialMatch: string;
    noIssues: string;
  };
  detail: {
    loadingTitle: string;
    loadingDescription: string;
    errorMessage: string;
    fallbackDescription: string;
    edit: string;
    triage: string;
    changeStatus: string;
    delete: string;
    metricStatus: string;
    metricPriority: string;
    metricType: string;
    metricLinkedContracts: string;
    overviewTitle: string;
    overviewDescription: string;
    metadata: {
      matterNumber: string;
      type: string;
      owner: string;
      requester: string;
      department: string;
      openedAt: string;
      dueDate: string;
      closedAt: string;
      tags: string;
      created: string;
      updated: string;
    };
    autoGenerated: string;
    notSet: string;
    noTags: string;
    descriptionTitle: string;
    descriptionEmpty: string;
    contractsTitle: string;
    contractsDescription: string;
    linkContract: string;
    contractsEmptyTitle: string;
    contractsEmptyDescription: string;
    unlink: string;
    relationship: string;
    obligationsTitle: string;
    obligationsDescription: string;
    obligationsEmptyTitle: string;
    obligationsEmptyDescription: string;
    obligationsError: string;
    viewObligation: string;
    noDueDate: string;
    unassigned: string;
  };
  form: {
    createTitle: string;
    editTitle: string;
    createDescription: string;
    editDescription: string;
    title: string;
    titlePlaceholder: string;
    matterNumber: string;
    matterNumberPlaceholder: string;
    type: string;
    status: string;
    priority: string;
    owner: string;
    ownerPlaceholder: string;
    requester: string;
    requesterUnassigned: string;
    department: string;
    departmentPlaceholder: string;
    dueDate: string;
    description: string;
    descriptionPlaceholder: string;
    tags: string;
    tagsPlaceholder: string;
    usersError: string;
    cancel: string;
    create: string;
    save: string;
    errors: {
      titleRequired: string;
      ownerRequired: string;
      ownerNameRequired: string;
    };
  };
  statusDialog: {
    title: string;
    description: string;
    nextStatus: string;
    selectStatus: string;
    cancel: string;
    submit: string;
  };
  view: {
    table: string;
    board: string;
    boardEmptyColumn: string;
    boardOwner: string;
    boardNoOwner: string;
    boardNoDueDate: string;
    transitionNotAllowed: (from: string, to: string) => string;
  };
  savedViews: {
    save: string;
    saved: string;
    empty: string;
  };
  filtersExtra: {
    dueDate: string;
  };
  bulk: {
    exportSelected: string;
    changeStatus: string;
    reassignOwner: string;
    changeStatusTitle: string;
    changeStatusDescription: (count: number) => string;
    reassignOwnerTitle: string;
    reassignOwnerDescription: (count: number) => string;
    owner: string;
    ownerPlaceholder: string;
    apply: string;
    cancel: string;
    statusUpdated: (count: number) => string;
    ownerReassigned: (count: number) => string;
    nothingApplicable: string;
    usersError: string;
  };
  triageDialog: {
    title: string;
    description: string;
    status: string;
    priority: string;
    owner: string;
    ownerPlaceholder: string;
    keepOwner: string;
    dueDate: string;
    notes: string;
    notesPlaceholder: string;
    cancel: string;
    submit: string;
  };
  linkDialog: {
    title: string;
    description: string;
    contract: string;
    contractPlaceholder: string;
    loadingContracts: string;
    relationship: string;
    cancel: string;
    submit: string;
    noContracts: string;
    loadError: string;
  };
  toast: {
    created: string;
    updated: string;
    statusUpdated: string;
    triaged: string;
    linked: string;
    unlinked: string;
    deleted: string;
  };
  confirm: {
    deleteTitle: string;
    deleteConfirm: string;
    deleteDescription: (title: string) => string;
    unlinkTitle: string;
    unlinkConfirm: string;
    unlinkDescription: (title: string) => string;
  };
}

export const matterLabelsBundle: LexBilingual<MatterLabels> = {
  en: {
    list: {
      title: 'Matters',
      description: 'Legal intake, triage, owner assignment, and contract-linked matter tracking.',
      newMatter: 'New Matter',
      searchPlaceholder: 'Search matters...',
      emptyTitle: 'No matters found',
      emptyDescription: 'No legal matters matched the current filters.',
      columns: {
        matter: 'Matter',
        status: 'Status',
        type: 'Type',
        priority: 'Priority',
        owner: 'Owner',
        requester: 'Requester',
        linkedContracts: 'Linked contracts',
        due: 'Due',
        updated: 'Updated',
        actions: 'Matter actions',
      },
      rowActions: {
        view: 'View detail',
        edit: 'Edit',
        triage: 'Triage',
        changeStatus: 'Change status',
        delete: 'Delete',
      },
      unassigned: 'Unassigned',
      notCaptured: 'Not captured',
      notLinked: 'Not linked',
      noDueDate: 'No due date',
      linkedCount: (count) => `${count} linked`,
      titlePlaceholder: 'Vendor termination dispute',
    },
    filters: {
      status: 'Status',
      type: 'Type',
      priority: 'Priority',
      statusOptions: {
        intake: 'Intake',
        open: 'Open',
        in_review: 'In Review',
        waiting_on_business: 'Waiting on Business',
        on_hold: 'On Hold',
        closed: 'Closed',
        cancelled: 'Cancelled',
      },
      typeOptions: {
        general: 'General',
        contract: 'Contract',
        litigation: 'Litigation',
        regulatory: 'Regulatory',
        employment: 'Employment',
        dispute: 'Dispute',
        advisory: 'Advisory',
        other: 'Other',
      },
      priorityOptions: {
        critical: 'Critical',
        high: 'High',
        medium: 'Medium',
        low: 'Low',
      },
    },
    intake: {
      title: 'Intake & Triage',
      description: 'Current matters grouped by the backend matter status lifecycle.',
      noRequester: 'No requester',
    },
    conflict: {
      title: 'Conflict Check',
      description: 'Bounded tenant-scoped screening before matter intake or contract linkage.',
      matterTitle: 'Matter title',
      counterparty: 'Counterparty',
      contract: 'Contract',
      context: 'Context',
      contextPlaceholder:
        'Counterparty, dispute facts, related contract, and requested legal position.',
      counterpartyPlaceholder: 'Acme LLC',
      contractPlaceholder: 'Acme MSA',
      run: 'Check Conflicts',
      inProgressTitle: 'Screening in progress',
      inProgressDescription: 'Checking current matters and linked contracts.',
      emptyTitle: 'No screening result',
      emptyDescription:
        'Run a check to compare the intake against tenant matters and contracts.',
      resultTitle: 'Screening result',
      checkedAt: 'Checked',
      conflicts: 'conflicts',
      warnings: 'warnings',
      conflictSeverity: 'Conflict',
      warningSeverity: 'Warning',
      potentialMatch: 'Potential match',
      noIssues: 'No conflicts or warnings found.',
    },
    detail: {
      loadingTitle: 'Matter',
      loadingDescription: 'Loading matter intake, ownership, and linked-contract context.',
      errorMessage: 'Failed to load matter details.',
      fallbackDescription: 'Legal matter intake and lifecycle detail.',
      edit: 'Edit',
      triage: 'Triage',
      changeStatus: 'Change Status',
      delete: 'Delete Matter',
      metricStatus: 'Status',
      metricPriority: 'Priority',
      metricType: 'Type',
      metricLinkedContracts: 'Linked contracts',
      overviewTitle: 'Matter Overview',
      overviewDescription: 'Core matter state, ownership, and intake context.',
      metadata: {
        matterNumber: 'Matter number',
        type: 'Type',
        owner: 'Owner',
        requester: 'Requester',
        department: 'Department',
        openedAt: 'Opened',
        dueDate: 'Due date',
        closedAt: 'Closed',
        tags: 'Tags',
        created: 'Created',
        updated: 'Updated',
      },
      autoGenerated: 'Auto-generated',
      notSet: 'Not set',
      noTags: 'No tags',
      descriptionTitle: 'Description',
      descriptionEmpty: 'No description was captured for this matter.',
      contractsTitle: 'Linked Contracts',
      contractsDescription: 'Contracts associated with this matter and their relationship.',
      linkContract: 'Link Contract',
      contractsEmptyTitle: 'No linked contracts',
      contractsEmptyDescription: 'Link a contract to associate it with this matter.',
      unlink: 'Unlink',
      relationship: 'Relationship',
      obligationsTitle: 'Matter Obligations',
      obligationsDescription: 'Obligations tied to this matter with owners and due dates.',
      obligationsEmptyTitle: 'No obligations',
      obligationsEmptyDescription: 'No obligations are linked to this matter yet.',
      obligationsError: 'Failed to load matter obligations.',
      viewObligation: 'View',
      noDueDate: 'No due date',
      unassigned: 'Unassigned',
    },
    form: {
      createTitle: 'Create Matter',
      editTitle: 'Edit Matter',
      createDescription: 'Register a new legal matter with ownership and intake context.',
      editDescription: 'Update matter metadata, ownership, type, and intake context.',
      title: 'Title',
      titlePlaceholder: 'Vendor termination dispute',
      matterNumber: 'Matter number',
      matterNumberPlaceholder: 'LEX-M-2026-001',
      type: 'Type',
      status: 'Status',
      priority: 'Priority',
      owner: 'Owner',
      ownerPlaceholder: 'Select owner',
      requester: 'Requester',
      requesterUnassigned: 'Not captured',
      department: 'Department',
      departmentPlaceholder: 'Procurement',
      dueDate: 'Due date',
      description: 'Description',
      descriptionPlaceholder:
        'Dispute facts, requested legal position, counterparties, and related contracts.',
      tags: 'Tags',
      tagsPlaceholder: 'dispute, vendor, urgent',
      usersError:
        'Unable to load the user directory. Matter save is disabled until owners can be resolved.',
      cancel: 'Cancel',
      create: 'Create matter',
      save: 'Save changes',
      errors: {
        titleRequired: 'Matter title is required.',
        ownerRequired: 'Select a matter owner.',
        ownerNameRequired: 'Owner name is required.',
      },
    },
    statusDialog: {
      title: 'Change Status',
      description: 'Move the matter to a valid lifecycle state.',
      nextStatus: 'Next status',
      selectStatus: 'Select status',
      cancel: 'Cancel',
      submit: 'Update Status',
    },
    view: {
      table: 'Table',
      board: 'Board',
      boardEmptyColumn: 'No matters',
      boardOwner: 'Owner',
      boardNoOwner: 'Unassigned',
      boardNoDueDate: 'No due date',
      transitionNotAllowed: (from, to) => `Cannot move a matter from "${from}" to "${to}".`,
    },
    savedViews: {
      save: 'Save current view',
      saved: 'Saved views',
      empty: 'No saved views yet',
    },
    filtersExtra: {
      dueDate: 'Due date',
    },
    bulk: {
      exportSelected: 'Export selected',
      changeStatus: 'Change status',
      reassignOwner: 'Reassign owner',
      changeStatusTitle: 'Bulk change status',
      changeStatusDescription: (count) =>
        `Move ${count} selected matter(s) to a new lifecycle state.`,
      reassignOwnerTitle: 'Bulk reassign owner',
      reassignOwnerDescription: (count) => `Reassign the owner for ${count} selected matter(s).`,
      owner: 'Owner',
      ownerPlaceholder: 'Select owner',
      apply: 'Apply',
      cancel: 'Cancel',
      statusUpdated: (count) => `${count} matter(s) updated.`,
      ownerReassigned: (count) => `${count} matter(s) reassigned.`,
      nothingApplicable: 'No selected matters could accept this change.',
      usersError: 'Unable to load the user directory.',
    },
    triageDialog: {
      title: 'Triage Matter',
      description: 'Set the working status, priority, owner, and target due date for this matter.',
      status: 'Status',
      priority: 'Priority',
      owner: 'Owner',
      ownerPlaceholder: 'Select owner',
      keepOwner: 'Keep current owner',
      dueDate: 'Due date',
      notes: 'Notes',
      notesPlaceholder: 'Triage rationale, escalation, or assignment context.',
      cancel: 'Cancel',
      submit: 'Apply Triage',
    },
    linkDialog: {
      title: 'Link Contract',
      description: 'Associate an existing contract with this matter.',
      contract: 'Contract',
      contractPlaceholder: 'Select contract',
      loadingContracts: 'Loading contracts...',
      relationship: 'Relationship',
      cancel: 'Cancel',
      submit: 'Link Contract',
      noContracts: 'No contracts are available to link.',
      loadError: 'Failed to load contracts.',
    },
    toast: {
      created: 'Matter created.',
      updated: 'Matter updated.',
      statusUpdated: 'Matter status updated.',
      triaged: 'Matter triaged.',
      linked: 'Contract linked.',
      unlinked: 'Contract unlinked.',
      deleted: 'Matter deleted.',
    },
    confirm: {
      deleteTitle: 'Delete matter',
      deleteConfirm: 'Delete',
      deleteDescription: (title) =>
        `Delete "${title}"? This removes the matter from the active register.`,
      unlinkTitle: 'Unlink contract',
      unlinkConfirm: 'Unlink',
      unlinkDescription: (title) => `Unlink "${title}" from this matter?`,
    },
  },
  ar: {
    list: {
      title: 'القضايا',
      description: 'استقبال القضايا القانونية وفرزها وإسناد المسؤولين وتتبّع القضايا المرتبطة بالعقود.',
      newMatter: 'قضية جديدة',
      searchPlaceholder: 'البحث في القضايا...',
      emptyTitle: 'لا توجد قضايا',
      emptyDescription: 'لا توجد قضايا قانونية مطابقة للمرشّحات الحالية.',
      columns: {
        matter: 'القضية',
        status: 'الحالة',
        type: 'النوع',
        priority: 'الأولوية',
        owner: 'المسؤول',
        requester: 'مقدّم الطلب',
        linkedContracts: 'العقود المرتبطة',
        due: 'الاستحقاق',
        updated: 'آخر تحديث',
        actions: 'إجراءات القضية',
      },
      rowActions: {
        view: 'عرض التفاصيل',
        edit: 'تعديل',
        triage: 'فرز',
        changeStatus: 'تغيير الحالة',
        delete: 'حذف',
      },
      unassigned: 'غير مُسند',
      notCaptured: 'غير مُسجّل',
      notLinked: 'غير مرتبط',
      noDueDate: 'بلا تاريخ استحقاق',
      linkedCount: (count) => `${count} عقد مرتبط`,
      titlePlaceholder: 'نزاع إنهاء تعاقد مع مورّد',
    },
    filters: {
      status: 'الحالة',
      type: 'النوع',
      priority: 'الأولوية',
      statusOptions: {
        intake: 'استقبال',
        open: 'مفتوحة',
        in_review: 'قيد المراجعة',
        waiting_on_business: 'بانتظار جهة العمل',
        on_hold: 'معلّقة',
        closed: 'مغلقة',
        cancelled: 'ملغاة',
      },
      typeOptions: {
        general: 'عام',
        contract: 'عقد',
        litigation: 'تقاضٍ',
        regulatory: 'تنظيمي',
        employment: 'عمالي',
        dispute: 'نزاع',
        advisory: 'استشاري',
        other: 'أخرى',
      },
      priorityOptions: {
        critical: 'حرجة',
        high: 'مرتفعة',
        medium: 'متوسطة',
        low: 'منخفضة',
      },
    },
    intake: {
      title: 'الاستقبال والفرز',
      description: 'القضايا الحالية مُجمّعة حسب دورة حياة حالة القضية في النظام.',
      noRequester: 'لا يوجد مقدّم طلب',
    },
    conflict: {
      title: 'فحص تعارض المصالح',
      description: 'فحص محدود ضمن نطاق المستأجر قبل استقبال القضية أو ربطها بعقد.',
      matterTitle: 'عنوان القضية',
      counterparty: 'الطرف المقابل',
      contract: 'العقد',
      context: 'السياق',
      contextPlaceholder:
        'الطرف المقابل ووقائع النزاع والعقد ذو الصلة والموقف القانوني المطلوب.',
      counterpartyPlaceholder: 'شركة أكمي',
      contractPlaceholder: 'اتفاقية خدمات أكمي الرئيسية',
      run: 'فحص التعارض',
      inProgressTitle: 'الفحص قيد التنفيذ',
      inProgressDescription: 'يجري فحص القضايا الحالية والعقود المرتبطة.',
      emptyTitle: 'لا توجد نتيجة فحص',
      emptyDescription:
        'شغّل الفحص لمقارنة المُدخل بقضايا المستأجر وعقوده.',
      resultTitle: 'نتيجة الفحص',
      checkedAt: 'تم الفحص',
      conflicts: 'تعارضات',
      warnings: 'تحذيرات',
      conflictSeverity: 'تعارض',
      warningSeverity: 'تحذير',
      potentialMatch: 'تطابق محتمل',
      noIssues: 'لم يُعثر على تعارضات أو تحذيرات.',
    },
    detail: {
      loadingTitle: 'القضية',
      loadingDescription: 'جارٍ تحميل بيانات استقبال القضية والمسؤول وسياق العقود المرتبطة.',
      errorMessage: 'تعذّر تحميل تفاصيل القضية.',
      fallbackDescription: 'تفاصيل استقبال القضية القانونية ودورة حياتها.',
      edit: 'تعديل',
      triage: 'فرز',
      changeStatus: 'تغيير الحالة',
      delete: 'حذف القضية',
      metricStatus: 'الحالة',
      metricPriority: 'الأولوية',
      metricType: 'النوع',
      metricLinkedContracts: 'العقود المرتبطة',
      overviewTitle: 'نظرة عامة على القضية',
      overviewDescription: 'الحالة الأساسية للقضية والمسؤول وسياق الاستقبال.',
      metadata: {
        matterNumber: 'رقم القضية',
        type: 'النوع',
        owner: 'المسؤول',
        requester: 'مقدّم الطلب',
        department: 'الإدارة',
        openedAt: 'تاريخ الفتح',
        dueDate: 'تاريخ الاستحقاق',
        closedAt: 'تاريخ الإغلاق',
        tags: 'الوسوم',
        created: 'تاريخ الإنشاء',
        updated: 'آخر تحديث',
      },
      autoGenerated: 'مُولّد تلقائيًا',
      notSet: 'غير محدد',
      noTags: 'لا توجد وسوم',
      descriptionTitle: 'الوصف',
      descriptionEmpty: 'لم يُسجَّل وصف لهذه القضية.',
      contractsTitle: 'العقود المرتبطة',
      contractsDescription: 'العقود المرتبطة بهذه القضية ونوع علاقتها بها.',
      linkContract: 'ربط عقد',
      contractsEmptyTitle: 'لا توجد عقود مرتبطة',
      contractsEmptyDescription: 'اربط عقدًا لربطه بهذه القضية.',
      unlink: 'إلغاء الربط',
      relationship: 'العلاقة',
      obligationsTitle: 'التزامات القضية',
      obligationsDescription: 'الالتزامات المرتبطة بهذه القضية مع المسؤولين وتواريخ الاستحقاق.',
      obligationsEmptyTitle: 'لا توجد التزامات',
      obligationsEmptyDescription: 'لا توجد التزامات مرتبطة بهذه القضية بعد.',
      obligationsError: 'تعذّر تحميل التزامات القضية.',
      viewObligation: 'عرض',
      noDueDate: 'بلا تاريخ استحقاق',
      unassigned: 'غير مُسند',
    },
    form: {
      createTitle: 'إنشاء قضية',
      editTitle: 'تعديل القضية',
      createDescription: 'تسجيل قضية قانونية جديدة مع تحديد المسؤول وسياق الاستقبال.',
      editDescription: 'تحديث بيانات القضية والمسؤول والنوع وسياق الاستقبال.',
      title: 'العنوان',
      titlePlaceholder: 'نزاع إنهاء تعاقد مع مورّد',
      matterNumber: 'رقم القضية',
      matterNumberPlaceholder: 'LEX-M-2026-001',
      type: 'النوع',
      status: 'الحالة',
      priority: 'الأولوية',
      owner: 'المسؤول',
      ownerPlaceholder: 'اختر المسؤول',
      requester: 'مقدّم الطلب',
      requesterUnassigned: 'غير مُسجّل',
      department: 'الإدارة',
      departmentPlaceholder: 'المشتريات',
      dueDate: 'تاريخ الاستحقاق',
      description: 'الوصف',
      descriptionPlaceholder:
        'وقائع النزاع والموقف القانوني المطلوب والأطراف المقابلة والعقود ذات الصلة.',
      tags: 'الوسوم',
      tagsPlaceholder: 'نزاع، مورّد، عاجل',
      usersError:
        'تعذّر تحميل دليل المستخدمين. حفظ القضية معطّل حتى يتعذّر تعيين المسؤولين.',
      cancel: 'إلغاء',
      create: 'إنشاء القضية',
      save: 'حفظ التغييرات',
      errors: {
        titleRequired: 'عنوان القضية مطلوب.',
        ownerRequired: 'اختر مسؤولًا للقضية.',
        ownerNameRequired: 'اسم المسؤول مطلوب.',
      },
    },
    statusDialog: {
      title: 'تغيير الحالة',
      description: 'نقل القضية إلى حالة صالحة ضمن دورة الحياة.',
      nextStatus: 'الحالة التالية',
      selectStatus: 'اختر الحالة',
      cancel: 'إلغاء',
      submit: 'تحديث الحالة',
    },
    view: {
      table: 'جدول',
      board: 'لوحة',
      boardEmptyColumn: 'لا توجد قضايا',
      boardOwner: 'المسؤول',
      boardNoOwner: 'غير مُسند',
      boardNoDueDate: 'بلا تاريخ استحقاق',
      transitionNotAllowed: (from, to) => `لا يمكن نقل القضية من "${from}" إلى "${to}".`,
    },
    savedViews: {
      save: 'حفظ العرض الحالي',
      saved: 'العروض المحفوظة',
      empty: 'لا توجد عروض محفوظة بعد',
    },
    filtersExtra: {
      dueDate: 'تاريخ الاستحقاق',
    },
    bulk: {
      exportSelected: 'تصدير المحدد',
      changeStatus: 'تغيير الحالة',
      reassignOwner: 'إعادة إسناد المسؤول',
      changeStatusTitle: 'تغيير الحالة بالجملة',
      changeStatusDescription: (count) => `نقل ${count} قضية محددة إلى حالة جديدة ضمن دورة الحياة.`,
      reassignOwnerTitle: 'إعادة إسناد المسؤول بالجملة',
      reassignOwnerDescription: (count) => `إعادة إسناد المسؤول لعدد ${count} قضية محددة.`,
      owner: 'المسؤول',
      ownerPlaceholder: 'اختر المسؤول',
      apply: 'تطبيق',
      cancel: 'إلغاء',
      statusUpdated: (count) => `تم تحديث ${count} قضية.`,
      ownerReassigned: (count) => `تمت إعادة إسناد ${count} قضية.`,
      nothingApplicable: 'لا توجد قضايا محددة يمكنها قبول هذا التغيير.',
      usersError: 'تعذّر تحميل دليل المستخدمين.',
    },
    triageDialog: {
      title: 'فرز القضية',
      description: 'حدّد حالة العمل والأولوية والمسؤول وتاريخ الاستحقاق المستهدف لهذه القضية.',
      status: 'الحالة',
      priority: 'الأولوية',
      owner: 'المسؤول',
      ownerPlaceholder: 'اختر المسؤول',
      keepOwner: 'الإبقاء على المسؤول الحالي',
      dueDate: 'تاريخ الاستحقاق',
      notes: 'ملاحظات',
      notesPlaceholder: 'مبررات الفرز أو التصعيد أو سياق الإسناد.',
      cancel: 'إلغاء',
      submit: 'تطبيق الفرز',
    },
    linkDialog: {
      title: 'ربط عقد',
      description: 'ربط عقد قائم بهذه القضية.',
      contract: 'العقد',
      contractPlaceholder: 'اختر العقد',
      loadingContracts: 'جارٍ تحميل العقود...',
      relationship: 'العلاقة',
      cancel: 'إلغاء',
      submit: 'ربط العقد',
      noContracts: 'لا توجد عقود متاحة للربط.',
      loadError: 'تعذّر تحميل العقود.',
    },
    toast: {
      created: 'تم إنشاء القضية.',
      updated: 'تم تحديث القضية.',
      statusUpdated: 'تم تحديث حالة القضية.',
      triaged: 'تم فرز القضية.',
      linked: 'تم ربط العقد.',
      unlinked: 'تم إلغاء ربط العقد.',
      deleted: 'تم حذف القضية.',
    },
    confirm: {
      deleteTitle: 'حذف القضية',
      deleteConfirm: 'حذف',
      deleteDescription: (title) =>
        `حذف "${title}"؟ سيؤدي ذلك إلى إزالة القضية من السجل النشط.`,
      unlinkTitle: 'إلغاء ربط العقد',
      unlinkConfirm: 'إلغاء الربط',
      unlinkDescription: (title) => `إلغاء ربط "${title}" من هذه القضية؟`,
    },
  },
};

/**
 * resolveMatterLabels is the pure resolver for non-React callers and tests;
 * defaults to English so isolated callers keep the English surface.
 */
export function resolveMatterLabels(locale: AppLocale = 'en'): MatterLabels {
  return resolveLexBilingual(matterLabelsBundle, locale);
}

/**
 * useMatterLabels is the thin memoized React hook the Matters pages/components
 * use to read the resolved {@link MatterLabels} for the active locale.
 */
export function useMatterLabels(): MatterLabels {
  const { locale } = useLocaleOrDefault();
  return useMemo(() => resolveMatterLabels(locale), [locale]);
}

export const MATTER_TYPE_OPTIONS = [
  'general',
  'contract',
  'litigation',
  'regulatory',
  'employment',
  'dispute',
  'advisory',
  'other',
] as const;

export const MATTER_STATUS_OPTIONS = [
  'intake',
  'open',
  'in_review',
  'waiting_on_business',
  'on_hold',
  'closed',
  'cancelled',
] as const;

export const MATTER_PRIORITY_OPTIONS = ['critical', 'high', 'medium', 'low'] as const;

/**
 * Valid forward status transitions for a matter. Mirrors the contract detail
 * STATUS_TRANSITIONS pattern: terminal states expose no further moves and the
 * current status is excluded from its own option set.
 */
export const MATTER_STATUS_TRANSITIONS: Record<string, readonly string[]> = {
  intake: ['open', 'in_review', 'on_hold', 'cancelled'],
  open: ['in_review', 'waiting_on_business', 'on_hold', 'closed', 'cancelled'],
  in_review: ['open', 'waiting_on_business', 'on_hold', 'closed', 'cancelled'],
  waiting_on_business: ['open', 'in_review', 'on_hold', 'closed', 'cancelled'],
  on_hold: ['open', 'in_review', 'closed', 'cancelled'],
  closed: ['open'],
  cancelled: ['open'],
};

export const MATTER_CONTRACT_RELATIONSHIPS = [
  'primary',
  'related',
  'amendment',
  'dispute',
  'reference',
] as const;

/** Display labels for the matter contract-relationship enum, keyed by token. */
export const matterRelationshipLabels: LexBilingual<Record<string, string>> = {
  en: {
    primary: 'Primary',
    related: 'Related',
    amendment: 'Amendment',
    dispute: 'Dispute',
    reference: 'Reference',
  },
  ar: {
    primary: 'أساسي',
    related: 'ذو صلة',
    amendment: 'تعديل',
    dispute: 'نزاع',
    reference: 'مرجعي',
  },
};

export function formatMatterToken(value: string): string {
  return value.replace(/_/g, ' ');
}
