import { BookOpen } from 'lucide-react';
import type { DocArticle } from './docs-content';

export type RouteGuide = {
  route: string;
  title: string;
  audience: string;
  purpose: string;
  actions: [string, string, string];
};

/**
 * Route-level WatheeqTech documentation inventory.
 *
 * This is intentionally explicit rather than inferred from filenames: each
 * shipped page must have a client-readable purpose, audience and operating
 * procedure. The coverage test compares these routes with the App Router.
 */
export const watheeqRouteGuides: RouteGuide[] = [
  { route: '/lex', title: 'Use the WatheeqTech home', audience: 'All WatheeqTech users', purpose: 'Open a persona-aware legal workspace and identify the highest-priority work available to your role.', actions: ['Read Needs attention and My work before the domain totals, noting any overdue, approval or SLA item surfaced for your persona.', 'Open the task from its card or use a domain tile to move into Service Desk, matters, contracts, litigation, knowledge or administration.', 'Complete the work in its source record, then return home and confirm the item and cross-domain KPI no longer show stale attention state.'] },
  { route: '/lex/admin', title: 'Use the Legal Administration hub', audience: 'Legal administrators and read-only auditors', purpose: 'Check administration health and open the exact catalog, policy, organization or governance area permitted for your role.', actions: ['Review the administration health dashboard for configuration gaps, then distinguish cards marked Manage from those marked View only.', 'Open the card that owns the setting; hidden cards are outside your effective permissions and read-only cards must not be treated as editable.', 'Complete and validate the change on the destination page, then return to the hub and confirm its health warning or card state reflects the result.'] },
  { route: '/lex/admin/attachment-policies', title: 'Configure attachment policies', audience: 'Legal and security administrators', purpose: 'Control attachment slots, required files, MIME types and size limits for WatheeqTech record types.', actions: ['Review policy precedence and the configured-slot KPI, then open the record type or service whose attachment behavior needs to change.', 'Create or edit required slots, accepted formats and byte limits, using the checklist to avoid an incomplete or shadowed policy.', 'Run the built-in evaluator with representative metadata for an allowed and rejected file and confirm the winning policy and validation reason.'] },
  { route: '/lex/admin/classifications', title: 'Govern the case-classification tree', audience: 'Case-classification administrators', purpose: 'Maintain the bilingual, hierarchical dispute taxonomy used by the case register.', actions: ['Search or quick-jump to the branch you need, then inspect its usage count, system status and child classifications before changing it.', 'Create, translate, reorder, merge or import classifications with the page’s cascade and impact warnings in view.', 'Run localization and usage checks, then confirm the revised tree appears on the case-classifications page without orphaned children.'] },
  { route: '/lex/admin/contract-approval-policies', title: 'Review contract-approval governance', audience: 'Contract governance administrators', purpose: 'Inspect contract approval policies, detect scope conflicts and open the governed editor or template catalog.', actions: ['Review active policies, their priority, version history and authority model before selecting one to change.', 'Run the conflict check to find overlapping scopes, then open the workflow editor or instantiate a governed template for the required change.', 'Return to the policy list and verify the expected version, status and audit entry after the change is published.'] },
  { route: '/lex/admin/contract-approval-policies/templates', title: 'Use approval-policy templates', audience: 'Legal governance administrators', purpose: 'Create consistent contract approval policies from governed templates.', actions: ['Choose the template matching the contract type and authority model.', 'Review inherited stages, roles, thresholds and decision requirements.', 'Create the policy, tailor its scope and validate it before activation.'] },
  { route: '/lex/admin/escalations', title: 'Audit SLA escalation coverage', audience: 'Legal operations and organization administrators', purpose: 'Find timing-order and recipient-coverage gaps across active SLA targets and the organization hierarchy.', actions: ['Review the active-target, ordered-ladder, recipient-coverage and open-gap indicators to identify the weakest escalation configuration.', 'Use the SLA timing matrix and L1–L3 chain preview to locate an out-of-order offset or missing inherited role holder.', 'Open SLA Targets to correct timing or Organization Registry to assign the missing role, then return and confirm the gap count falls.'] },
  { route: '/lex/admin/integrations', title: 'Operate the integration inventory', audience: 'Integration and security administrators', purpose: 'Triage connector health and open the correct setup, governance or reliability workflow.', actions: ['Filter the inventory by connector kind, status or health, and use the health history to identify the connector requiring attention.', 'Run a permitted connection test or enable/disable action, or open the connector for configuration, synchronization and failure details.', 'Refresh the inventory and confirm its status, health result and latest check reflect the operation you performed.'] },
  { route: '/lex/admin/integrations/new', title: 'Create an integration', audience: 'Integration administrators', purpose: 'Onboard an identity, HR, archive, email, signature, court or custom connector through its catalog-guided setup.', actions: ['Search the connector catalog, review maturity, KSA and government-gated notices, then choose the exact provider kind you intend to connect.', 'Complete Prerequisites and Credentials with protected values or use the no-code REST builder for a custom connector; never paste secrets into notes.', 'Run the connection test, enable the connector and complete its first synchronization, then confirm the wizard opens the new connector detail page.'] },
  { route: '/lex/admin/integrations/[id]', title: 'Manage an integration', audience: 'Integration administrators', purpose: 'Inspect and operate one configured WatheeqTech connector.', actions: ['Review configuration, honest health grade and recent synchronization state.', 'Run the permitted connection test, sync or credential-rotation action.', 'Use events, logs, conflicts and dead-letter views to resolve failures.'] },
  { route: '/lex/admin/integrations/[id]/conflicts', title: 'Resolve integration conflicts', audience: 'Integration administrators and data owners', purpose: 'Decide how one connector should handle records that automatic reconciliation could not settle.', actions: ['Filter Open conflicts and compare the WatheeqTech value, provider value and connector-suggested resolution for each field.', 'Choose Merge, Override or Ignore for one conflict, or apply a carefully scoped bulk resolution when the same decision is valid for every selected row.', 'Confirm the conflict status changes to Resolved and review the next synchronization run to ensure the same mapping problem does not recur.'] },
  { route: '/lex/admin/integrations/[id]/dlq', title: 'Replay an integration dead letter', audience: 'Integration administrators', purpose: 'Inspect and safely retry failed events for a specific connector.', actions: ['Review the failure reason, payload metadata and retry history without exposing secrets.', 'Correct configuration or source data before retrying.', 'Replay the item and verify the resulting event or retain it with an operator note.'] },
  { route: '/lex/admin/integrations/[id]/events', title: 'Inspect integration events', audience: 'Integration administrators and support', purpose: 'Trace inbound and outbound events for one connector.', actions: ['Filter by event type, outcome, correlation identifier or time.', 'Open the event and review sanitized headers, timing and processing state.', 'Follow its correlation data into logs or dead-letter handling when required.'] },
  { route: '/lex/admin/integrations/[id]/logs', title: 'Diagnose connector synchronization', audience: 'Integration administrators and support', purpose: 'Review one connector’s sync-run ledger, reconciliation results and session connection-test receipts.', actions: ['Read total, succeeded, partial, failed and last-run indicators, then open the relevant sync-run row instead of assuming an unavailable ledger means zero runs.', 'Inspect reconciliation differences and connection-test receipts; use Sync preview to review the delta before a permitted operator confirms a new run.', 'Refresh the ledger and verify the resulting run status and reconciliation counts, retaining its identifier when escalation to provider support is required.'] },
  { route: '/lex/admin/integrations/dlq', title: 'Manage the integration dead-letter queue', audience: 'Integration administrators', purpose: 'Triage failed integration events across all WatheeqTech connectors.', actions: ['Filter by connector, failure class, age and retry status.', 'Assign or resolve the underlying credential, mapping, provider or data issue.', 'Replay eligible items in bounded batches and verify downstream results.'] },
  { route: '/lex/admin/integrations/events', title: 'Search all integration events', audience: 'Integration administrators and auditors', purpose: 'Trace connector events across the tenant from a single event inspector.', actions: ['Search by provider, event type, record identifier or correlation ID.', 'Inspect the sanitized event envelope and processing outcome.', 'Open the owning integration for configuration or retry actions.'] },
  { route: '/lex/admin/integrations/observability', title: 'Monitor integration health', audience: 'Integration administrators and SRE teams', purpose: 'Track connector reliability, latency, failure rates and backlog.', actions: ['Review health distribution and identify degraded or unavailable connectors.', 'Inspect sync latency, failures, retries, dead letters and circuit state.', 'Open the affected connector and follow its remediation workflow.'] },
  { route: '/lex/admin/integrations/pending-changes', title: 'Approve integration changes', audience: 'Integration checker or security approver', purpose: 'Review maker-checker changes before they affect live connectors.', actions: ['Open the pending change and compare old and proposed sanitized configuration.', 'Confirm the maker is different from the checker and assess data-egress impact.', 'Approve or reject with notes, then verify the resulting connector state.'] },
  { route: '/lex/admin/legal-holds', title: 'Apply or release a legal hold', audience: 'Authorized legal administrators and preservation owners', purpose: 'Freeze a contract, matter, document or consultation while a preservation duty remains in force.', actions: ['Search active and released holds first, then select Apply legal hold and choose the exact record to preserve.', 'Record the preservation reason, reference, custodian and notes; apply the hold and confirm the record is protected from destructive lifecycle actions.', 'When counsel confirms the duty has ended, select Release hold, record the release note and verify the hold status changes to Released.'] },
  { route: '/lex/admin/org-entities', title: 'Manage the organization registry', audience: 'Legal and identity administrators', purpose: 'Maintain the hierarchy used for routing, responsibility and scoped access.', actions: ['Review the organization tree or download an import template.', 'Create, edit or dry-run import entities, managers, roles and memberships.', 'Validate the hierarchy and apply changes atomically.'] },
  { route: '/lex/admin/org-entities/[id]', title: 'Manage an organization entity', audience: 'Legal and identity administrators', purpose: 'Configure one company, business unit, department, section or shared service unit.', actions: ['Review the entity path, active state and platform mapping.', 'Assign responsibility roles, managers and employee memberships.', 'Save and verify routing, escalation and visibility for the entity.'] },
  { route: '/lex/admin/request-approval-policies', title: 'Manage request approval policies', audience: 'Legal governance administrators', purpose: 'Govern requester and provider approvals for Legal Service Desk submissions.', actions: ['Review policy priority and scope for overlapping service and request-type matches.', 'Configure stage, approvers, quorum, authority evidence and thresholds.', 'Test recommendation and activate only after the expected policy wins.'] },
  { route: '/lex/admin/request-approval-policies/templates', title: 'Use request-policy templates', audience: 'Legal governance administrators', purpose: 'Create consistent request approval policies from reusable patterns.', actions: ['Choose a template matching the requester or provider decision model.', 'Review its approver roles, sequence, quorum and evidence requirements.', 'Create, scope and test the resulting policy against a real service.'] },
  { route: '/lex/admin/role-matrix', title: 'Audit the WatheeqTech role matrix', audience: 'Security, audit and legal administrators', purpose: 'Compare the 14 seeded legal roles with live tenant permissions and separation-of-duties principles without granting access.', actions: ['Use the legend to distinguish allowed, conditional and unavailable capabilities, then locate the role and capability domain under review.', 'Inspect any seeded-versus-live drift indicator and compare the effective permission pattern with the stated least-privilege and separation-of-duties principles.', 'Record the discrepancy and make any role assignment or permission change in the owning identity administration workflow; this page is read-only.'] },
  { route: '/lex/admin/service-catalog', title: 'Manage the legal service catalog', audience: 'Legal administrators', purpose: 'Create and operate the bilingual services available through legal intake.', actions: ['Review active, inactive and restricted services.', 'Create or open a service to configure identity, eligibility, approvals and channel.', 'Validate availability with representative requester personas.'] },
  { route: '/lex/admin/service-catalog/[id]', title: 'Configure a legal service', audience: 'Legal administrators', purpose: 'Set one service’s bilingual details, requirements, eligibility and governance.', actions: ['Review the stable code, request type, bilingual content and owning team.', 'Configure eligibility, attachments, priority behavior, approvals and SLA targets.', 'Activate and submit a test request through each intended channel.'] },
  { route: '/lex/admin/sla-targets', title: 'Configure SLA targets', audience: 'Legal administrators', purpose: 'Define acknowledgement, turnaround and L1–L3 post-breach escalation timing for legal services and priorities.', actions: ['Choose the service and priority scope, then check existing rows so a new target does not create ambiguous SLA coverage.', 'Set acknowledgement and turnaround working time plus strictly ordered L1, L2 and L3 escalation offsets; use the page preview before saving.', 'Monitor a representative clock and confirm its due and escalation timestamps honor the selected service target and active working calendar.'] },
  { route: '/lex/admin/working-calendars', title: 'Manage SLA working calendars', audience: 'Legal administrators', purpose: 'Define working-hour profiles, default-calendar behavior, holidays and Ramadan periods used by legal SLA clocks.', actions: ['Review the calendar list and resolve any warning that the tenant has zero or multiple defaults before changing working time.', 'Create or edit the calendar’s timezone, working-hour profile and Ramadan dates, then maintain holiday exceptions from its row action.', 'Set exactly one default calendar and verify its working hours and holiday count in the list before relying on new SLA due dates.'] },
  { route: '/lex/analytics', title: 'Interpret legal-operations workload and velocity', audience: 'Legal leaders and operations analysts', purpose: 'Assess active-matter workload, officer allocation, throughput and cycle time from the current legal portfolio.', actions: ['Read the KPI strip first to establish active matters, recent closures, average close time, settlement cycle and weekly throughput.', 'Use the officer-by-practice-area heatmap to find workload concentration, then compare opened-versus-closed and days-in-phase velocity charts.', 'Refresh after operational data changes and take the identified staffing or process action in the owning matter or team workflow.'] },
  { route: '/lex/analytics/risk', title: 'Interpret portfolio risk and value exposure', audience: 'Legal leaders, contract owners and risk teams', purpose: 'Assess contract value at risk, risk-score coverage, matter urgency, obligation maturity and the renewal cliff.', actions: ['Read portfolio value, active value, value at risk, high-risk share, 90-day expiries and average risk score as one exposure snapshot.', 'Compare the risk distribution, matter-priority and obligation-maturity visuals, then identify the peak month on the 12-month renewal cliff.', 'Refresh after source records change and open Contracts, Matters or Obligations to assign mitigation against the exposure you identified.'] },
  { route: '/lex/approvals/escalations', title: 'Manage approval escalations', audience: 'Approval managers and legal operations leaders', purpose: 'Triage overdue or at-risk approval work and coordinate the next governed escalation action.', actions: ['Filter the escalation queue by level, age, owner, service and SLA state before selecting the highest-impact unresolved item.', 'Open the source request and confirm its evidence, current assignee and escalation history before changing ownership or level.', 'Record the permitted escalation action and verify the queue, source timeline and next responsible actor all reflect the result.'] },
  { route: '/lex/approvals/requests', title: 'Process the legal approval queue', audience: 'Authorized request approvers and legal managers', purpose: 'Review pending Legal Service Desk decisions and open the source request with its governing approval context.', actions: ['Filter the queue by stage, service, priority, requester and age, then start with overdue or SLA-risk decisions.', 'Open the request and inspect its details, attachments, approval task, authority and lifecycle evidence before deciding.', 'Approve, return or reject with required comments and confirm the task leaves the queue or advances to the next approver.'] },
  { route: '/lex/approvals/requests/[id]', title: 'Decide a legal service request', audience: 'Assigned legal request approvers and managers', purpose: 'Make a reasoned approval, revision or rejection decision on one Legal Service Desk request.', actions: ['Review the request details, requester, department, priority, SLA, description, attachments and completed lifecycle checks.', 'Enter decision comments and choose only the action permitted by the active approval task and your delegated authority.', 'Confirm the lifecycle records the decision, or transfer the pending task to another eligible manager when policy allows it.'] },
  { route: '/lex/audit', title: 'Inspect the Watheeq audit ledger', audience: 'Authorized legal auditors, administrators and managers', purpose: 'Search the tenant-scoped immutable Watheeq activity ledger and reconstruct the chronology for a selected legal record.', actions: ['Search or filter the audit viewer by actor, action, resource and severity, then select the event that identifies the target record.', 'Use Activity Timeline to load the target record’s complete filtered history and compare actors, timestamps, hashes and before-and-after values.', 'Export only the filtered ledger scope needed for review and make any administrative note through an audited source workflow rather than altering the ledger.'] },
  { route: '/lex/calendar', title: 'Use the legal calendar', audience: 'Legal professionals and managers', purpose: 'See hearings, deadlines, obligations, renewals and legal tasks in one calendar.', actions: ['Choose month, week or agenda view and apply domain filters.', 'Open an event to verify its source record, owner and due-date basis.', 'Update the source record rather than creating conflicting duplicate dates.'] },
  { route: '/lex/case-timeline', title: 'Maintain a matter delay timeline', audience: 'Matter owners, dispute teams and supervisors', purpose: 'Track one matter’s estimated duration, external holds and delay events in a deep-linkable timeline workspace.', actions: ['Choose a matter, use a recently viewed shortcut when available, or enable On hold only to narrow the picker.', 'Review estimated duration, current hold state and recorded delay events; add or correct timeline data only when your case-edit permission allows it.', 'Confirm the matterId remains in the page URL and that the timeline totals and open-delay state reflect the saved change.'] },
  { route: '/lex/case-timeline/portfolio', title: 'Triage matter holds and delays', audience: 'Heads of legal, matter supervisors and legal operations', purpose: 'Prioritize matters that are on hold, accumulating open-delay days, overdue or due this week.', actions: ['Choose On hold, Open delays or All; start with the default worst-delay ordering and review the KPI strip for the visible page.', 'Open the highest-risk matter row to inspect its duration, hold source, open-delay days and next deadline in the single-matter timeline.', 'Assign the operational follow-up in the owning matter workflow, then return to the portfolio and confirm the hold or delay indicator updates.'] },
  { route: '/lex/cases', title: 'Manage the case register', audience: 'Litigation teams', purpose: 'Search, create and manage plaintiff and defendant case records.', actions: ['Filter the register by posture, court, status, owner, risk or next date.', 'Create a case from authorized intake or open the selected record.', 'Keep ownership, exposure and next procedural milestone current.'] },
  { route: '/lex/cases/[id]', title: 'Operate a legal case', audience: 'Assigned lawyers and supervisors', purpose: 'Manage parties, pleadings, hearings, evidence, experts, judgment and case closure.', actions: ['Review posture, classification, strength assessment, parties and legal strategy.', 'Maintain filings, hearings, experts, tasks, documents and preservation controls.', 'Record judgment, objection and closure through governed state transitions.'] },
  { route: '/lex/cases/classifications', title: 'Maintain case classifications', audience: 'Litigation taxonomy administrators', purpose: 'Create, edit and retire the dispute classifications available to case records.', actions: ['Review the classification list and cascade for the branch you intend to change, checking whether existing cases already use it.', 'Create the bilingual classification or edit its parent and labels; delete only when the page’s dependency checks permit it.', 'Return to the case register and verify the intended classification can be selected without breaking existing case categorization.'] },
  { route: '/lex/cases/control', title: 'Monitor cases and investigations', audience: 'Litigation managers and investigation supervisors', purpose: 'Review the combined case and investigation portfolio, attention signals, workload and operational control state.', actions: ['Read the combined KPIs and attention queue, then compare case and investigation volume, ownership and deadline risk.', 'Open the control view or source record that explains an overdue, unassigned, high-risk or approval-blocked item.', 'Assign the operational follow-up in its owning workflow and return to confirm the control panel reflects the source change.'] },
  { route: '/lex/cases/control/assignment', title: 'Assign case and investigation work', audience: 'Litigation managers and investigation supervisors', purpose: 'Allocate unassigned or overloaded case and investigation records using visible workload and responsibility context.', actions: ['Filter the assignment queue by domain, team, priority and deadline, then review current ownership and workload indicators.', 'Choose an eligible assignee whose role and capacity match the record, and record the reason when reassignment changes ownership.', 'Confirm the source record, workload summary and control queue all show the new owner without leaving a duplicate assignment.'] },
  { route: '/lex/cases/control/litigation', title: 'Review the litigation control view', audience: 'Litigation managers and supervising counsel', purpose: 'Focus the combined control panel on case posture, hearings, filings, judgments and procedural deadline risk.', actions: ['Review plaintiff and defendant posture, court stage, next hearing, filing deadline and judgment signals for the visible portfolio.', 'Open the highest-risk case and inspect its pleadings, hearing record, evidence and responsible lawyer before intervening.', 'Record the procedural update in the source case and return to confirm the litigation control indicators and ordering change.'] },
  { route: '/lex/cases/control/overview', title: 'Use the cases control overview', audience: 'Heads of legal, litigation managers and investigators', purpose: 'Read the executive cases and investigations overview before drilling into assignment or litigation-specific control views.', actions: ['Compare portfolio totals, risk, deadlines, assignments and lifecycle distribution across cases and investigations.', 'Use the attention list to identify the record whose delay, SLA, approval or ownership state requires management action.', 'Open the relevant assignment, litigation or source-record workflow and verify the overview updates after the action completes.'] },
  { route: '/lex/clause-library', title: 'Use the clause library', audience: 'Contract lawyers and knowledge managers', purpose: 'Find, create and govern reusable bilingual contract clauses.', actions: ['Search by text, category, risk, language or governance state.', 'Insert an approved clause or create a draft entry when authorized.', 'Route changes through governance and retain version history.'] },
  { route: '/lex/compliance', title: 'Run contract compliance checks', audience: 'Compliance owners and contract teams', purpose: 'Maintain compliance rules, evaluate the tenant contract portfolio and resolve resulting alerts.', actions: ['Review compliance score, severity and status breakdowns plus the last-run receipt, then create or correct a rule before relying on its findings.', 'Run Check compliance for the permitted tenant portfolio and inspect the run summary showing evaluated contracts, generated alerts and resulting score.', 'Open or bulk-select alerts, move them through acknowledged, investigating, resolved or dismissed with notes, and export only the governed scope you reviewed.'] },
  { route: '/lex/compliance/alerts/[id]', title: 'Resolve a compliance alert', audience: 'Compliance owners and contract lawyers', purpose: 'Investigate one failed legal compliance rule and record its resolution.', actions: ['Review the rule, affected contract, evidence and severity.', 'Confirm the finding, assign an owner and document remediation or acceptance.', 'Update status with notes and verify the compliance score reflects the outcome.'] },
  { route: '/lex/consultations', title: 'Manage legal consultations', audience: 'Legal advisory teams', purpose: 'Triage, assign and deliver governed legal advice.', actions: ['Filter consultations by status, topic, priority, requester or assignee.', 'Open new work and classify conflicts, practice area and service level.', 'Track drafting, review, delivery and archive state.'] },
  { route: '/lex/consultations/[id]', title: 'Deliver a legal consultation', audience: 'Assigned legal professionals and reviewers', purpose: 'Research, draft, review and deliver advice for a specific consultation.', actions: ['Confirm the question, facts, assumptions, conflicts and requested deadline.', 'Link authority and draft analysis, options, risk and recommendation.', 'Complete review, deliver the approved advice and archive the record.'] },
  { route: '/lex/consultations/[id]/response', title: 'Prepare a consultation response', audience: 'Assigned legal advisers and consultation reviewers', purpose: 'Draft, review and approve the formal legal response associated with one routed consultation.', actions: ['Review the original question, requester context, attachments, deadline and any existing response before editing the advice.', 'Draft the opinion with legal basis, analysis, recommendation, risk and source references, then save it through the governed response action.', 'Approve, request revision or archive only when the response state and your permission make that lifecycle decision available.'] },
  { route: '/lex/consultations/archive', title: 'Search the consultation archive', audience: 'Legal advisers, managers and authorized auditors', purpose: 'Search completed and historical consultation records without mixing them into the active advisory queue.', actions: ['Search by reference, requester or subject and refine the archive by adviser, department, type, status and relevant dates.', 'Open a result to review the original request, approved response, linked evidence and immutable lifecycle history.', 'Export the filtered archive when permitted and retain the applied scope with any downstream review or audit evidence.'] },
  { route: '/lex/consultations/new', title: 'Request a new legal consultation', audience: 'Authorized business requesters and legal operations users', purpose: 'Submit a complete legal question with urgency, context and supporting documents to the consultation workflow.', actions: ['Choose the consultation type, identify the relevant department and enter a concise subject plus the detailed facts and questions.', 'Select normal or urgent handling, provide the required urgency justification and stage only supported supporting documents.', 'Review the requester and SLA guidance, submit the consultation and confirm the created detail page contains each attached record.'] },
  { route: '/lex/contracts', title: 'Manage the contract register', audience: 'Contract and procurement legal teams', purpose: 'Search, create and operate contracts across their lifecycle.', actions: ['Filter by status, category, owner, risk, counterparty, expiry or renewal.', 'Create a contract or open an existing record requiring action.', 'Use portfolio warnings to prioritize review, signature and obligation work.'] },
  { route: '/lex/contracts/[id]', title: 'Operate a contract lifecycle', audience: 'Contract lawyers, reviewers and approvers', purpose: 'Move one contract through document control, analysis, review, approval, signature, obligation and renewal work.', actions: ['Confirm contract metadata and classification, then identify or upload the current governed file version before running analysis or review.', 'Work through Review desk, Clauses and Compliance findings, resolve redlines and deviations, and complete the recommended approval tasks with evidence.', 'Create the signature envelope only from the approved final version, then monitor custody, obligations, expiry and renewal before archiving the contract.'] },
  { route: '/lex/contracts/[id]/approval', title: 'Approve a governed contract', audience: 'Assigned contract approvers and legal managers', purpose: 'Review contract readiness, authority, compliance and supporting evidence before recording a governed approval decision.', actions: ['Confirm the contract version, commercial summary, risk findings, deviations, compliance state and approval task before deciding.', 'Review delegated authority and required evidence, then approve, return or reject with a reason that supports the decision.', 'Verify the workflow, contract lifecycle and next responsible actor update consistently and that the decision appears in audit history.'] },
  { route: '/lex/contracts/[id]/draft', title: 'Draft and review contract language', audience: 'Contract authors, reviewers and knowledge managers', purpose: 'Edit governed contract language with version, clause, collaboration and review controls tied to the contract record.', actions: ['Confirm the contract, active version, edit mode and lock state before changing text or inserting governed clauses.', 'Draft or review language, resolve comments and clause deviations, and create a version snapshot at a meaningful checkpoint.', 'Run preflight checks and hand the version to negotiation or approval only when blockers and unresolved changes are visible.'] },
  { route: '/lex/contracts/[id]/negotiation', title: 'Manage contract negotiation', audience: 'Contract lawyers, reviewers and negotiation owners', purpose: 'Track counterpart discussion, redlines, positions and version handoffs within the governed contract negotiation workspace.', actions: ['Confirm the negotiation parties, active draft, internal position and outstanding issues before sending or recording a message.', 'Record each material proposal, response and attachment against the correct version and preserve internal-only guidance separately.', 'Close or advance negotiation only after accepted language is captured in the governed draft and the next review owner is clear.'] },
  { route: '/lex/contracts/[id]/signature', title: 'Prepare contract signature', audience: 'Contract owners, signature coordinators and approvers', purpose: 'Validate signature readiness and create or monitor the governed envelope for an approved contract version.', actions: ['Confirm the final approved version, signatories, signing order, authority and unresolved compliance blockers before creating an envelope.', 'Send through the configured provider and monitor recipient, provider-event and custody evidence without bypassing approval state.', 'After completion, verify the signed file, hashes, timestamps and envelope status are attached to the correct contract version.'] },
  { route: '/lex/contracts/archived', title: 'Find archived contracts', audience: 'Contract teams and authorized auditors', purpose: 'Search historical contracts without mixing them into active work.', actions: ['Filter archived records by party, category, owner, date or identifier.', 'Open the contract to review its final version, outcome and audit history.', 'Restore only through an authorized lifecycle action when policy permits.'] },
  { route: '/lex/contracts/compliance', title: 'Review contract compliance portfolio', audience: 'Contract managers, compliance owners and legal reviewers', purpose: 'Monitor contract-level compliance findings, readiness and remediation across the governed portfolio.', actions: ['Filter contracts by compliance state, risk, owner, category and review age, then start with unresolved high-impact findings.', 'Open the contract or finding to inspect the governing rule, evidence, affected language and current remediation owner.', 'Resolve or accept the finding through its source workflow and confirm portfolio indicators update without hiding unresolved evidence.'] },
  { route: '/lex/contracts/control', title: 'Monitor contracts and consultations', audience: 'Contracts managers and legal advisory leaders', purpose: 'Review combined contract and consultation workload, SLA signals, assignments and portfolio attention items.', actions: ['Compare contract and consultation KPIs, then inspect the attention queue for overdue, unassigned, approval or SLA-risk work.', 'Open the relevant record or assignment view and review its owner, status, deadline and evidence before taking action.', 'Complete the change in the source workflow and return to verify the combined control panel no longer shows stale state.'] },
  { route: '/lex/contracts/control/assignment', title: 'Assign contract and consultation work', audience: 'Contracts managers and consultation supervisors', purpose: 'Allocate unassigned contract and consultation records using role eligibility, current workload and deadline context.', actions: ['Filter by domain, team, priority and deadline, then compare the current workload of eligible legal professionals.', 'Assign or reassign the selected record with the operational reason and preserve any required separation-of-duties constraint.', 'Verify ownership changes on the source record and that the assignment queue and workload totals update consistently.'] },
  { route: '/lex/contracts/new', title: 'Create a governed contract record', audience: 'Authorized contract requesters and legal authors', purpose: 'Start a contract lifecycle with complete parties, ownership, dates, value, classification and supporting information.', actions: ['Choose the contract type and enter the bilingual identity, parties, business owner, department and responsible legal reviewer.', 'Record value, currency, effective dates, expiry, renewal and risk context, then attach only the correct source documents.', 'Review the new record before creation and confirm its detail page shows the expected metadata and next lifecycle action.'] },
  { route: '/lex/documents', title: 'Manage the legal document repository', audience: 'All authorized legal users', purpose: 'Search, classify, version and link legal documents.', actions: ['Search by title, full text, type, language, classification or linked record.', 'Create or upload the document with the correct confidentiality and retention.', 'Use version history and links instead of duplicating the file.'] },
  { route: '/lex/documents/editor', title: 'Use the document collaboration workspace', audience: 'Authorized legal authors, reviewers and approvers', purpose: 'Review document health, locks, versions, comments, clauses, approvals and signature readiness in one workspace.', actions: ['Open the route with the intended documentId and confirm the displayed file, current version, mode, lock holder and autosave/recovery state.', 'Choose View, Review or Edit as permitted, then use comments, clause recommendations, comparison and approval panels to complete the assigned work.', 'Use the visible save or snapshot control and confirm version, pending-change, blocker and signature-readiness indicators before handing the document onward.'] },
  { route: '/lex/drafting', title: 'Run a governed drafting task', audience: 'Legal authors and reviewers', purpose: 'Work across clause, contract, rewrite, fallback, translation, summary, glossary, RFP, obligation-QA and assembly drafting tasks.', actions: ['Choose the exact task in the command bar and confirm the workspace, project and active version shown in the route and workspace cockpit.', 'Provide permitted source material and task instructions, run the task, then review the generated language, risks, terms and task-specific quality checks.', 'Save or restore the accepted workspace version and use the handoff control to continue in the next drafting task without losing project context.'] },
  { route: '/lex/entities', title: 'Analyze the Entity 360 register', audience: 'Legal leaders, dispute teams and contract teams', purpose: 'Review a read-only counterparty register derived from contracts, case parties and settlements.', actions: ['Search the normalized organization name and use the KPI strip to understand total exposure, settlement exposure, recovery, open cases and active contracts.', 'Open the matching Entity 360 row and compare the organization’s exposure and connected legal-work counts.', 'Correct inaccurate names, parties or values in the owning contract, case or settlement record; the Entity 360 register itself is derived and read-only.'] },
  { route: '/lex/entities/[id]', title: 'Investigate an Entity 360 profile', audience: 'Assigned lawyers, dispute teams and contract owners', purpose: 'Assess one counterparty’s aggregate exposure, recovery posture and connected contracts, cases and settlements.', actions: ['Confirm the counterparty identity and read the profile KPIs and exposure breakdown before drawing a conclusion.', 'Review the Contracts, Cases, Settlements and Activity tabs, then open the source record that explains the exposure or posture.', 'Make corrections or mitigation assignments in that source record and return to confirm the derived profile reflects the updated portfolio data.'] },
  { route: '/lex/inbox', title: 'Decide work awaiting you', audience: 'Legal approvers and assigned decision makers', purpose: 'Process a cross-domain queue of settlement, governance, workflow, contract and Service Desk approvals.', actions: ['Review Pending, Due today and Overdue indicators, then start with the oldest overdue item in its domain group.', 'Use the inline decision action when offered; otherwise open the linked source record and inspect its evidence, authority and current state.', 'Record the reasoned decision, refresh the inbox and confirm the item leaves the awaiting-me queue or shows the next responsible actor.'] },
  { route: '/lex/investigations', title: 'Manage investigations', audience: 'Investigation teams and supervisors', purpose: 'Track confidential investigations from scope through findings sign-off.', actions: ['Filter by status, owner, allegation type, confidentiality and target date.', 'Open new work and confirm authority, scope and preservation requirements.', 'Track evidence, interviews, findings, review and closure.'] },
  { route: '/lex/investigations/[id]', title: 'Conduct an investigation', audience: 'Assigned investigators and reviewers', purpose: 'Operate one investigation with controlled evidence and findings.', actions: ['Review scope, authority, conflicts, custodians and legal hold requirements.', 'Record interviews, evidence receipts, activity and investigative decisions.', 'Draft findings, obtain distinct-actor sign-off and close with recommendations.'] },
  { route: '/lex/investigations/[id]/report', title: 'Prepare an investigation report', audience: 'Assigned investigators, reviewers and approving managers', purpose: 'Draft and review the formal findings, evidence summary and recommendations for one governed investigation.', actions: ['Confirm the investigation scope, parties, evidence inventory, interviews and unresolved limitations before writing findings.', 'Draft source-linked findings, recommendations and risk statements without exposing material outside the permitted audience.', 'Submit the report for distinct-actor review and confirm the approved version and decision appear on the investigation timeline.'] },
  { route: '/lex/knowledge-hub', title: 'Navigate the legal Knowledge Hub', audience: 'All authorized Watheeq legal practitioners', purpose: 'Start from one bilingual landing page for governed clauses, playbooks, documents, policies, precedents and learning.', actions: ['Use the central search to hand a query to the source-grounded reference library, or choose the knowledge category that owns your task.', 'Review recently added resources and open an item to confirm its authority, classification, version and source before relying on it.', 'Continue into drafting, regulation review or Ask the Library and keep any resulting advice or document linked to its governed sources.'] },
  { route: '/lex/learning-centre', title: 'Complete Watheeq learning modules', audience: 'Legal practitioners learning Watheeq workflows', purpose: 'Follow short source-linked operating guides and keep honest browser-local completion progress for the learning path.', actions: ['Open a module and work through the linked Watheeq guide before recording it as complete in the Learning Centre.', 'Use the module progress and overall path indicator to identify which drafting, compliance or contract guide remains unfinished.', 'Reopen completed modules whenever the operating process changes and clear the completion mark if the guide needs to be repeated.'] },
  { route: '/lex/library', title: 'Search the WatheeqTech legal library', audience: 'Legal researchers and practitioners', purpose: 'Find governed Saudi legal references and tenant knowledge.', actions: ['Search in Arabic or English and refine by source, topic, date and jurisdiction.', 'Open a result to review provenance, version and permitted use.', 'Link the reference to advice, drafting, a clause or another legal record.'] },
  { route: '/lex/library/[id]', title: 'Read a legal-library item', audience: 'Legal researchers and practitioners', purpose: 'Review one legal authority with its metadata and linked knowledge.', actions: ['Confirm title, source, jurisdiction, effective date and version.', 'Read or search the content and inspect related references.', 'Cite or link it in governed legal work according to tenant policy.'] },
  { route: '/lex/matters', title: 'Manage legal matters', audience: 'Legal operations and matter owners', purpose: 'Search, open and govern non-litigation legal work.', actions: ['Filter by owner, status, category, entity, risk and deadline.', 'Run conflict checking before creating a new matter.', 'Open the matter and keep triage, links, tasks and outcome current.'] },
  { route: '/lex/matters/[id]', title: 'Operate a legal matter', audience: 'Matter owners and assigned legal teams', purpose: 'Triage and manage one matter with linked work, documents and obligations.', actions: ['Confirm ownership, priority, conflict result, parties and handling strategy.', 'Maintain tasks, timeline, contracts, documents, obligations and decisions.', 'Resolve remaining work, record outcome and close through the lifecycle action.'] },
  { route: '/lex/notifications', title: 'Manage legal notifications', audience: 'All WatheeqTech users', purpose: 'Review legal alerts and control permitted notification preferences.', actions: ['Filter unread, task, SLA, approval, deadline or integration notifications.', 'Open the source legal record and complete the required action.', 'Mark handled notifications read and adjust channel preferences when authorized.'] },
  { route: '/lex/obligations', title: 'Manage legal obligations', audience: 'Contract owners and legal operations', purpose: 'Track contractual and legal commitments, owners, deadlines and escalation.', actions: ['Filter by due date, status, owner, contract, matter or risk.', 'Review extracted obligations before accepting them into the register.', 'Assign accountability, configure reminders and record fulfilment evidence.'] },
  { route: '/lex/playbooks', title: 'Manage clause playbooks', audience: 'Contract knowledge managers', purpose: 'Define preferred, fallback and prohibited positions by contract type.', actions: ['Open or create the playbook for the target contract category.', 'Add governed clauses with position, risk and negotiation guidance.', 'Approve and activate the playbook before using deviation analysis.'] },
  { route: '/lex/playbooks/portfolio', title: 'Triage contract playbook deviations', audience: 'Heads of contracts, contract lawyers and knowledge managers', purpose: 'Rank scored contracts by playbook compliance so low-scoring agreements receive review first.', actions: ['Filter by contract type and maximum compliance score, then keep ascending order to place the worst-scoring contracts first.', 'Compare scored, average, at-risk and healthy indicators for the visible page and inspect each contract’s deviation summary.', 'Open the affected contract or return to the playbook catalog to correct a contract deviation or improve the governing playbook.'] },
  { route: '/lex/policies', title: 'Browse the governed Policy Hub', audience: 'Legal knowledge, compliance and policy reviewers', purpose: 'Search the real regulation catalog in a compact bilingual policy-oriented view while preserving its source and governance state.', actions: ['Search by title, code or authority and narrow the visible collection by the regulation types returned from the governed catalog.', 'Review each source’s status, version, authority, jurisdiction and bilingual description before using it in legal work.', 'Open the full regulation workspace to inspect governance evidence, linked clauses and compliance effects or to perform an authorized change.'] },
  { route: '/lex/regulations', title: 'Manage the regulation library', audience: 'Legal knowledge and compliance teams', purpose: 'Maintain governed Saudi and tenant regulatory references.', actions: ['Search existing entries before creating or importing a regulation.', 'Maintain bilingual metadata, effective dates, source and supersession.', 'Route governance and link the approved regulation to clauses and rules.'] },
  { route: '/lex/reports', title: 'Generate legal reports', audience: 'Legal leaders, operations and auditors', purpose: 'Create governed contract, matter, obligation and operational reports.', actions: ['Choose the report and apply permitted period, entity, owner and status filters.', 'Preview totals and sample records for scope accuracy.', 'Export in the supported format and retain the request context for audit.'] },
  { route: '/lex/reports/analytics', title: 'Analyze report trends', audience: 'Legal leaders and analysts', purpose: 'Explore trends behind legal operations reports.', actions: ['Set the time period, organization and legal-domain scope.', 'Compare volume, cycle time, SLA, risk and outcome dimensions.', 'Drill to source records before sharing conclusions or exports.'] },
  { route: '/lex/reports/builder', title: 'Build a governed legal report', audience: 'Legal analysts, managers and authorized report authors', purpose: 'Compose a filtered legal report from supported datasets, fields, grouping and output controls while preserving scope.', actions: ['Choose the supported legal dataset and select only the fields, date range and organization scope needed for the report purpose.', 'Preview totals and sample rows, then adjust filters, grouping and sorting until the result matches the intended population.', 'Export or save the configuration when permitted and retain the report scope, requester and generation time with shared evidence.'] },
  { route: '/lex/service-desk', title: 'Operate the Legal Service Desk', audience: 'Requesters, providers and legal operations', purpose: 'Submit, triage and track legal services under configured SLA and approval rules.', actions: ['Use saved views to find drafts, approvals, routed work, SLA risk and delivery.', 'Open a request to complete the next permitted action.', 'Keep decisions and information exchanges on the governed request timeline.'] },
  { route: '/lex/service-desk/new', title: 'Create a legal request', audience: 'Eligible requesters', purpose: 'Submit a complete legal-service request through the platform.', actions: ['Choose an available bilingual service from the catalog.', 'Complete details, service requirements, priority justification and attachments.', 'Review and submit, then track approval and routing from the request page.'] },
  { route: '/lex/service-desk/[id]', title: 'Operate a legal request', audience: 'Requester, provider, approver and legal operations', purpose: 'Track one request from draft through approval, fulfilment and delivery confirmation.', actions: ['Review status, SLA, requirements, assignments, approval and timeline.', 'Complete the next permitted submit, approve, route, fulfil or confirm action.', 'Record notes and evidence before transitioning the request.'] },
  { route: '/lex/service-desk/intake', title: 'Triage inbound intake messages', audience: 'Legal intake teams and mailbox administrators', purpose: 'Inspect email-ingested and simulated intake messages and connect them to governed legal requests.', actions: ['Search or filter Pending, Processed and Errored messages, then open a row to inspect sender, subject, body and attachment metadata.', 'Open an already linked request or use the message sheet’s create-request handoff for an unlinked message; administrators may simulate inbound intake for testing.', 'Return to the queue and confirm the message is linked and processed, or preserve the error state and evidence for mailbox troubleshooting.'] },
  { route: '/lex/service-desk/notifications', title: 'Use Service Desk notifications and preferences', audience: 'All Legal Service Desk users', purpose: 'Read personal request notifications and control category-by-channel delivery preferences.', actions: ['Open the Inbox tab, review unread counts and follow an actionable notification to its source request before marking it read.', 'Use Mark all read only after checking the queue, then open Preferences to review request, case, hearing, judgment, contract and general categories.', 'Toggle only the channels you want to opt out of or restore, and confirm the switch remains in the expected state after the subscription saves.'] },
  { route: '/lex/service-desk/sla-board', title: 'Escalate at-risk Service Desk clocks', audience: 'Legal operations managers and service owners', purpose: 'Find acknowledgement or resolution clocks that are imminent, breached or already escalated.', actions: ['Review Breach imminent, Acknowledgement risk, Breached and Escalated indicators, then filter the clock table to the most urgent cohort.', 'Open the source legal request to verify owner and context, or use the permitted Escalate action with an operationally useful note.', 'Refresh the board and confirm the clock’s escalation level and status changed, then address the staffing or workflow cause in the source request.'] },
  { route: '/lex/settlements', title: 'Manage settlements and ADR', audience: 'Dispute and legal teams', purpose: 'Track negotiation, approvals and settlement evidence.', actions: ['Filter settlements by case, matter, status, owner and decision deadline.', 'Create or open the negotiation record and link the governing dispute.', 'Track offers, approvals, documents and final execution.'] },
  { route: '/lex/settlements/[id]', title: 'Operate a settlement', audience: 'Assigned lawyers, negotiators and approvers', purpose: 'Govern one settlement from authority through signed evidence.', actions: ['Review parties, dispute, authority, negotiation position and approval threshold.', 'Record offers and counteroffers as dated activity with supporting documents.', 'Obtain approval, preserve the executed settlement and update the linked case or matter.'] },
  { route: '/lex/signatures', title: 'Manage signature envelopes', audience: 'Contract teams and signature administrators', purpose: 'Prepare, send and track electronic signatures and custody evidence.', actions: ['Filter envelopes by status, provider, owner, recipient or related record.', 'Create an envelope only from the approved final document version.', 'Monitor recipient and provider events through completion, cancellation or expiry.'] },
  { route: '/lex/workflow-policies', title: 'Manage legal workflow policies', audience: 'Legal governance and workflow administrators', purpose: 'Create, edit and archive approval policies while monitoring their definitions, instances and decision performance.', actions: ['Use the Policies tab and KPI strip to review active, draft and archived policies plus routed, quorum and decision-speed indicators.', 'Create or edit the policy’s scope, stage, approver role or user, quorum, authority evidence and active state; use Definitions for the underlying workflow design.', 'Inspect Instances and analytics to verify new work routes as intended, then archive superseded policies instead of leaving overlapping active scopes.'] },
];

function routeToSlug(route: string) {
  if (route === '/lex') return 'home';
  return route
    .replace(/^\/lex\/?/, '')
    .replace(/\[id\]/g, 'record')
    .replace(/\[([^\]]+)\]/g, '$1')
    .replace(/\//g, '--');
}

type GuideWorkflow = 'admin' | 'detail' | 'insight' | 'queue' | 'workspace';

const INSIGHT_ROUTES = new Set([
  '/lex/admin/escalations',
  '/lex/admin/role-matrix',
  '/lex/analytics',
  '/lex/analytics/risk',
  '/lex/case-timeline/portfolio',
  '/lex/entities',
  '/lex/entities/[id]',
  '/lex/playbooks/portfolio',
  '/lex/reports',
  '/lex/reports/analytics',
]);

const WORKSPACE_ROUTES = new Set([
  '/lex/calendar',
  '/lex/case-timeline',
  '/lex/documents/editor',
  '/lex/drafting',
]);

function workflowFor(route: string): GuideWorkflow {
  if (INSIGHT_ROUTES.has(route)) return 'insight';
  if (WORKSPACE_ROUTES.has(route)) return 'workspace';
  if (route.includes('[id]')) return 'detail';
  if (route.startsWith('/lex/admin/')) return 'admin';
  return 'queue';
}

function prerequisitesFor(guide: RouteGuide): string[] {
  const workflow = workflowFor(guide.route);
  const items = [
    `Sign in as ${guide.audience.toLowerCase()} and confirm WatheeqTech shows ${guide.route}; hidden controls indicate that your account lacks the required permission.`,
  ];

  if (workflow === 'admin') {
    items.push('Prepare the approved bilingual values, policy decision or connector details before opening a form; do not use production records as test data.');
  } else if (workflow === 'detail') {
    items.push('Open the record from its owning register or a trusted notification so you begin with the correct tenant, record identifier and current lifecycle state.');
  } else if (workflow === 'insight') {
    items.push('Confirm the reporting scope and source-data freshness before interpreting a KPI, score or derived portfolio value.');
  } else if (workflow === 'workspace') {
    items.push('Identify the source record or workspace you intend to change and check its current owner, version, due date or lock before acting.');
  } else {
    items.push('Know the organization scope, status and urgency of the work you need to find before applying filters or saved views.');
  }

  items.push('Collect the reason, authority and supporting evidence required for any governed decision or state transition.');
  return items;
}

const STEP_TITLES: Record<GuideWorkflow, [string, string, string]> = {
  admin: ['Assess the current configuration', 'Make the governed change', 'Validate the configuration'],
  detail: ['Verify the record and state', 'Complete the permitted action', 'Confirm the transition'],
  insight: ['Establish the scope', 'Interpret the evidence', 'Act on the finding'],
  queue: ['Prioritize the work', 'Process the right item', 'Clear the queue safely'],
  workspace: ['Open the right context', 'Complete the task', 'Verify and hand off'],
};

function governanceFor(guide: RouteGuide): string[] {
  const workflow = workflowFor(guide.route);
  const common = [
    'Operate only within the tenant, role and record visibility granted to you.',
    'Record the decision, reason and supporting evidence before completing a governed action.',
  ];

  if (workflow === 'insight') {
    return [
      ...common,
      'Treat dashboard and derived Entity 360 values as decision support; verify material conclusions against the linked source record.',
      'Correct data in the owning legal record rather than editing an aggregate or exporting an ungoverned copy.',
    ];
  }
  if (workflow === 'admin') {
    return [
      ...common,
      'Check dependent services, roles, records and policies before deleting, deactivating or changing precedence.',
      'Use preview, evaluator, conflict-check or test controls when the page provides them, and verify the audit result after saving.',
    ];
  }
  return [
    ...common,
    'Use the page action for the transition rather than changing source data or maintaining a parallel offline status.',
    'Verify the resulting status, owner, timeline, version or audit event before leaving the page.',
  ];
}

function expectedResultFor(guide: RouteGuide): string {
  const task = guide.purpose.replace(/\.$/, '');
  return `You used ${guide.route} to ${task.charAt(0).toLowerCase()}${task.slice(1)}. The result is visible in WatheeqTech and traceable to the acting user, tenant and source legal record.`;
}

export const watheeqRouteArticles: DocArticle[] = watheeqRouteGuides.map((guide) => ({
  slug: `watheeq/pages/${routeToSlug(guide.route)}`,
  title: guide.title,
  description: guide.purpose,
  group: 'WatheeqTech pages',
  icon: BookOpen,
  updated: 'July 20, 2026',
  sections: [
    {
      id: 'page-purpose',
      title: 'Page purpose',
      blocks: [
        { type: 'text', text: guide.purpose },
        { type: 'table', headers: ['Application route', 'Intended audience'], rows: [[guide.route, guide.audience]] },
      ],
    },
    {
      id: 'before-you-start',
      title: 'Before you start',
      blocks: [{ type: 'bullets', items: prerequisitesFor(guide) }],
    },
    {
      id: 'how-to-use',
      title: 'How to use this page',
      blocks: [
        {
          type: 'steps',
          items: guide.actions.map((text, index) => ({
            title: STEP_TITLES[workflowFor(guide.route)][index],
            text,
          })),
        },
      ],
    },
    {
      id: 'governance',
      title: 'Governance and expected result',
      blocks: [
        { type: 'bullets', items: governanceFor(guide) },
        { type: 'callout', tone: 'success', title: 'Expected result', text: expectedResultFor(guide) },
      ],
    },
  ],
}));
