{{- if and .Values.clarioDrService.enabled (not .Values.clarioDrService.existingSecret) }}
{{- $dbName := default (default "dr_db" .Values.secrets.database.drDb) .Values.clarioDrService.databaseName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clario360.fullname" . }}-dr-credentials
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "clario-dr-service") | nindent 4 }}
type: Opaque
data:
  DR_DB_URL: {{ include "clario360.databaseUrl" (dict "root" . "dbName" $dbName) | b64enc | quote }}
  DR_VAULT_TOKEN: {{ .Values.clarioDrService.vault.token | default "" | b64enc | quote }}
  DR_VAULT_APPROLE_ROLE_ID: {{ .Values.clarioDrService.vault.appRoleRoleId | default "" | b64enc | quote }}
  DR_VAULT_APPROLE_SECRET_ID: {{ .Values.clarioDrService.vault.appRoleSecretId | default "" | b64enc | quote }}
  DR_ENROLL_TOKEN_PRIVATE_KEY_PEM: {{ .Values.clarioDrService.enrollToken.privateKeyPEM | default "" | b64enc | quote }}
  DR_ENROLL_TOKEN_PRIVATE_JWK: {{ .Values.clarioDrService.enrollToken.privateJWK | default "" | b64enc | quote }}
  DR_INTEGRATIONS_ENC_KEY: {{ .Values.clarioDrService.integrations.encKey | default "" | b64enc | quote }}
{{- end }}
