{{- $serviceAccount := .Values.clarioDrService.serviceAccount | default dict }}
{{- if and .Values.clarioDrService.enabled (or (not (hasKey $serviceAccount "create")) $serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clario360.serviceAccountName" (dict "root" . "component" "clario-dr-service" "svcConfig" .Values.clarioDrService) }}
  namespace: {{ include "clario360.namespace" . }}
  labels:
    {{- include "clario360.componentLabels" (dict "root" . "component" "clario-dr-service") | nindent 4 }}
  {{- with .Values.global.serviceAccountAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
