apiVersion: v1
kind: ServiceAccount
metadata:
  name: clario360-jupyterhub
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clario360-notebook
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clario360-jupyterhub
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "secrets", "configmaps", "events"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clario360-jupyterhub
subjects:
  - kind: ServiceAccount
    name: clario360-jupyterhub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: clario360-jupyterhub
