apiVersion: v1
kind: ResourceQuota
metadata:
  name: notebook-resource-quota
spec:
  hard:
    requests.cpu: {{ .Values.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.resourceQuota.requestsMemory | quote }}
    limits.cpu: {{ .Values.resourceQuota.limitsCpu | quote }}
    limits.memory: {{ .Values.resourceQuota.limitsMemory | quote }}
    persistentvolumeclaims: {{ .Values.resourceQuota.persistentVolumeClaims | quote }}
    requests.storage: {{ .Values.resourceQuota.requestsStorage | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: notebook-limit-range
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 500m
        memory: 1Gi
      default:
        cpu: "2"
        memory: 4Gi
