{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clario360-jupyter-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind }}
  target:
    name: clario360-jupyter-secrets
    creationPolicy: Owner
  data:
    - secretKey: JUPYTERHUB_OAUTH_CLIENT_SECRET
      remoteRef:
        key: clario360/jupyterhub
        property: client_secret
    - secretKey: JUPYTERHUB_DB_PASSWORD
      remoteRef:
        key: clario360/jupyterhub
        property: db_password
{{- end }}
