apiVersion: v1
kind: ConfigMap
metadata:
  name: clario360-notebooks
binaryData:
{{- range $path, $_ := .Files.Glob "notebooks/*.ipynb" }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc }}
{{- end }}
