package recover

import (
	"bytes"
	"html/template"
	"strconv"

	"github.com/jung-kurt/gofpdf"

	"github.com/clario360/platform/internal/forms"
)

// PDF layout constants (A4, mm). Kept explicit so the document is reproducible.
const (
	pdfMargin       = 15.0
	pdfContentWidth = 210.0 - 2*pdfMargin // A4 width (210mm) minus left+right margin
	pdfLineHeight   = 5.0
)

// Report localization notes
// ==========================
//
// Report string LITERALS are routed through evidenceLabels — a per-report label
// table keyed by a stable slug and resolved by the report's locale — so the same
// generator can emit an English or an Arabic evidence report. RenderEvidencePDFLocalized
// is the locale-aware entrypoint; RenderEvidencePDF keeps the legacy no-locale
// signature (English) so existing callers stay unchanged.
//
// gofpdf LIMITATION (do not "fix" here): the vendored gofpdf ships only the core
// Latin PDF fonts and performs NO Arabic glyph shaping or bidi reordering. Feeding
// it Arabic strings produces missing-glyph / visually-broken output. The locale
// threading + right-alignment ('R') implemented here is the SAFE, compiling
// scaffolding only.
//
// HTML->PDF path (recommended for customer-/regulator-facing Arabic): render the
// report as HTML with dir="rtl" and convert it with headless Chrome (chromedp) or
// wkhtmltopdf, which get RTL + Arabic shaping for free from the browser engine and
// let us reuse the notification-service email RTL CSS
// (internal/notification/service/template_service.go baseLayoutTemplate). The HTML
// half of that path is implemented and ready in RenderEvidenceHTML below; the only
// remaining follow-up is wiring the (heavier, binary-dependent) HTML->PDF converter
// behind the same entrypoint once a headless-Chrome dependency is approved. gofpdf
// stays for internal/English artifacts.

const (
	localeEN = "en"
	localeAR = "ar"
)

// reportLocaleDefault is the tenant/product default locale for customer-/regulator-
// facing reports (Watheeq / KSA tenants default to Arabic). It is applied when a
// caller passes an empty locale. The legacy RenderEvidencePDF wrapper passes localeEN
// explicitly so its output never regresses while the gofpdf Arabic-shaping gap is open.
const reportLocaleDefault = localeAR

// normalizeReportLocale collapses an arbitrary locale tag to the two supported
// report locales, defaulting to the tenant/product default when unset.
func normalizeReportLocale(locale string) string {
	switch locale {
	case localeAR:
		return localeAR
	case localeEN:
		return localeEN
	case "":
		return reportLocaleDefault
	default:
		if len(locale) >= 2 && locale[:2] == "ar" {
			return localeAR
		}
		return localeEN
	}
}

// alignFor returns the gofpdf cell alignment for a locale ("R" right-aligns Arabic
// text, "L" left-aligns Latin).
func alignFor(locale string) string {
	if locale == localeAR {
		return "R"
	}
	return "L"
}

// localizeLabel resolves a report label slug to text in the requested locale via
// forms.LocalizedText (the canonical backend bilingual string type, with built-in
// other-locale fallback). An unknown slug falls back to the slug itself.
func localizeLabel(cat map[string]forms.LocalizedText, key, locale string) string {
	if lt, ok := cat[key]; ok {
		return lt.Localize(locale)
	}
	return key
}

// evidenceLabels is the per-report label table for the regulatory evidence PDF/HTML.
// Arabic copy follows the Saudi-MSA termbase (frontend/scripts/i18n-glossary.json):
// disaster recovery = التعافي من الكوارث, runbook = دليل التشغيل, RTO/RPO/RTA/WORM kept
// verbatim + glossed once, approval (sign-off) = اعتماد, status = الحالة, audit trail =
// سجل التدقيق. Acronyms and product names (Clario Recover) are kept verbatim.
var evidenceLabels = map[string]forms.LocalizedText{
	"doc_title":       {EN: "Clario Recover — Regulatory Evidence Report", AR: "Clario Recover — تقرير الأدلة التنظيمية"},
	"generated":       {EN: "Generated", AR: "أُنشئ في"},
	"utc":             {EN: "UTC", AR: "بالتوقيت العالمي (UTC)"},
	"sec_event":       {EN: "Recovery Event", AR: "حدث التعافي"},
	"event_id":        {EN: "Event ID", AR: "معرّف الحدث"},
	"sub_solution":    {EN: "Sub-solution", AR: "الحل الفرعي"},
	"application":     {EN: "Application", AR: "التطبيق"},
	"recovery_tier":   {EN: "Recovery tier", AR: "فئة التعافي"},
	"sec_proof":       {EN: "Proof Metadata", AR: "بيانات الإثبات الوصفية"},
	"no_proof":        {EN: "No proof envelope is attached to this report.", AR: "لا يوجد مغلَّف إثبات مرفق بهذا التقرير."},
	"proof_status":    {EN: "Proof status", AR: "حالة الإثبات"},
	"proof_reason":    {EN: "Proof reason", AR: "سبب الإثبات"},
	"payload_hash":    {EN: "Payload hash", AR: "بصمة الحمولة"},
	"hash_algorithm":  {EN: "Hash algorithm", AR: "خوارزمية البصمة"},
	"generated_by":    {EN: "Generated by", AR: "أُنشئ بواسطة"},
	"signature":       {EN: "Signature", AR: "التوقيع"},
	"ledger":          {EN: "Ledger", AR: "السجل"},
	"ledger_seq":      {EN: "Ledger seq", AR: "تسلسل السجل"},
	"previous_hash":   {EN: "Previous hash", AR: "البصمة السابقة"},
	"entry_hash":      {EN: "Entry hash", AR: "بصمة القيد"},
	"root_hash":       {EN: "Root hash", AR: "البصمة الجذرية"},
	"anchor_status":   {EN: "Anchor status", AR: "حالة التثبيت"},
	"merkle_root":     {EN: "Merkle root", AR: "جذر ميركل"},
	"worm_object":     {EN: "WORM object", AR: "كائن WORM"},
	"worm_version":    {EN: "WORM version", AR: "إصدار WORM"},
	"sec_runbook":     {EN: "Runbook Executed — RTO vs RTA", AR: "دليل التشغيل المُنفَّذ — RTO مقابل RTA"},
	"runbook":         {EN: "Runbook", AR: "دليل التشغيل"},
	"run_id":          {EN: "Run ID", AR: "معرّف التنفيذ"},
	"mode":            {EN: "Mode", AR: "الوضع"},
	"status":          {EN: "Status", AR: "الحالة"},
	"started":         {EN: "Started", AR: "بدأ في"},
	"completed":       {EN: "Completed", AR: "اكتمل في"},
	"rto_target":      {EN: "RTO target (s)", AR: "هدف زمن الاسترداد RTO (ثانية)"},
	"rta_actual":      {EN: "RTA actual (s)", AR: "زمن الاسترداد الفعلي RTA (ثانية)"},
	"rto_outcome":     {EN: "RTO outcome", AR: "نتيجة RTO"},
	"rto_breached":    {EN: "BREACHED by", AR: "تم التجاوز بمقدار"},
	"seconds_suffix":  {EN: "s", AR: "ثانية"},
	"rto_within":      {EN: "Within target", AR: "ضمن الهدف"},
	"rto_uncaptured":  {EN: "Not yet captured", AR: "لم يُسجَّل بعد"},
	"no_runbook":      {EN: "No runbook execution record is linked to this event.", AR: "لا يوجد سجل تنفيذ دليل تشغيل مرتبط بهذا الحدث."},
	"sec_approvals":   {EN: "Approvals", AR: "الاعتمادات"},
	"no_approvals":    {EN: "No approvals recorded for this event.", AR: "لم تُسجَّل أي اعتمادات لهذا الحدث."},
	"pinned_scan":     {EN: "pinned to integrity scan", AR: "مثبَّت إلى فحص السلامة"},
	"note_prefix":     {EN: "note:", AR: "ملاحظة:"},
	"sec_integrity":   {EN: "Integrity-Check Results", AR: "نتائج فحص السلامة"},
	"no_integrity":    {EN: "No integrity-check results recorded for this event.", AR: "لم تُسجَّل أي نتائج فحص سلامة لهذا الحدث."},
	"scan_prefix":     {EN: "scan", AR: "فحص"},
	"sec_timeline":    {EN: "Full Timeline", AR: "الجدول الزمني الكامل"},
	"no_timeline":     {EN: "No timeline entries recorded for this event.", AR: "لم تُسجَّل أي قيود في الجدول الزمني لهذا الحدث."},
	"subsol_it_dr":    {EN: "IT Disaster Recovery", AR: "التعافي من الكوارث لتقنية المعلومات"},
	"subsol_cloud_dr": {EN: "Cloud Disaster Recovery", AR: "التعافي من الكوارث السحابي"},
	"subsol_cyber":    {EN: "Cyber Recovery", AR: "التعافي السيبراني"},
}

// RenderEvidencePDF renders an EvidenceReport as a real, regulator-ready PDF
// document using gofpdf (genuine PDF generation, not an HTML stand-in). It
// preserves the legacy (English) signature; RenderEvidencePDFLocalized is the
// locale-aware entrypoint. The document carries every section the contract
// requires — the runbook executed, RTO vs RTA, approvals, integrity-check
// results, and the full timeline — each populated from the report's real data.
func RenderEvidencePDF(rep *EvidenceReport) ([]byte, error) {
	return RenderEvidencePDFLocalized(rep, localeEN)
}

// RenderEvidencePDFLocalized renders the evidence report as a PDF in the requested
// locale, resolving every label through evidenceLabels and right-aligning cells for
// Arabic. See the "gofpdf LIMITATION" / "HTML->PDF path" notes above: for a shaped,
// customer-/regulator-facing Arabic PDF use RenderEvidenceHTML + a headless-Chrome
// converter. This function is the label-catalog + locale threading + alignment
// scaffolding.
func RenderEvidencePDFLocalized(rep *EvidenceReport, locale string) ([]byte, error) {
	locale = normalizeReportLocale(locale)
	align := alignFor(locale)
	lbl := func(key string) string { return localizeLabel(evidenceLabels, key, locale) }

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetTitle(lbl("doc_title"), false)
	pdf.SetAutoPageBreak(true, pdfMargin)
	pdf.AddPage()

	// --- Title block. --------------------------------------------------------
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(pdfContentWidth, 9, lbl("doc_title"), "", 1, align, false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(90, 90, 90)
	pdf.CellFormat(pdfContentWidth, 5, lbl("generated")+" "+fmtTime(rep.GeneratedAt)+" "+lbl("utc"), "", 1, align, false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(3)

	// --- Event identity. -----------------------------------------------------
	pdfSectionHeading(pdf, align, lbl("sec_event"))
	pdfKeyValue(pdf, align, lbl("event_id"), rep.EventID.String())
	pdfKeyValue(pdf, align, lbl("sub_solution"), labelSubSolution(rep.SubSolution, locale))
	if rep.ApplicationName != "" || rep.ApplicationKey != "" {
		pdfKeyValue(pdf, align, lbl("application"), joinAppLabel(rep.ApplicationName, rep.ApplicationKey))
	}
	if rep.RecoveryTier != "" {
		pdfKeyValue(pdf, align, lbl("recovery_tier"), rep.RecoveryTier)
	}
	pdf.Ln(2)

	pdfSectionHeading(pdf, align, lbl("sec_proof"))
	if rep.Proof == nil {
		pdfMuted(pdf, align, lbl("no_proof"))
	} else {
		pdfKeyValue(pdf, align, lbl("proof_status"), rep.Proof.Status)
		if rep.Proof.Reason != "" {
			pdfKeyValue(pdf, align, lbl("proof_reason"), rep.Proof.Reason)
		}
		pdfKeyValue(pdf, align, lbl("payload_hash"), rep.Proof.PayloadHash)
		pdfKeyValue(pdf, align, lbl("hash_algorithm"), rep.Proof.PayloadHashAlgorithm)
		if rep.Proof.GeneratedBy != "" {
			pdfKeyValue(pdf, align, lbl("generated_by"), rep.Proof.GeneratedBy)
		}
		pdfKeyValue(pdf, align, lbl("signature"), rep.Proof.Signature.Status)
		if rep.Proof.HashChain != nil {
			pdfKeyValue(pdf, align, lbl("ledger"), rep.Proof.HashChain.Ledger)
			pdfKeyValue(pdf, align, lbl("ledger_seq"), strconv.FormatInt(rep.Proof.HashChain.Seq, 10))
			pdfKeyValue(pdf, align, lbl("previous_hash"), rep.Proof.HashChain.PreviousHash)
			pdfKeyValue(pdf, align, lbl("entry_hash"), rep.Proof.HashChain.EntryHash)
			pdfKeyValue(pdf, align, lbl("root_hash"), rep.Proof.HashChain.RootHash)
		}
		if rep.Proof.Anchor != nil {
			pdfKeyValue(pdf, align, lbl("anchor_status"), rep.Proof.Anchor.Status)
			if rep.Proof.Anchor.MerkleRoot != "" {
				pdfKeyValue(pdf, align, lbl("merkle_root"), rep.Proof.Anchor.MerkleRoot)
			}
			if rep.Proof.Anchor.WORMObjectKey != "" {
				pdfKeyValue(pdf, align, lbl("worm_object"), rep.Proof.Anchor.WORMObjectKey)
				pdfKeyValue(pdf, align, lbl("worm_version"), rep.Proof.Anchor.WORMVersionID)
			}
		}
	}
	pdf.Ln(2)

	// --- Runbook executed + RTO vs RTA. --------------------------------------
	pdfSectionHeading(pdf, align, lbl("sec_runbook"))
	if rep.RunbookExecution != nil {
		e := rep.RunbookExecution
		pdfKeyValue(pdf, align, lbl("runbook"), e.RunbookName)
		pdfKeyValue(pdf, align, lbl("run_id"), e.RunID.String())
		pdfKeyValue(pdf, align, lbl("mode"), e.Mode)
		pdfKeyValue(pdf, align, lbl("status"), e.Status)
		pdfKeyValue(pdf, align, lbl("started"), fmtTime(e.StartedAt))
		pdfKeyValue(pdf, align, lbl("completed"), fmtTimePtr(e.CompletedAt))
		pdfKeyValue(pdf, align, lbl("rto_target"), strconv.Itoa(e.RTOTargetSeconds))
		pdfKeyValue(pdf, align, lbl("rta_actual"), fmtIntPtr(e.RTAActualSeconds))
		if e.RTABreach {
			pdf.SetTextColor(176, 0, 32)
			pdfKeyValue(pdf, align, lbl("rto_outcome"), lbl("rto_breached")+" "+strconv.Itoa(e.BreachSeconds)+lbl("seconds_suffix"))
			pdf.SetTextColor(0, 0, 0)
		} else if e.RTAActualSeconds != nil {
			pdf.SetTextColor(0, 120, 60)
			pdfKeyValue(pdf, align, lbl("rto_outcome"), lbl("rto_within"))
			pdf.SetTextColor(0, 0, 0)
		} else {
			pdfKeyValue(pdf, align, lbl("rto_outcome"), lbl("rto_uncaptured"))
		}
	} else {
		pdfMuted(pdf, align, lbl("no_runbook"))
	}
	pdf.Ln(2)

	// --- Approvals. ----------------------------------------------------------
	pdfSectionHeading(pdf, align, lbl("sec_approvals"))
	if len(rep.Approvals) == 0 {
		pdfMuted(pdf, align, lbl("no_approvals"))
	} else {
		for i := range rep.Approvals {
			a := &rep.Approvals[i]
			line := fmtTime(a.ApprovedAt) + "  —  " + a.Approver + " (" + a.Action + ")"
			pdfBullet(pdf, align, line)
			if a.ScanID != "" {
				pdfBulletSub(pdf, align, lbl("pinned_scan")+" "+a.ScanID)
			}
			if a.Note != "" {
				pdfBulletSub(pdf, align, lbl("note_prefix")+" "+a.Note)
			}
		}
	}
	pdf.Ln(2)

	// --- Integrity-check results (cyber recovery). ---------------------------
	pdfSectionHeading(pdf, align, lbl("sec_integrity"))
	if len(rep.IntegrityChecks) == 0 {
		pdfMuted(pdf, align, lbl("no_integrity"))
	} else {
		for i := range rep.IntegrityChecks {
			c := &rep.IntegrityChecks[i]
			verdict := c.Verdict
			if c.Passed {
				pdf.SetTextColor(0, 120, 60)
			} else {
				pdf.SetTextColor(176, 0, 32)
			}
			pdfBullet(pdf, align, fmtTime(c.CheckedAt)+"  —  "+verdict)
			pdf.SetTextColor(0, 0, 0)
			if c.ScanID != "" {
				pdfBulletSub(pdf, align, lbl("scan_prefix")+" "+c.ScanID)
			}
			if c.Detail != "" {
				pdfBulletSub(pdf, align, c.Detail)
			}
		}
	}
	pdf.Ln(2)

	// --- Full timeline. ------------------------------------------------------
	pdfSectionHeading(pdf, align, lbl("sec_timeline"))
	if len(rep.Timeline) == 0 {
		pdfMuted(pdf, align, lbl("no_timeline"))
	} else {
		for i := range rep.Timeline {
			t := &rep.Timeline[i]
			pdf.SetFont("Helvetica", "B", 8)
			pdf.CellFormat(36, pdfLineHeight, fmtTime(t.At), "", 0, align, false, 0, "")
			pdf.SetFont("Helvetica", "", 8)
			line := t.Action
			if t.Actor != "" {
				line += "  ·  " + t.Actor
			}
			pdf.MultiCell(pdfContentWidth-36, pdfLineHeight, line, "", align, false)
			if t.Summary != "" {
				pdf.SetX(pdfMargin + 36)
				pdf.SetTextColor(90, 90, 90)
				pdf.SetFont("Helvetica", "I", 8)
				pdf.MultiCell(pdfContentWidth-36, pdfLineHeight, t.Summary, "", align, false)
				pdf.SetTextColor(0, 0, 0)
			}
		}
	}

	if err := pdf.Error(); err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// --- PDF layout helpers -----------------------------------------------------

func pdfSectionHeading(pdf *gofpdf.Fpdf, align, title string) {
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetFillColor(232, 240, 236)
	pdf.CellFormat(pdfContentWidth, 7, title, "", 1, align, true, 0, "")
	pdf.Ln(1)
}

func pdfKeyValue(pdf *gofpdf.Fpdf, align, key, value string) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(45, pdfLineHeight, key, "", 0, align, false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.MultiCell(pdfContentWidth-45, pdfLineHeight, valueOrDash(value), "", align, false)
}

func pdfBullet(pdf *gofpdf.Fpdf, align, text string) {
	pdf.SetFont("Helvetica", "", 9)
	pdf.CellFormat(4, pdfLineHeight, "-", "", 0, align, false, 0, "")
	pdf.MultiCell(pdfContentWidth-4, pdfLineHeight, text, "", align, false)
}

func pdfBulletSub(pdf *gofpdf.Fpdf, align, text string) {
	pdf.SetX(pdfMargin + 6)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(90, 90, 90)
	pdf.MultiCell(pdfContentWidth-6, pdfLineHeight, text, "", align, false)
	pdf.SetTextColor(0, 0, 0)
}

func pdfMuted(pdf *gofpdf.Fpdf, align, text string) {
	pdf.SetFont("Helvetica", "I", 9)
	pdf.SetTextColor(120, 120, 120)
	pdf.MultiCell(pdfContentWidth, pdfLineHeight, text, "", align, false)
	pdf.SetTextColor(0, 0, 0)
}

func valueOrDash(v string) string {
	if v == "" {
		return "—"
	}
	return v
}

func joinAppLabel(name, key string) string {
	switch {
	case name != "" && key != "":
		return name + " (" + key + ")"
	case name != "":
		return name
	default:
		return key
	}
}

func labelSubSolution(s, locale string) string {
	switch s {
	case AuditSubSolutionITDR:
		return localizeLabel(evidenceLabels, "subsol_it_dr", locale)
	case AuditSubSolutionCloudDR:
		return localizeLabel(evidenceLabels, "subsol_cloud_dr", locale)
	case AuditSubSolutionCyberRecovery:
		return localizeLabel(evidenceLabels, "subsol_cyber", locale)
	default:
		return s
	}
}

// RenderEvidenceHTML renders the evidence report as a self-contained HTML document
// in the requested locale. It is the "HTML half" of the recommended HTML->PDF path:
// unlike gofpdf, a browser engine shapes Arabic glyphs and applies bidi/RTL from the
// dir="rtl" attribute, so this HTML converts to a correct Arabic PDF via headless
// Chrome (chromedp) / wkhtmltopdf. The inline RTL styling mirrors the notification
// email RTL CSS (dir/text-align driven by locale). Wiring the actual HTML->PDF
// converter is the deferred follow-up (it needs an approved headless-Chrome binary
// dependency); this function makes the localized, RTL-correct source ready to feed it.
func RenderEvidenceHTML(rep *EvidenceReport, locale string) ([]byte, error) {
	locale = normalizeReportLocale(locale)
	lbl := func(key string) string { return localizeLabel(evidenceLabels, key, locale) }
	dir := "ltr"
	textAlign := "left"
	if locale == localeAR {
		dir = "rtl"
		textAlign = "right"
	}

	type kvRow struct{ K, V string }
	type section struct {
		Title string
		Rows  []kvRow
		Muted string
	}
	data := struct {
		Lang      string
		Dir       string
		TextAlign string
		Title     string
		Generated string
		Sections  []section
	}{
		Lang:      locale,
		Dir:       dir,
		TextAlign: textAlign,
		Title:     lbl("doc_title"),
		Generated: lbl("generated") + " " + fmtTime(rep.GeneratedAt) + " " + lbl("utc"),
	}

	event := section{Title: lbl("sec_event"), Rows: []kvRow{
		{lbl("event_id"), rep.EventID.String()},
		{lbl("sub_solution"), labelSubSolution(rep.SubSolution, locale)},
	}}
	if rep.ApplicationName != "" || rep.ApplicationKey != "" {
		event.Rows = append(event.Rows, kvRow{lbl("application"), joinAppLabel(rep.ApplicationName, rep.ApplicationKey)})
	}
	if rep.RecoveryTier != "" {
		event.Rows = append(event.Rows, kvRow{lbl("recovery_tier"), rep.RecoveryTier})
	}
	data.Sections = append(data.Sections, event)

	runbook := section{Title: lbl("sec_runbook")}
	if rep.RunbookExecution != nil {
		e := rep.RunbookExecution
		runbook.Rows = []kvRow{
			{lbl("runbook"), e.RunbookName},
			{lbl("run_id"), e.RunID.String()},
			{lbl("mode"), e.Mode},
			{lbl("status"), e.Status},
			{lbl("started"), fmtTime(e.StartedAt)},
			{lbl("completed"), fmtTimePtr(e.CompletedAt)},
			{lbl("rto_target"), strconv.Itoa(e.RTOTargetSeconds)},
			{lbl("rta_actual"), fmtIntPtr(e.RTAActualSeconds)},
		}
		switch {
		case e.RTABreach:
			runbook.Rows = append(runbook.Rows, kvRow{lbl("rto_outcome"), lbl("rto_breached") + " " + strconv.Itoa(e.BreachSeconds) + lbl("seconds_suffix")})
		case e.RTAActualSeconds != nil:
			runbook.Rows = append(runbook.Rows, kvRow{lbl("rto_outcome"), lbl("rto_within")})
		default:
			runbook.Rows = append(runbook.Rows, kvRow{lbl("rto_outcome"), lbl("rto_uncaptured")})
		}
	} else {
		runbook.Muted = lbl("no_runbook")
	}
	data.Sections = append(data.Sections, runbook)

	const tmpl = `<!DOCTYPE html>
<html lang="{{.Lang}}" dir="{{.Dir}}">
<head><meta charset="utf-8"><title>{{.Title}}</title>
<style>
body{font-family:Arial, sans-serif; color:#111; margin:24px; text-align:{{.TextAlign}}; direction:{{.Dir}};}
h1{font-size:20px; margin:0 0 4px;} .muted{color:#777; font-size:12px;}
h2{font-size:14px; background:#e8f0ec; padding:6px 10px; margin:18px 0 8px;}
table{width:100%; border-collapse:collapse;} td{padding:4px 8px; vertical-align:top; font-size:12px;}
td.k{font-weight:bold; width:220px; color:#333;}
</style></head>
<body>
<h1>{{.Title}}</h1>
<div class="muted">{{.Generated}}</div>
{{range .Sections}}<h2>{{.Title}}</h2>
{{if .Muted}}<div class="muted">{{.Muted}}</div>{{else}}<table>{{range .Rows}}<tr><td class="k">{{.K}}</td><td>{{.V}}</td></tr>{{end}}</table>{{end}}
{{end}}
</body></html>`

	t, err := template.New("evidence").Parse(tmpl)
	if err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
