package engine

import "github.com/prometheus/client_golang/prometheus"

type Metrics struct {
	PredictionsGeneratedTotal *prometheus.CounterVec
	PredictionAccuracy        *prometheus.GaugeVec
	PredictionLatencySeconds  *prometheus.HistogramVec
	ModelDriftScore           *prometheus.GaugeVec
	ModelRetrainingTotal      *prometheus.CounterVec
	ModelRetrainingDuration   *prometheus.HistogramVec
}

func NewMetrics(reg prometheus.Registerer) *Metrics {
	if reg == nil {
		reg = prometheus.NewRegistry()
	}
	m := &Metrics{
		PredictionsGeneratedTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "vciso_prediction_generated_total",
			Help: "Total predictive engine outputs generated by type and model version.",
		}, []string{"prediction_type", "model_version"}),
		PredictionAccuracy: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Name: "vciso_prediction_accuracy",
			Help: "Average prediction accuracy by prediction type.",
		}, []string{"prediction_type"}),
		PredictionLatencySeconds: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Name:    "vciso_prediction_latency_seconds",
			Help:    "Prediction generation latency by type.",
			Buckets: prometheus.DefBuckets,
		}, []string{"prediction_type"}),
		ModelDriftScore: prometheus.NewGaugeVec(prometheus.GaugeOpts{
			Name: "vciso_model_drift_score",
			Help: "Current model drift score by model type.",
		}, []string{"model_type"}),
		ModelRetrainingTotal: prometheus.NewCounterVec(prometheus.CounterOpts{
			Name: "vciso_model_retraining_total",
			Help: "Retraining executions by model type and trigger.",
		}, []string{"model_type", "trigger"}),
		ModelRetrainingDuration: prometheus.NewHistogramVec(prometheus.HistogramOpts{
			Name:    "vciso_model_retraining_duration_seconds",
			Help:    "Retraining runtime by model type.",
			Buckets: prometheus.DefBuckets,
		}, []string{"model_type"}),
	}
	reg.MustRegister(
		m.PredictionsGeneratedTotal,
		m.PredictionAccuracy,
		m.PredictionLatencySeconds,
		m.ModelDriftScore,
		m.ModelRetrainingTotal,
		m.ModelRetrainingDuration,
	)
	return m
}
